### ISSUE TITLE
Unable to use multi-part yaml files --- separated

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1108]
**Describe the bug**
When defining custom rules, I expected to be able to group similar rules into a yaml file, such as:

```
metadata:
  name: <name>
  id: <id>
  category: <category>
definition:
  <definition>
---
metadata:
  name: <name>
  id: <id>
  category: <category>
definition:
  <definition>
```

However this fails with:

```
yaml.composer.ComposerError: expected a single document in the stream
```

**To Reproduce**
1. Create a file with two or more definitions
2. run `checkov -f <your-file>.tf --external-checks-dir /your/path --quiet`

**Expected behavior**
Multi-part files should be loaded correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/42545485/115537338-a27da400-a292-11eb-9625-e3123195958f.png)

**Desktop (please complete the following information):**
 - OS: OS X
 - Checkov Version: 2.0.64
