### ISSUE TITLE
Unable to Load Custom V2 Yaml Checks with --external-checks-dir

### ISSUE THREAD

**Issue by jmeredith16** [bridgecrewio/checkov#1162]
Hello Checkov Team,

`checkov==2.0.107`

I'm struggling to load a custom Checkov check in the new `.yaml` format with `--external-checks-dir`.

**What I've done** 
I've copied an existing check (just a POC for myself) and put it into a file `mychecks/S3BucketPublicAccessBlock.yaml`

```yaml
metadata:
  name: "Ensure that S3 bucket has a Public Access block"
  category: "Networking"
  id: "CUSTOM_AWS_6"
definition:
  and:
    - resource_types:
        - aws_s3_bucket
      connected_resource_types:
        - aws_s3_bucket_public_access_block
      operator:  exists
      cond_type: connection
    - cond_type: filter
      attribute: resource_type
      value:
        - aws_s3_bucket
      operator: within
    - cond_type: attribute
      attribute: block_public_acls
      value: true
      operator: equals
      resource_types:
        - aws_s3_bucket_public_access_block
    - cond_type: attribute
      attribute: block_public_policy
      value: true
      operator: equals
      resource_types:
        - aws_s3_bucket_public_access_block
```

When I execute Checkov with `checkov -d /tmp/project --external-checks-dir mychecks` against some example terraform, I don't see the check in my run output. I looked in the code and I think I see the issue:

https://github.com/bridgecrewio/checkov/blob/master/checkov/common/checks/base_check_registry.py#L165 looks for arguments passed to `--external-checks-dir` and loads only those with a `.py`.

**What I expect**
I expect checkov to load both `.py` or `.yaml` checks in the specified `--external-checks-dir` directory. Or have the ability to load the `.yaml` files in a different way.

Is there a separate way to load external `.yaml` files, or does this logic need to be extended to include the new version checks?

Thanks for your help and guidance!

**Comment by nimrodkor** [comment]
Hey @jmeredith16 (& @rohantandon)!

I'll check it out, but I expect [this line](https://github.com/bridgecrewio/checkov/blob/540cd26149a5993f7ffb9163c2ada1aee387631c/checkov/terraform/runner.py#L119) to be the one to do the trick, calling the [graph checks registry](https://github.com/bridgecrewio/checkov/blob/540cd26149a5993f7ffb9163c2ada1aee387631c/checkov/terraform/checks_infra/registry.py#L40). Taking a look now

**Comment by nimrodkor** [comment]
Looking at the code - we have a dedupe filter there to avoid creating multiple copies of the same check.
Can you modify the check ID and try again?

The filter ([found here](https://github.com/bridgecrewio/checkov/blob/540cd26149a5993f7ffb9163c2ada1aee387631c/checkov/terraform/checks_infra/registry.py#L37)):
```python
                        if not any([c for c in self.checks if check.id == c.id]):
                            self.checks.append(check)
```

**Comment by nimrodkor** [comment]
Hey @jmeredith16 , I'm having trouble reproducing this. The only way this happened is if I gave the wrong relative path.
Can you try the same command, with an absolute path to your external checks dir, and share the output?

**Comment by jmeredith16** [comment]
Thanks @nimrodkor - I'm out for a while this morning, but I'll check my code and try the absolute path + more details when I get a moment. Could just be a dumb mistake on my end.

Thanks for your help.

**Comment by jmeredith16** [comment]
@nimrodkor You are 100% correct - I can see it is loading the custom test now that I futz with the name and ID. My confusion continues though!

I have a test project with the following Terraform
```terraform
resource "aws_s3_bucket" "bad_credit_cards_bucket" {
  region        = "us-east-1"
  bucket        = "some-example-name"
  acl           = "public-read"
  force_destroy = true

  tags = {
    Scope = "PCI",
  }
}
```

I've copied the check [here](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/graph_checks/aws/S3BucketHasPublicAccessBlock.yaml) to a `myTests` directory, changed the name slightly (`S3BucketPublicAccessBlock.yml` (mine) vs `S3BucketHasPublicAccessBlock.yaml` (checkov)) and changed the contents to:

```yml
metadata:
  name: "JoeSucks Ensure that S3 bucket has a Public Access block"
  category: "Networking"
  id: "CUSTOM_AWS_0123"
definition:
  and:
    - resource_types:
        - aws_s3_bucket
      connected_resource_types:
        - aws_s3_bucket_public_access_block
      operator:  exists
      cond_type: connection
    - cond_type: filter
      attribute: resource_type
      value:
        - aws_s3_bucket
      operator: within
    - cond_type: attribute
      attribute: block_public_acls
      value: true
      operator: equals
      resource_types:
        - aws_s3_bucket_public_access_block
    - cond_type: attribute
      attribute: block_public_policy
      value: true
      operator: equals
      resource_types:
        - aws_s3_bucket_public_access_block
```

When I run `checkov` in my Docker container with custom checks mounted in `myTests`, I see my copied custom check running in the output, but do not see the checkov-builtin test `CKV2_AWS_6`.

```
[root@23c1a422edc0 project]# checkov --no-guide -d /tmp/project --external-checks-dir /myTests
...
           _               _
       ___| |__   ___  ___| | _______   __
      / __| '_ \ / _ \/ __| |/ / _ \ \ / /
     | (__| | | |  __/ (__|   < (_) \ V /
      \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.107
Update available 2.0.107 -> 2.0.110
Run pip3 install -U checkov to update


terraform scan results:

Passed checks: 17, Failed checks: 22, Skipped checks: 4
...
Check: CUSTOM_AWS_0123: "JoeSucks Ensure that S3 bucket has a Public Access block"
	FAILED for resource: aws_s3_bucket.bad_credit_cards_bucket
	File: /terraform-stuffs/main.tf:11-20

		11 | resource "aws_s3_bucket" "bad_credit_cards_bucket" {
		12 |   region        = "us-east-1"
		13 |   bucket        = "some-example-name"
		14 |   acl           = "public-read"
		15 |   force_destroy = true
		16 |
		17 |   tags = {
		18 |     Scope = "PCI",
		19 |   }
		20 | }
```

Do I need to add additional arguments to my command in order to run the new graph checks? Is there another reason it isn't triggered? Another thing I'm messing up?

Thanks

**Comment by gruebel** [comment]
I think @nimrodkor is already working on a fix for the yaml checks included in `checkov` -> #1166

**Comment by lindseyvolta** [comment]
I'm having a similar issue with CloudFormation. I'm able to create and execute a custom policy using Python, but any YAML checks are being ignored. 

- `template.yaml`
- `python/`
- `yaml/`

I'm just using the sample custom policy example [here](https://www.checkov.io/3.Custom%20Policies/Examples.html). 
```

---
metadata:
 name: "Check that all resources are tagged with the key - env"
 id: "CKV2_AWS_1"
 category: "GENERAL_SECURITY"
definition:
       cond_type: "attribute"
       resource_types: "all"
       attribute: "tags.env"
       operator: "exists"
```

When I run it, it seems to ignore the custom check and only runs the default policy checks. I've tried passing in the absolute path as well and it doesn't help. 

`checkov -d . --external-checks-dir ./yaml`
