### ISSUE TITLE
Check CKV2_AZURE_21 conflicts with rule CKV_AZURE_34

### ISSUE THREAD

**Issue by rdenchev** [bridgecrewio/checkov#1317]
I have a Azure Storage Account with Azure Storage Container.
To fullfill the check CKV_AZURE_34, I have set "container_access_type=private" for the Azure Storage Container.
To fullfill the check CKV2_AZURE_21, "container_access_type=blob" is required which leads to CKV_AZURE_34. See https://github.com/bridgecrewio/checkov/blob/d32adef6e13ce9f769e86edffd49e6ae1c6f5da5/checkov/terraform/checks/graph_checks/azure/StorageLoggingIsEnabledForBlobService.yaml#L29

**Comment by gruebel** [comment]
I think the part
```yaml
    - resource_types:
        - azurerm_storage_container
      operator:  equals
      cond_type: attribute
      attribute: container_access_type
      value: "blob"
```
can be omitted completely, because enabling logging should be not dependable on the allowed/disallowed anonymous access of the storage container. @schosterbarak do you have any thoughts on this?

**Comment by nimrodkor** [comment]
I'd like to propose this change to the definition:
```yaml
definition:
  or:
    - resource_types:
      - azurerm_storage_container
      operator:  not_equals
      cond_type: attribute
      attribute: container_access_type
      value: "blob"
    - and:
      - resource_types:
          - azurerm_storage_container
        connected_resource_types:
          - azurerm_storage_account
        operator: exists
        cond_type: connection
      - resource_types:
          - azurerm_storage_account
        connected_resource_types:
          - azurerm_log_analytics_storage_insights
        operator:  exists
        cond_type: connection
      - resource_types:
          - azurerm_log_analytics_storage_insights
        operator:  exists
        cond_type: attribute
        attribute: blob_container_names
      - resource_types:
          - azurerm_storage_container
        operator:  equals
        cond_type: attribute
        attribute: container_access_type
        value: "blob"
      - cond_type: filter
        attribute: resource_type
        value:
          - azurerm_storage_container
        operator: within
```

WDYT @gruebel @rdenchev ?

**Comment by rdenchev** [comment]
@nimrodkor the following part is obsolete as the connection between azurerm_storage_container and azurerm_storage_account is required by default (see azurerm_storage_container.storage_account_name in  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_container)

``` yaml
- resource_types:
        - azurerm_storage_container
      connected_resource_types:
        - azurerm_storage_account
      operator: exists
      cond_type: connection
```
I have successfully tested your code without the above part:

``` yaml
metadata:
  id: "CKV2_AZURE_21"
  name: "Ensure Storage logging is enabled for Blob service for read requests"
  category: "LOGGING"
definition:
  or:
    - resource_types:
      - azurerm_storage_container
      operator:  not_equals
      cond_type: attribute
      attribute: container_access_type
      value: "blob"
    - and:
      - resource_types:
          - azurerm_storage_account
        connected_resource_types:
          - azurerm_log_analytics_storage_insights
        operator:  exists
        cond_type: connection
      - resource_types:
          - azurerm_log_analytics_storage_insights
        operator:  exists
        cond_type: attribute
        attribute: blob_container_names
      - resource_types:
          - azurerm_storage_container
        operator:  equals
        cond_type: attribute
        attribute: container_access_type
        value: "blob"
      - cond_type: filter
        attribute: resource_type
        value:
          - azurerm_storage_container
        operator: within
```

I like your proposal as it implements the check as described under https://docs.bridgecrew.io/docs/ensure-storage-logging-is-enabled-for-blob-service-for-read-requests#description
