### ISSUE TITLE
Skipping checks in Kubernetes are ignored?

### ISSUE THREAD

**Issue by MikeK184** [bridgecrewio/checkov#1329]
## Describe the bug
Declaring to skip policies in the job template does not take effect and logs still contain the to be skipped policies in output.

## Expected behavior
The specified policies to be skipped.
 
## Additional context
As example we would like to skip the CKV_K8S_38 in our Kubernetes Cluster, without having to add annotations to each individual resource and just let checkov know to skip this check in general. For this I've added the "args" section to the yaml file myself to pass down the additional arguments.
```
spec:
      securityContext:
        runAsUser: 12000
        runAsNonRoot: true
      restartPolicy: Never
      serviceAccountName: checkov-svc
      containers:
        - name: checkov
          image: bridgecrew/checkov-k8s:latest:2.0.140
          imagePullPolicy: IfNotPresent
          args:
            - "--skip-check"
            - "CKV_K8S_38"
```

Once checkov has finished, unfortunately the logs still contain the to be skipped policy:
![grafik](https://user-images.githubusercontent.com/56921065/123432958-3b9aa500-d5cb-11eb-9740-bcafd540c089.png)
