### ISSUE TITLE
Selecting AWS policies fields

### ISSUE THREAD

**Issue by vmorkunas** [bridgecrewio/checkov#1356]
Hello, 

I am trying to write a YAML custom check to check if the SQS policy has a "*" in resources block of policy:

```
data "aws_iam_policy_document" "sqs" {
  statement {
    effect = "Allow"
    actions = [
      "SQS:SendMessage"
    ]
    principals {
      type        = "AWS"
      identifiers = ["*"]
    }
    resources = [
      "*"
    ]
  }
}
```

Then i pass this policy to aws_sqs_queue_policy resource and run a check on it:

```
---
metadata:
  name: "Check sqs policy"
  id: "CKV2_AWS_2"
  category: "GENERAL_SECURITY"
scope:
  provider: AWS
definition:
  cond_type: "attribute"
  resource_types:
    - "aws_sqs_queue_policy"
  attribute: "policy.statement.resources"
  operator: "contains"
  value: "*"
```

But this doesn't work and it always matches even if I change value in the check. 

Could this case with policy reading be added to the docs?
