### ISSUE TITLE
Checkov Action permissions defect probably related to recent dockerfile changes

### ISSUE THREAD

**Issue by njgibbon** [bridgecrewio/checkov#1503]
**Describe the bug**
Hello,

Today the GitHub Action started showing a permissions issue. All working successfully until today. We are using the public github actions runners for this.

**Issue logs**
```
cp: can't create '/github/workspace/checkov-problem-matcher.json': Permission denied 
Error: Unable to process command '::add-matcher::checkov-problem-matcher.json' successfully. 
Error: Could not find file '/home/runner/work/<dir>/<dir>/checkov-problem-matcher.json'.
```

**Actions Config**
```
  checkov:
    runs-on: ubuntu-latest
    name: Checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/
          quiet: false
          soft_fail: false
          framework: terraform
          output_format: cli
```

Checkov does still run successfully and report results but this causes the action step to return a none zero exit code.

I've worked around very roughly by just shoving the json file into my root dir and moving on but just raising this issue to see if it is something which will affect others. I've not taken the time to replicate in other environments yet.

**EDIT**: I've just replicated the issue publicly here: https://github.com/njgibbon/test/actions

I think maybe there could be a good opportunity here for continuous testing of the action on goat or something like that.

It could be related to these changes: https://github.com/bridgecrewio/checkov/commit/ef302fbfe74732c5bdeb7c1d94c80fb9975089ad
https://github.com/bridgecrewio/checkov/commit/055815a146f4d8a907f5056a64d92c145fc5860c

And I suspect something to do with the permissions in the checkov container vs the github actions runner. Perhaps needs some trial and error to work out.
