### ISSUE TITLE
BC_AWS_PUBLIC_1 does not take Conditions into account

### ISSUE THREAD

**Issue by shotty1** [bridgecrewio/checkov#1582]
**Describe the bug**
BC_AWS_PUBLIC_1 seems to only look for the principal in a ECR Resource Policy. If you want to control access to a repo based on the pricipals AWS Organization ID, you have to do this using a condition instead of a Principal. It seems like checkov does not take this into account.

Example:

``` yaml
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepoName
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: OrgRead
            Effect: Allow
            Principal: "*"
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:GetRepositoryPolicy
              - ecr:DescribeRepositories
              - ecr:ListImages
              - ecr:DescribeImages
              - ecr:BatchGetImage
              - ecr:DescribeImageScanFindings
            Condition:
              ForAllValues:StringEquals:
                aws:PrincipalOrgID: "o-12345678"
```  

**To Reproduce**
Create the above mentioned resource in cloudformation and scan it with checkov

**Expected behavior**
I expect checkov to look for the usage of a PrincipalOrgID or similar global condition keys and not fail the check when they are used to make the repository non public.

**Desktop (please complete the following information):**
 - OS: macOS 11.5.2
 - Checkov Version 2.0.390
