### ISSUE TITLE
feat(operators): Add less_than, less_than_or_equals, greater_than, and greater_than_or_equals for graph

### ISSUE THREAD

**Issue by AjkayAlan** [bridgecrewio/checkov#1594]
## The Problem

We would like to write tests which can assert that numbers are less than our greater than a value. For example, given we have the following CloudFormation:

```json
{
  "Resources": {
    "Vpc8378EB38": {
      "Type": "AWS::EC2::VPC",
      "Properties": {
        "CidrBlock": "10.250.0.0/16"
      }
    },
    "Acl": {
      "Type": "AWS::EC2::NetworkAcl",
      "Properties": {
        "VpcId": {
          "Ref": "Vpc8378EB38"
        }
      }
    },
    "BadAclEntry": {
      "Type": "AWS::EC2::NetworkAclEntry",
      "Properties": {
        "NetworkAclId": {
          "Ref": "Acl"
        },
        "Egress": false,
        "PortRange": {
          "From": 21,
          "To": 23
        }
      }
    }
  }
}
```

We would like to write a rule that makes sure that the `PortRange` on `AWS::EC2::NetworkAclEntry` does not encompass port 22 for ingress. Right now, we have a rule like the following for ingress

```yaml
metadata:
  name: "vpc network acls should not allow public access to ssh"
  id: "CUSTOM_VPC_NETWORK_ACL_NO_SSH"
  category: "GENERAL_SECURITY"
definition:
  or:
    - cond_type: attribute
      resource_types:
        - AWS::EC2::NetworkAclEntry
      attribute: Egress
      operator: equals
      value: true
    - and:
      - cond_type: attribute
        resource_types:
          - AWS::EC2::NetworkAclEntry
        attribute: PortRange.From
        operator: not_equals
        value: 22
      - cond_type: attribute
        resource_types:
          - AWS::EC2::NetworkAclEntry
        attribute: PortRange.To
        operator: not_equals
        value: 22
```

This rule will pass, since From is 21, and To is 23.

## The Solution

Allow new operators of `greater_than`, `greater_than_or_equals`, `less_than`, and `less_than_or_equals`. This would allow me to write a policy similar to the following (in Pseudocode):

```
For AWS::EC2::NetworkAclEntry
OR
   If Egress equals true
   AND
      From < 22
      AND To < 22
   AND
      From > 22
      To > 22
```

## Alternatives

Right now this can be written using Python rules instead of the graph based YAML ones.

## Other

Thanks to @vangundy-jason-pfg for the research and example code/policy
