### ISSUE TITLE
Multiline output from github-action trimmed

### ISSUE THREAD

**Issue by raghavtan** [bridgecrewio/checkov#1648]
**Describe the bug**
Multiline CHECKOV_RESULTS fails. That is because the set-output notation only works on single line input

**To Reproduce**
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Policy Compliance Evaluation
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: compliance/configs/checkov.config.yaml
          directory: charts/checov-test

       - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.checkov.outputs.results }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10398915/134552364-68a9abdd-8e57-4bc7-8c17-5265350a2e0d.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Checkov Version : 2.0.437

**Additional context**
Expected output
```
|----|----------------------------------|-----------------|----------------------------------|----------------------------------------------|-------------|
|  0 | HelloFresh-PodDisruptionBudget-1 | /kube-test.yaml | PodDisruptionBudget.test.utility | PodDisruptionBudget should be greater than 1 |             |
```

fixes: #1644
