### ISSUE TITLE
CKV_K8S_31 failure with DockerDefault configured

### ISSUE THREAD

**Issue by nmarchini** [bridgecrewio/checkov#1740]
**Describe the bug**
CKV_K8S_31 failure when the seccompProfile type is configured as Docker/Default or Runtime/Default

**To Reproduce**
Define security context as below.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clust3rf8ck
  name: clust3rf8ck
  namespace: clust3rf8ck
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clust3rf8ck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clust3rf8ck
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "docker/default"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - clust3rf8ck
              topologyKey: "kubernetes.io/hostname"
      containers:
        - image: eurogig/clust3rf8ck@sha256:a374eb5853e0e17d06bcf37afc2fcb40892aa3477caf362ea3581c71373cb90a
          name: clust3rf8ck
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.6"
              memory: "100Mi"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "[ -f /var/run/nginx.pid ] && ps -A | grep nginx"
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - NET_RAW
          volumeMounts:
            - mountPath: /var/cache/nginx
              name: cache-volume
            - mountPath: /var/run
              name: pid-volume
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10014
        runAsGroup: 10014
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: pid-volume
          emptyDir: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: clust3rf8ck
  name: cflb
  namespace: clust3rf8ck
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: clust3rf8ck
  type: LoadBalancer
```
2. Run checkov for kubernetes.
```
checkov --framework=kubernetes --quiet -d .
```
**Expected behavior**
CKV_K8S_31 to pass with the following configuration.

```
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clust3rf8ck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clust3rf8ck
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "docker/default"
```

**Actual Behaviour**
```
[terraformpipeline] checkov --framework=kubernetes --quiet -d .                                                                               20:52:07  ☁  master ☂ ⚡
kubernetes scan results:

Passed checks: 89, Failed checks: 1, Skipped checks: 0

Check: CKV_K8S_31: "Ensure that the seccomp profile is set to docker/default or runtime/default"
	FAILED for resource: Deployment.clust3rf8ck.clust3rf8ck
	File: /k8s-sample.yaml:35-114
	Guide: https://docs.bridgecrew.io/docs/bc_k8s_29

		35  | apiVersion: apps/v1
		36  | kind: Deployment
		37  | metadata:
		38  |   labels:
		39  |     app: clust3rf8ck
		40  |   name: clust3rf8ck
		41  |   namespace: clust3rf8ck
		42  | spec:
		43  |   replicas: 2
		44  |   selector:
		45  |     matchLabels:
		46  |       app: clust3rf8ck
		47  |   strategy: {}
		48  |   template:
		49  |     metadata:
		50  |       creationTimestamp: null
		51  |       labels:
		52  |         app: clust3rf8ck
		53  |       annotations:
		54  |         seccomp.security.alpha.kubernetes.io/pod: "docker/default"
		55  |     spec:
		56  |       affinity:
		57  |         podAntiAffinity:
		58  |           requiredDuringSchedulingIgnoredDuringExecution:
		59  |             - labelSelector:
		60  |                 matchExpressions:
		61  |                   - key: app
		62  |                     operator: In
		63  |                     values:
		64  |                       - clust3rf8ck
		65  |               topologyKey: "kubernetes.io/hostname"
		66  |       containers:
		67  |         - image: eurogig/clust3rf8ck@sha256:a374eb5853e0e17d06bcf37afc2fcb40892aa3477caf362ea3581c71373cb90a
		68  |           name: clust3rf8ck
		69  |           imagePullPolicy: Always
		70  |           resources:
		71  |             limits:
		72  |               cpu: "1"
		73  |               memory: "200Mi"
		74  |             requests:
		75  |               cpu: "0.6"
		76  |               memory: "100Mi"
		77  |           livenessProbe:
		78  |             exec:
		79  |               command:
		80  |                 - /bin/sh
		81  |                 - -c
		82  |                 - "[ -f /var/run/nginx.pid ] && ps -A | grep nginx"
		83  |             initialDelaySeconds: 10
		84  |             periodSeconds: 5
		85  |           readinessProbe:
		86  |             httpGet:
		87  |               scheme: HTTP
		88  |               path: /index.html
		89  |               port: 8080
		90  |             initialDelaySeconds: 10
		91  |             periodSeconds: 5
		92  |           securityContext:
		93  |             readOnlyRootFilesystem: true
		94  |             allowPrivilegeEscalation: false
		95  |             capabilities:
		96  |               drop:
		97  |                 - ALL
		98  |                 - NET_RAW
		99  |           volumeMounts:
		100 |             - mountPath: /var/cache/nginx
		101 |               name: cache-volume
		102 |             - mountPath: /var/run
		103 |               name: pid-volume
		104 |       automountServiceAccountToken: false
		105 |       securityContext:
		106 |         runAsNonRoot: true
		107 |         runAsUser: 10014
		108 |         runAsGroup: 10014
		109 |       volumes:
		110 |         - name: cache-volume
		111 |           emptyDir: {}
		112 |         - name: pid-volume
		113 |           emptyDir: {}
		114 | status: {}
```

**Desktop (please complete the following information):**
 - OS: Big Sur 11.5.2 
 - Checkov Version 2.0.479

**Additional context**
Took the K8s example from this blog https://bridgecrew.io/blog/creating-a-secure-kubernetes-nginx-deployment-using-checkov/
