### ISSUE TITLE
Custom terraform checks fail to resolve `merge()` calls with `for_each` references

### ISSUE THREAD

**Issue by brnsmns13** [bridgecrewio/checkov#1940]
**Describe the bug**
Custom terraform checks fail to resolve `merge()` calls with `for_each` references.

**To Reproduce**
1. In an empty directory, create the following files.

`check.yml`
```yaml
---
metadata:
  name: "Show `for_each` tag merge resolution fails"
  id: "tag_merge"
definition:
  cond_type: "attribute"
  resource_types:
    - "aws_lambda_function"
  attribute: "tags.Name"
  operator: "equals"
  value: "MyLambda"
```

`for_each_merge_example.tf`
```terraform
locals {
  tags = {
    App = "MyApp"
  }
  lambdas = {
    MyLambda = {
      Name = "MyLambda"
    }
  }
}

resource "aws_lambda_function" "my_lambda_success" {
  tags = merge(local.tags, {Name = "MyLambda"})
}

resource "aws_lambda_function" "my_lambda_failure" {
  for_each = local.lambdas

  function_name = each.value.Name
  tags = merge(local.tags, {Name = each.value.Name})
}
```

2. In the same directory, run the following cli command to validate the custom check against the provided example.
    `checkov --external-checks-dir . -c tag_merge -d .`

**Expected behavior**
As defined by the check, the expectation is that the tag `Name` will have the value of `MyLambda`. The lambda resource `my_lamdba_success` in the example works as expected and the `Name` tag is merged and resolved properly. However, when the value of a merge argument contains a reference to an `each.*` variable as defined by the `for_each` loop, the value is not populated as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/5491926/141824536-41990fda-1bbc-40db-8362-56c6de7e5415.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Checkov Version: 2.0.573 (latest at time of issue)
