### ISSUE TITLE
Support to define global and local checks/skip-checks

### ISSUE THREAD

**Issue by hugomcfonseca** [bridgecrewio/checkov#2201]
**Describe the issue**

In my repository, I have a complex IaC with multiple stacks from different projects, and I implemented GitOps using Atlantis w/ checkov using `terraform-plan` framework to run static analysis on pull-requests.
In order to ease management of checkov configurations, I would like to want to define global configurations that would affect all tfstate and, optionally, that can be overridden locally per tfstate.

However, when trying to use options `--config-file` with declared `skip-check` along with `--skip-check`, this ends with no skip-checks defined.

Is this intended by design or can this be considered a feature to be implemented?

A possible solution is to have another configs such `--default-skip-check` or `--default-check` that can be used in a global configuration file for checkov.

**Examples**

As an expectation, I would like to run checkov with a similar command such:

```sh
$ checkov --config-file $CHECKOV_CONFIG/global-config.yml --config-file local-config.yml --compact --quiet -f tfplan.json

# or, for a specific use case, if I want to add extra skip-checks to the ones defined in $CHECKOV_CONFIG/global-config.yml
$ checkov --config-file $CHECKOV_CONFIG/global-config.yml --skip-check CKV_AWS_91 --compact --quiet -f tfplan.json
```

For the sake of context, this is my `$CHECKOV_CONFIG/global-config.yml`:

```yml
framework:
  - terraform_plan
skip-check:
  - CKV_AWS_18
  - CKV_AWS_37
  - CKV_AWS_79
  - CKV_AWS_86
  - CKV_AWS_91
  - CKV_AWS_118
  - CKV_AWS_129
  - CKV_AWS_130
  - CKV_AWS_144
```

**Version (please complete the following information):**
 - 2.0.705
