### ISSUE TITLE
CKV_K8S_31 false positive for CronJob with new "type: RuntimeDefault"

### ISSUE THREAD

**Issue by neiser** [bridgecrewio/checkov#2222]
**Describe the issue**
When using the following Kubernetes yaml:
```
apiVersion: batch/v1
kind: CronJob
...
spec:
  ...
  jobTemplate:
    spec:
      template:
        ...
        spec:
          securityContext:
            ...
            seccompProfile:
              type: RuntimeDefault
          containers:
              ...
            - securityContext:
                ...
                seccompProfile:
                  type: RuntimeDefault
```
I expect the check CKV_K8S_31 to pass, but it doesn't. 

The issue #710 and subsequent PR #719 fixed it for `Deployment`, but I think it should work with `CronJob`, too! Telling from the code, that fix apparantly wasn't enough: https://github.com/bridgecrewio/checkov/blob/master/checkov/kubernetes/checks/resource/k8s/Seccomp.py#L38
as it appears is only checks for the annotation, not for the new property `securityContext.type`

**Version (please complete the following information):**
 - Checkov Version: 2.0.709
