### ISSUE TITLE
Cannot check that all children of an entity meet a condition

### ISSUE THREAD

**Issue by Efrat-Gordon** [bridgecrewio/checkov#2435]
I want to check that all the children of an entity meet a condition e.g cidr_block attribute in all routes of a route table don't equal to "0.0.0.0/0".
I wrote the following block in my check:
```
 - cond_type: "attribute"
    resource_types:
       - "aws_route_table"
    attribute: "route.*.cidr_block"
    operator: "not_contains"
    value: "0.0.0.0/0"
```
I expect that if there I at least one route that doesn't stand in the condition the fail should fail, but the fail passes if there is at least one valid route.

This behavior is reproduced also in existing Checkov checks:
Check CKV2_AWS_7 checks that Amazon EMR clusters' security groups are not open to the world, which means that if there is an ingress that is open to the world, the check should fail even though there are other valid ingresses.
Actual behavior: The check passes when there is at least one valid ingress.

**Example:**
The check:
```
name: "Ensure SG is not totally exposed to the internet"
metadata:
  id: "CKV2_AWS_7"
  name: "Ensure that Amazon EMR clusters' security groups are not open to the world"
  category: "NETWORKING"
definition:
  and:
    - cond_type: "attribute"
      resource_types: 
        - "aws_security_group"
      attribute: "ingress.*.cidr_blocks"
      operator: "not_contains"
      value: "0.0.0.0/0"
```

The Terraform file content:
```
resource "aws_security_group" "exposed_SG" {
  description = "Allow inbound traffic to ElasticSearch from VPC CIDR"
  ingress {
    description = "TLS from VPC"
    cidr_blocks = "0.0.0.0/0"
    from_port = 0
    to_port = 0
    protocol = "-1"
  }
   ingress {
    description = "TLS from VPC"
    cidr_blocks = "0.0.0.1/0"
    from_port = 0
    to_port = 0
    protocol = "-1"
  }
}

```
Expected: The check should fail.
Actual: The check passes.

 - Checkov Version 2.0.780
