### ISSUE TITLE
Terraform custom module count not evaluated correctly 

### ISSUE THREAD

**Issue by SolLepel** [bridgecrewio/checkov#2475]
I am in the process of creating custom policies to check on resources created by a custom module creating aws Secrets Manager resources.  The module has a uses count to determine if it needs to create a `aws_secretsmanager_secret_rotation` resource
When running a custom check to see if the resources created by the module have a connection with the `aws_secretsmanager_secret_rotation` resource passes the check, while it should fail since the count = 0 so no  `aws_secretsmanager_secret_rotation` resource is created. I assume that if the checkov scan would be done on a tf plan out it will be check correctly since no resource would show up there.

I created the following check:
```
metadata:
 name: "Check that Secret has lambda rotation enabled"
 id: "CKV2_AWS_99"
 category: "SECRETS"
definition:
 and:
      - cond_type: "filter"
        attribute: "resource_type"
        value:
           - "aws_secretsmanager_secret"
        operator: "within"
      - cond_type: "connection"
        resource_types:
           - "aws_secretsmanager_secret"
        connected_resource_types:
         - "aws_secretsmanager_secret_rotation"
        operator: "exists"
```

**Examples**

Example ./modules/secrets_manager module contents:
```
resource "aws_secretsmanager_secret" "default" {
  name                    = var.name
  description             = var.description
  recovery_window_in_days = var.recovery_window_in_days
  kms_key_id              = var.kms_key_id
  tags                    = var.tags
}
resource "aws_secretsmanager_secret_rotation" "default" {
  count = var.rotation_enabled ? 1 : 0
  secret_id           = aws_secretsmanager_secret.default.id
  rotation_lambda_arn = var.secret_rotation_lambda_arn
  rotation_rules {
    automatically_after_days = 30
  }
  tags = var.tags
}
```

main.tf

```
module "example_secretsmanager" {
  source = "../modules/secrets_manager"

  name                    = "example-secrets-manager-secret"
  description             = "Description of an example secrets manager secret"
  recovery_window_in_days = 14
  rotation_enabled = false
   tags                    = {
    owner = "example"
  }
}
...
resource "aws_secretsmanager_secret" "default_tst" {
  name                    = "var.name"
  description             = "var.description"
  recovery_window_in_days = 30
  kms_key_id              = var.kms_key_id
  tags                    = var.tags
}
```

**Results:**
Expected: The check should fail.
Actual: The check passes.

The check works fine when scanning a terraform file containing just a `aws_secretsmanager_secret` resource and no associated `aws_secretsmanager_secret_rotation` resource, which succesfully evalutes that it shouldnt pass.

However when using the module which has a count condition for creating the associated `aws_secretsmanager_secret_rotation` resource the check passes incorrectly.

When commenting out the rotation resource and rerunning checkov it correctly fails the check.
First check passes for secret manager resource created through module, which has  `rotation_enabled = false`, the second check results from a single basic `aws_secretsmanager_secret` with no related  `aws_secretsmanager_secret_rotation` resource.

```
Check: CKV2_AWS_99: "Check that aws_secretsmanager_secret has lambda rotation enabled"
        PASSED for resource: aws_secretsmanager_secret.default
        File: /../modules/secrets_manager/main.tf:1-7

Check: CKV2_AWS_99: "Check that aws_secretsmanager_secret has lambda rotation enabled"
        FAILED for resource: aws_secretsmanager_secret.default_tst
        File: /main.tf:64-70

                64 | resource "aws_secretsmanager_secret" "default_tst" {
                65 |   name                    = "var.name"
                66 |   description             = "var.description"
                67 |   recovery_window_in_days = 30
                68 |   kms_key_id              = var.kms_key_id
                69 |   tags                    = var.tags
                70 | }
``` 

**Version:**
 - Checkov Version  2.0.861
