### ISSUE TITLE
Unable to check Terraform resources dependencies created with a for_each loop

### ISSUE THREAD

**Issue by xdavietpro** [bridgecrewio/checkov#2591]
Hello

### My goal
Checking that any Azure subnet is protected with a custom security group 

### Terraform code
```tf
resource "azurerm_subnet" "snet" {
  for_each = local.subnets
   ... 
}

resource "azurerm_network_security_group" "nsg" {
  for_each = local.subnets
  ...
}

resource "azurerm_subnet_network_security_group_association" "nsgass" {
  for_each = local.subnets

  subnet_id                 = azurerm_subnet.snet["${each.key}"].id
  network_security_group_id = azurerm_network_security_group.nsg["${each.key}"].id
}
```

### Additional info
Terraform `local.subnets` variable is a dictionnary containing something like this
```tf
{
  0 : "a.b.c.0/25"
  1 : "a.b.c.128/25"
}
```

### Checkov custom policy definition
```yml
definition:
 and:
  - cond_type: "filter"
    attribute: "resource_type"
    value:
      - "azurerm_subnet"
    operator: "within"
  - cond_type: "connection"
    resource_types:
      - "azurerm_subnet"
    connected_resource_types:
      - "azurerm_subnet_network_security_group_association"
    operator: "exists"
```

### Checkov error message
`FAILED for resource: azurerm_subnet.snet`

Checkov version : 2.0.929
