### ISSUE TITLE
Check ECS tasks don't use the same IAM role for task_role_arn and execution_role_arn

### ISSUE THREAD

**Issue by danielcompton** [bridgecrewio/checkov#2602]
**Describe the issue**

I'm wanting to add a check for ECS tasks to prevent using the same role as the `execution_role_arn` and the `task_role_arn`.

Using the YAML based definition, there doesn't seem to be a way to compare two attributes on the same resource as being equal or unequal. Am I missing something?

**Examples**

```yaml
---
metadata:
 name: "ECS tasks should use different roles for task_role and execution_role"
 id: "CKV2_AWS_9999"
 category: "IAM"
scope:
 provider: aws
definition:
  cond_type: "attribute"
  resource_types:
    - "aws_ecs_task_definition"
  attribute: "task_role_arn"
  operator: "equals"
  value: "0" # ??? here's where I want to compare to execution_role_arn
```

**Version (please complete the following information):**
 - Checkov Version: 2.0.915

**Additional context**
