### ISSUE TITLE
Add check for waf required on AWS appsync

### ISSUE THREAD

**Issue by sbe-arg** [bridgecrewio/checkov#2623]
**Describe the issue**
Similarly to CKV_AWS_68 add support for appsync check for WAF as required for cloudformation based resources.

**Examples**
n/a

**Version (please complete the following information):**
latest

**Additional context**
n/a

**Comment by MooreDerek** [comment]
@sbe-arg This check already exists see CKV2_AWS_33 - Ensure AppSync is protected by WAF

**Comment by sbe-arg** [comment]
> @sbe-arg This check already exists see CKV2_AWS_33 - Ensure AppSync is protected by WAF

I think it might be only available for terraform. Can't find one for cloudformation/serverless/cdk

**Comment by MooreDerek** [comment]
@sbe-arg I've had a look at how this could be implemented. The terraform code is looking for a WebACLAssociation for the AppSync::GraphQLApi , however there is no way to prove the relationship in the CloudFormation - that I can see.  Below is a working example of CFN to create an AppSync API protected by a WAF. 
@gruebel I'd be interested if you have any ideas on approaches for this ...
```
AWSTemplateFormatVersion: "2010-09-09"
Description: "AppSync-WAF-Enabled"
Resources:
    AppSyncGraphQLApi:
        Type: "AWS::AppSync::GraphQLApi"
        Properties:
            Name: "My Checkov Test App"
            AuthenticationType: "API_KEY"
            XrayEnabled: false

    WAFv2WebACL:
        Type: "AWS::WAFv2::WebACL"
        Properties:
            Name: "Checkov-ACL"
            Description: "Checkov-ACL"
            DefaultAction: 
                Block: {}
            VisibilityConfig: 
                SampledRequestsEnabled: true
                CloudWatchMetricsEnabled: true
                MetricName: "Checkov-ACL"
            Scope: "REGIONAL"
    WebACLAssociation:
      Type: AWS::WAFv2::WebACLAssociation
      Properties:
        ResourceArn: !GetAtt AppSyncGraphQLApi.Arn
        WebACLArn: !GetAtt WAFv2WebACL.Arn
```

**Comment by gruebel** [comment]
@MooreDerek yeah it is actually possible to do for CloudFormation too 🙂 
```yaml
metadata:
  id: "CKV2_AWS_33"
  name: "Ensure AppSync is protected by WAF"
  category: "APPLICATION_SECURITY"
definition:
  and:
    - cond_type: filter
      value:
        - AWS::AppSync::GraphQLApi
      operator: within
      attribute: resource_type
    - cond_type: connection
      operator: exists
      resource_types:
       - AWS::AppSync::GraphQLApi
      connected_resource_types:
       - AWS::WAFv2::WebACLAssociation
```
I think that's the whole check, very similar to the Terraform one. It needs to be added here https://github.com/bridgecrewio/checkov/tree/master/checkov/cloudformation/checks/graph_checks and of course tests need to be added 😄
