### ISSUE TITLE
kubernetes: all checks skipped for manifests including a multi-line annotation

### ISSUE THREAD

**Issue by Poweranimal** [bridgecrewio/checkov#2660]
**Describe the issue**
Checking a `kubernetes` manifest that contains a multi-line annotation causes `checkov` to skip all checks for the affected file and returning error code `0`.

**Examples**
The annotation in question can be found at `line 30` -> `/spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-template-serverca.crt`.

<details>
<summary>Manifest with multi-line annotation (all checks skipped)</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consul
    chart: consul-helm
    component: controller
    golane/chart: consulgroup-chart
    heritage: Helm
    release: consul
  name: consul-controller
  namespace: consul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consul
      chart: consul-helm
      component: controller
      heritage: Helm
      release: consul
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "false"
        vault.hashicorp.com/agent-extra-secret: vault-server-tls
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-serverca.crt: pki/cert/ca
        vault.hashicorp.com/agent-inject-template-serverca.crt: |
          {{- with secret "pki/cert/ca" -}}
          {{- .Data.certificate -}}
          {{- end -}}
        vault.hashicorp.com/ca-cert: /vault/custom/ca.crt
        vault.hashicorp.com/role: consul-ca
      labels:
        app: consul
        chart: consul-helm
        component: controller
        heritage: Helm
        release: consul
    spec:
      containers:
        - command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane controller \
                -log-level=info \
                -log-json=false \
                -webhook-tls-cert-dir=/tmp/controller-webhook/certs \
                -datacenter=dc1 \
                -enable-leader-election \
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: consul-controller-acl-token
            - name: CONSUL_CACERT
              value: /consul/tls/ca/tls.crt
            - name: CONSUL_HTTP_ADDR
              value: https://$(HOST_IP):8501
          image: hashicorp/consul-k8s-control-plane:0.41.1
          name: controller
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
            - mountPath: /tmp/controller-webhook/certs
              name: cert
              readOnly: true
            - mountPath: /consul/tls/ca
              name: consul-auto-encrypt-ca-cert
              readOnly: true
      initContainers:
        - command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane acl-init \
                -secret-name="consul-controller-acl-token" \
                -k8s-namespace=consul
          image: hashicorp/consul-k8s-control-plane:0.41.1
          name: controller-acl-init
          resources:
            limits:
              cpu: 50m
              memory: 25Mi
            requests:
              cpu: 50m
              memory: 25Mi
        - command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane get-consul-client-ca \
                -output-file=/consul/tls/client/ca/tls.crt \
                -server-addr=consul-server \
                -server-port=8501 \
                -ca-file=/vault/secrets/serverca.crt
          image: hashicorp/consul-k8s-control-plane:0.41.1
          name: get-auto-encrypt-client-ca
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - mountPath: /consul/tls/client/ca
              name: consul-auto-encrypt-ca-cert
      serviceAccountName: consul-controller
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: consul-controller-webhook-cert
        - name: consul-ca-cert
          secret:
            items:
              - key: tls.crt
                path: tls.crt
            secretName: pki/cert/ca
        - emptyDir:
            medium: Memory
          name: consul-auto-encrypt-ca-cert
```
</details>

<details>
<summary>Manifest without multi-line annotation (= normal behavior of checkov)</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consul
    chart: consul-helm
    component: controller
    golane/chart: consulgroup-chart
    heritage: Helm
    release: consul
  name: consul-controller
  namespace: consul
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consul
      chart: consul-helm
      component: controller
      heritage: Helm
      release: consul
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "false"
        vault.hashicorp.com/agent-extra-secret: vault-server-tls
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-serverca.crt: pki/cert/ca
        vault.hashicorp.com/ca-cert: /vault/custom/ca.crt
        vault.hashicorp.com/role: consul-ca
      labels:
        app: consul
        chart: consul-helm
        component: controller
        heritage: Helm
        release: consul
    spec:
      containers:
        - command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane controller \
                -log-level=info \
                -log-json=false \
                -webhook-tls-cert-dir=/tmp/controller-webhook/certs \
                -datacenter=dc1 \
                -enable-leader-election \
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: consul-controller-acl-token
            - name: CONSUL_CACERT
              value: /consul/tls/ca/tls.crt
            - name: CONSUL_HTTP_ADDR
              value: https://$(HOST_IP):8501
          image: hashicorp/consul-k8s-control-plane:0.41.1
          name: controller
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
          volumeMounts:
            - mountPath: /tmp/controller-webhook/certs
              name: cert
              readOnly: true
            - mountPath: /consul/tls/ca
              name: consul-auto-encrypt-ca-cert
              readOnly: true
      initContainers:
        - command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane acl-init \
                -secret-name="consul-controller-acl-token" \
                -k8s-namespace=consul
          image: hashicorp/consul-k8s-control-plane:0.41.1
          name: controller-acl-init
          resources:
            limits:
              cpu: 50m
              memory: 25Mi
            requests:
              cpu: 50m
              memory: 25Mi
        - command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane get-consul-client-ca \
                -output-file=/consul/tls/client/ca/tls.crt \
                -server-addr=consul-server \
                -server-port=8501 \
                -ca-file=/vault/secrets/serverca.crt
          image: hashicorp/consul-k8s-control-plane:0.41.1
          name: get-auto-encrypt-client-ca
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - mountPath: /consul/tls/client/ca
              name: consul-auto-encrypt-ca-cert
      serviceAccountName: consul-controller
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: consul-controller-webhook-cert
        - name: consul-ca-cert
          secret:
            items:
              - key: tls.crt
                path: tls.crt
            secretName: pki/cert/ca
        - emptyDir:
            medium: Memory
          name: consul-auto-encrypt-ca-cert
```
</details>
**Version (please complete the following information):**
 - Checkov Version `2.0.978`
