### ISSUE TITLE
Kubernetes checks pass on manifest with curly brackets

### ISSUE THREAD

**Issue by tom1299** [bridgecrewio/checkov#2739]
**Kubernetes checks pass on manifest with curly brackets**
When running the kubernetes checks against a manifest that contains double curly brackets `{{`, checkovs return value is `0` despite other manifests failing.

**Examples**
The following example based on [this test case](https://github.com/bridgecrewio/checkov/blob/10fd473f0e6840cb1e49919185a8120fbe0f41c9/tests/kubernetes/checks/example_AllowPrivilegeEscalation/nginx-app-FAILED.json) contains an additional config map with a data key containing `{{` (see last line):
```yaml
---
kind: Pod
apiVersion: v1
metadata:
  name: my-nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: http
      containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  game.properties: |
    {{ pass }}

```
running checkov with the kubernetes framework returns return code `0`:
```
# checkov --framework kubernetes --compact -f nginx-app-FAILED.yml  

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.1021 


# echo $?
0
```
despite the fact that the checks for the nginx Pod should fail. Removing the `{{` creates the expected result (nginx Pod failing):
```yaml
---
kind: Pod
apiVersion: v1
metadata:
  name: my-nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - name: http
      containerPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  game.properties: |
    pass }}

```
```
# checkov --framework kubernetes --compact -f nginx-app-FAILED.yml
       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.1021 

kubernetes scan results:

Passed checks: 71, Failed checks: 19, Skipped checks: 0
...
# echo $?
1
```
Please not that I truncated the output for reasons of brevity.
The expected outcome would be that the nginx manifest should fail in both runs.

**Version (please complete the following information):**
 - Checkov Version 2.0.1021

**Additional context**
Note that [kubeval](https://kubeval.instrumenta.dev) validation succeeds for both cases, verifying that both yamls are vaild kubernetes manifests.
