### ISSUE TITLE
CKV_K8S_22 Does not Check If the Deployment Manifest Contains a Valid Boolean

### ISSUE THREAD

**Issue by SachithKasthuriarachchi** [bridgecrewio/checkov#2775]
**Describe the issue**
Check ID: CKV_K8S_22

This check passes even if the `readOnlyRootFileSystem` contains an invalid non-boolean value.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      key: value
  replicas: 1
  template:
    metadata:
      labels:
        key: value
    spec:
      containers:
      - name: my-container
        image: nginx
        securityContext:
          readOnlyRootFilesystem: ture
```

Please note that the `readOnlyRootFilesystem` contains an invalid non-bool value (`ture` not `true`). The expected outcome should be the failure of check. However, the test has been passed.

**Version (please complete the following information):**
 - Checkov Version: 2.0.1037
