### ISSUE TITLE
Arrays of numbers do not appear to be processed as expected

### ISSUE THREAD

**Issue by mwelch-m** [bridgecrewio/checkov#2796]
This issue description will be based off the following Terraform:
```
resource "google_compute_firewall" "should_pass_01" {
  name    = "test-firewall2"
  network = "network_name"

  allow {
    protocol = "tcp"
    ports = ["21"]
  }
}

resource "google_compute_firewall" "should_pass_02" {
  name    = "test-firewall2"
  network = "network_name"

  allow {
    protocol = "tcp"
    ports = ["21", "443"]
  }
}
```
And this policy:
```
---
metadata:
  id: 'custom_policy_id_000356'
  name: 'Firewall restricts traffic on SSH port (22)'
  guidelines: 'Do not use e2-micro instance type'
  category: 'networking'
  severity: 'critical'
scope:
  provider: 'gcp'
definition:
  cond_type: 'attribute'
  resource_types:
    - 'google_compute_firewall'
  attribute: 'allow.ports'
  operator: 'not_contains'
  value: '22'
```
**Describe the issue**
Both resources above should pass. This first is neither passed, failed, or skipped. It errors out and is silently ignored.  I debugged the code to some level and by the time the actual comparison is done in the `common/checks_infra/solvers/attribute_solvers/contains_attribute_solver.py`, the resource value of `['21']` has not only been converted to s standalone value of `'21'` but also a numeric value of `21`. The comparison for the contains/not_contains operator uses the python `in` and thus the ultimate comparison made is `'22' in 21` which throws an exception since an int isn't iterable. 

It would also be incorrect for the comparison to be `'22' in '21'` as (I think) that would iterate over the characters in the string. The correct comparison, and the one that occurs where there's more that one value in the resource array, would seem to be the one that's expected by the way the policy and resources is written; i.e. `'22' in ['21']`. 

When the comparison is made on the second resource, it works as expected: `'21' in ['21', '443']`. 

Yes, I know that there is a python check that already performs this exact port check, but I'm making the point with an example. 

**Examples**
Provided above. 

**Version (please complete the following information):**
 - Checkov Version:  2.0.1050
