### ISSUE TITLE
Guidelines not displayed when check fails 

### ISSUE THREAD

**Issue by SiSiHenry** [bridgecrewio/checkov#2826]
I am crafting some custom rules and am unable to get the guidelines section to print out when the rule fails. 
When I run the out-of-the box rules, guidelines prints.  How do I get my custom rules to generate the guideline so that my users can access url? 

```
metadata:
  name: "Ensure instance profile is configured - https://test.example.com/EC2/MK_AWS_EC2_2.md?at=refs%2Fheads%2Fdevelop"
  guidelines: "https://test.example.com/EC2/MK_AWS_EC2_2.md?at=refs%2Fheads%2Fdevelop"
  id: "CKV_AWS_TF_EC2_2"
  category: "IAM"
  severity: "TBD"
scope:
provider: "aws"
definition:
            cond_type: "attribute"
            resource_types:
              - "aws_instance"
            attribute: "iam_instance_profile"
            operator: "exists"
```

**Version (please complete the following information):**
 - Checkov Version [2.0.1065]
