### ISSUE TITLE
Usage of --external-checks-dir, custom checks do not get recognised

### ISSUE THREAD

**Issue by antoniorodriguezmoreno** [bridgecrewio/checkov#2863]
**Describe the bug:**
I created a basic yaml custom rules and I plan to create several new rules. 
Currently I don't get why the custom rules does not get asserted as it should be. 

My custom rule `checkov-checks/chekov_custom_rule_tagging.yaml` looks like that:
```yaml
---
metadata:
 name: "Check that all resources are tagged with the key - InfoSecClass"
 id: "CKV_AWS_123"
 category: "GENERAL_SECURITY"
scope:
 provider: aws
definition:
       cond_type: "attribute"
       resource_types: "AWS::EC2::SecurityGroup"
       attribute: "tags.infosecclass"
       operator: "exists"
```

And I run it via `checkov -f src/test/rds-cf-template.json --external-checks-dir ./checkov-checks`

Is there something I am doing wrong or is the rule malformed/incorrect? 

Currently I am using the Version 2.0.1079

**Comment by tsmithv11** [comment]
This is a case where a Python check is likely better, but here are both options:

```python
from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.cloudformation.checks.resource.base_resource_value_check import BaseResourceCheck

class BagTagging(BaseResourceCheck):
    def __init__(self):
        name = "Check that all resources are tagged with the key - InfoSecClass"
        id = "CKV_AWS_999"
        supported_resources = ['AWS::EC2::SecurityGroup']
        categories = (CheckCategories.GENERAL_SECURITY)
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf):
        if 'Properties' in conf.keys():
            if 'Tags' in conf['Properties'].keys():
                for tag in conf['Properties']['Tags']:
                    if tag['Key'] == 'infosecclass':
                        return CheckResult.PASSED
        return CheckResult.FAILED

check = BagTagging()
```

or in YAML:

```yaml
---
metadata:
 name: "Check that all resources are tagged with the key - InfoSecClass"
 id: "CKV_AWS_999"
 category: "GENERAL_SECURITY"
scope:
 provider: aws
definition:
       cond_type: "attribute"
       resource_types: "AWS::EC2::SecurityGroup"
       attribute: Tags.*.Key
       operator: "equals"
       value: "infosecclass"
```

**Comment by antoniorodriguezmoreno** [comment]
Thank you for providing those templates! Unfortunately those rules also do not get recognised, when I run the command `checkov -f src/test/rds-cf-template.json --external-checks-dir ./checkov-checks`.
Is there some flag I need to set to use the custom rules or something in my env?

**Comment by tsmithv11** [comment]
@antoniorodriguezmoreno can you provide an anonymized example of a file you would expect to pass the check?

**Comment by antoniorodriguezmoreno** [comment]
I tried it multiple files for example:
```yml
secGroupName:
  Type: AWS::EC2::SecurityGroup
  Properties:
    GroupName: Test_sg
    GroupDescription: Test SG
    Tags:
      - Key: infosecclass
        Value: open
```
and

```terraform
resource "aws_security_group" "sg_test" {
  name   = "sg_test"

  tags = {
    "infosecclass" = "Open"
  }
}
```

**Comment by tsmithv11** [comment]
For the first one, it needs to be in a resource block:

```yaml
Resources:
  secGroupName:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Test_sg
      GroupDescription: Test SG
      Tags:
        - Key: infosecclass
          Value: open
```

For the second, you'll need a TF specific policy and it will run.

**Comment by antoniorodriguezmoreno** [comment]
Thank you for the help @tsmithv11 !
I was able to run it successfully.

**Comment by nijdarshan** [comment]
Hi, 

I am facing the same problem with my custom checks while trying to run in a pipeline. But, it works absolutely well when works scanned locally.

### **My sample check in python looks like below:**

```
from typing import Dict, Any

from checkov.common.models.enums import CheckResult
from checkov.kubernetes.checks.resource.base_container_check import BaseK8sContainerCheck


class ApiServerAuditLog(BaseK8sContainerCheck):
    def __init__(self) -> None:
        id = "CKV_K8S_999"
        name = "Ensure that the --audit-log-path argument is set"
        super().__init__(name=name, id=id)

    def scan_container_conf(self, metadata: Dict[str, Any], conf: Dict[str, Any]) -> CheckResult:
        self.evaluated_container_keys = ["command"]
        if conf.get("command") is not None:
            if "kube-apiserver" in conf["command"]:
                hasAuditLog = False
                for command in conf["command"]:
                    if command.startswith("--audit-log-path"):
                        hasAuditLog = True
                return CheckResult.PASSED if hasAuditLog else CheckResult.FAILED

        return CheckResult.PASSED


check = ApiServerAuditLog()
```

### **.gitlab-ci.yml looks like below:**

```
stages:
    - test
    
checkov:
  stage: test
  allow_failure: true  # True for AutoDevOps compatibility
  image:
    name: bridgecrew/checkov
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - '**/*.yml'
        - '**/*.yaml'
        - '**/*.json'
        - '**/*.template'
        - '**/*.tf'      
        - '**/serverless.yml'
        - '**/serverless.yaml'
  script:
      - checkov -d ./ --external-checks-dir ./ --check CKV_K8S_999 
```

### **My GitLab repo structure:** 

![image](https://user-images.githubusercontent.com/51939272/188482284-eaff811f-15aa-4dfa-8292-dfba95f20689.png)

Can someone please help? Thanks!
