### ISSUE TITLE
Ability to write a check based on whether resource is coming from external module or directly defined

### ISSUE THREAD

**Issue by meghaddn** [bridgecrewio/checkov#2874]
Is it possible to make a determination in checks whether the resource is directly defined or is coming from an external module.
We want to be able to fail check if approved module is not being used.

Thanks!

**Comment by rotemavni** [comment]
Hello @meghaddn , thanks for your question.
There is a way to query the file path, and we can tell whether the resource is originated in an external module.
When defining a YAML query we can add an attribute query for the `file_path_` attribute.
If you are using the default checkov settings, all external modules are stored under the `.external_modules` directory, so this query will help exclude resources from external modules.

```
    - cond_type: "attribute"
      resource_types: 
        - "aws_security_group"
      attribute: "file_path_"
      operator: "not_contains"
      value: ".external_modules"
```
