### ISSUE TITLE
Regex failing for custom YAML check - how does `!Sub` get parsed from CF?

### ISSUE THREAD

**Issue by shearn89** [bridgecrewio/checkov#2909]
**Describe the issue**
I'm trying to write a custom check to verify some internal policies. As an example, we have some naming conventions that include prepending IAM roles with 'local-'.

I have written a custom check for my CF template, but the only way I can get it to match my resource name is by sticking `.*` at the start. I'm using the `Sub` intrinsic function, and the Checkov documentation is a little lacking in showing how that is handled!

Why is this failing?

**Examples**
My CFN:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  customRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "local-${AWS::StackName}-foobar"
```

My check in `checks/name.yaml`:

```yaml
---
metadata:
  name: "name check"
  id: "custom_01"
  category: "custom"
scope:
  provider: AWS
definition:
  cond_type: "attribute"
  resource_types:
    - "AWS::IAM::Role"
  attribute: "RoleName"
  operator: "regex_match"
  value: "!Sub \"local.*"
```

My command:

```bash
$ checkov --quiet -f template.yaml --external-checks-dir checks --skip-download
cloudformation scan results:

Passed checks: 6, Failed checks: 1, Skipped checks: 0

Check: custom_01: "name check"
	FAILED for resource: AWS::IAM::Role.customRole
	File: /template.yaml:3-6

		3 |   customRole:
		4 |     Type: AWS::IAM::Role
		5 |     Properties:
		6 |       RoleName: !Sub "local-${AWS::StackName}-foobar"

```

If I change the value to `.*local.*`:

```bash
checkov --quiet -f template.yaml --external-checks-dir checks --skip-download
cloudformation scan results:

Passed checks: 7, Failed checks: 0, Skipped checks: 0
```

**Version (please complete the following information):**
 - Checkov Version 2.0.1108

**Additional context**

Other patterns I've tried:

- `.*\"local.*` - ⛔ 
- `local.*` - ⛔ 
- `!Sub.*local.*` - ⛔ 
- `.*!Sub.*local.*` - ⛔ 
- `.*\\!Sub.*local.*` - ⛔

**Comment by Saarett** [comment]
Hey @shearn89 , and thanks for reaching us out!

You are right, I would expect this regex to work too. The reason this check fails is because at the time of the check, `RoleName` ’s value is actually `{\'Fn::Sub\': \'local-${AWS::StackName}-foobar\'}` .
3 reasons behind it:

1. checkov uses `cfn_lint` as the parser for CFN files, and it parses `!Sub` into `Fn::Sub`
2. checkov stores `RoleName` ’s value as the dict `{'Fn::Sub': 'local-${AWS::StackName}-foobar'}` so just before it runs the regex match function, it stringifies this object into the value I’ve stated earlier
3. checkov doesn’t parse this CFN Sub function because it can’t parse the Pseudo Parameter `AWS::StackName` as its value is unknown before the deployment (and we should detail it in the documentation :slightly_smiling_face: )

**Comment by shearn89** [comment]
Aha! Okay! Yep - when I update the check to be:

```
---
metadata:
  name: "name check"
  id: "custom_01"
  category: "custom"
scope:
  provider: AWS
definition:
  cond_type: "attribute"
  resource_types:
    - "AWS::IAM::Role"
  attribute: "RoleName"
  operator: "regex_match"
  value: "{'Fn::Sub': 'local-.*"
```

It works fine! Thanks!
