### ISSUE TITLE
File scanning not possible with Github-Actions

### ISSUE THREAD

**Issue by roymartinezblanco** [bridgecrewio/checkov#3042]
**Describe the issue**
I've been trying to use checkov's integration with Github actions (bridgecrewio/checkov-action) to scan our terraform plan file (https://bridgecrew.io/blog/terraform-plan-security-scanning-checkov/). 

Relates to: https://github.com/bridgecrewio/checkov-action/issues/88

While debugging to figure out why I could not scan a single file with the GitHub action I noticed that [action definition](https://github.com/bridgecrewio/checkov-action/blob/master/action.yml) did not have any configuration to accept the argument for files `-f`. This means that this GH action will not work to scan terraform plans, therefore making some of Chekov's functionality unusable and causing issues like https://github.com/bridgecrewio/checkov-action/issues/70

This is not only a flag to point out what is happening but also I am providing an example of what needs to be changed to make this functionality available (Implementation will vary).

Proposed Changes:

- Repo: https://github.com/bridgecrewio/checkov

  On this we need to modify the [entrypoint.sh](https://github.com/bridgecrewio/checkov/blob/master/github_action_resources/entrypoint.sh) used by the [docker image](https://github.com/bridgecrewio/checkov/blob/master/Dockerfile) that is used by the [github action](https://github.com/bridgecrewio/checkov-action/blob/4b6b3857279f6b82beb58b4151dc9f7a0f9302c8/action.yml#L73). 

  What we need to do is to make the script looks for the presence of the file flag and modifies the command used, therefore, enabling scanning of individual files/resources. 

  This is what I would change:
  > https://github.com/bridgecrewio/checkov/blob/f7e3569c17c020f5e4eead5656c685ddd0c3f732/github_action_resources/entrypoint.sh#L102-L110

  and replace it with:
  ```bash
  # If File Variable exists then use -f flag to scan specific resources
  if [ -n "$INPUT_FILE" ]; then
    RESOURCE_TO_SCAN="-f $INPUT_FILE"
    echo "running checkov on file: $INPUT_FILE"
  else
  # Otherwise exists then use -d flag for directory scaning
    RESOURCE_TO_SCAN="-d $INPUT_DIRECTORY"
    echo "running checkov on directory: $INPUT_DIRECTORY"
  fi 
  # Build command
  if [ -n "$API_KEY_VARIABLE" ]; then
    echo "checkov --bc-api-key XXXXXXXXX-XXX-XXXXX --branch $GIT_BRANCH --repo-id $GITHUB_REPOSITORY $RESOURCE_TO_SCAN $CHECK_FLAG $SKIP_CHECK_FLAG $COMPACT_FLAG $QUIET_FLAG $SOFT_FAIL_FLAG $EXTCHECK_DIRS_FLAG $EXTCHECK_REPOS_FLAG $OUTPUT_FLAG $DOWNLOAD_EXTERNAL_MODULES_FLAG $CONFIG_FILE_FLAG $SOFT_FAIL_ON_FLAG $HARD_FAIL_ON_FLAG $FRAMEWORK_FLAG $BASELINE_FLAG $VAR_FILE_FLAG"
    CHECKOV_RESULTS=$(checkov --bc-api-key $API_KEY_VARIABLE --branch $GIT_BRANCH --repo-id $GITHUB_REPOSITORY $RESOURCE_TO_SCAN $CHECK_FLAG $SKIP_CHECK_FLAG $COMPACT_FLAG $QUIET_FLAG $SOFT_FAIL_FLAG $EXTCHECK_DIRS_FLAG $EXTCHECK_REPOS_FLAG $OUTPUT_FLAG $DOWNLOAD_EXTERNAL_MODULES_FLAG $CONFIG_FILE_FLAG $SOFT_FAIL_ON_FLAG $HARD_FAIL_ON_FLAG $FRAMEWORK_FLAG $BASELINE_FLAG $VAR_FILE_FLAG)
    else
    echo "checkov $RESOURCE_TO_SCAN $CHECK_FLAG $SKIP_CHECK_FLAG $COMPACT_FLAG $QUIET_FLAG $EXTCHECK_DIRS_FLAG $EXTCHECK_REPOS_FLAG $OUTPUT_FLAG $SOFT_FAIL_FLAG $DOWNLOAD_EXTERNAL_MODULES_FLAG $CONFIG_FILE_FLAG $SOFT_FAIL_ON_FLAG $HARD_FAIL_ON_FLAG $FRAMEWORK_FLAG $BASELINE_FLAG $VAR_FILE_FLAG"
    CHECKOV_RESULTS=$(checkov $RESOURCE_TO_SCAN $CHECK_FLAG $SKIP_CHECK_FLAG $COMPACT_FLAG $QUIET_FLAG $EXTCHECK_DIRS_FLAG $EXTCHECK_REPOS_FLAG $OUTPUT_FLAG $SOFT_FAIL_FLAG $DOWNLOAD_EXTERNAL_MODULES_FLAG $CONFIG_FILE_FLAG $SOFT_FAIL_ON_FLAG $HARD_FAIL_ON_FLAG $FRAMEWORK_FLAG $BASELINE_FLAG $VAR_FILE_FLAG)
  fi
  ```

- Repo: https://github.com/bridgecrewio/checkov-action

  Once the entrypoint has been modified to work with the file flag and the new docker image is deployed, modifying the action. yaml is pretty simple.

  
  Add input for file argument
  > Where: https://github.com/bridgecrewio/checkov-action/blob/4b6b3857279f6b82beb58b4151dc9f7a0f9302c8/action.yml#L5-L10

  ```yaml
  name: 'Checkov GitHub Action'
  author: 'Chris Mavrakis'
  description: 'Run Checkov against Terraform/CloudFormation infrastructure code, as a pre-packaged GitHub Action.'
  inputs:
    file:
      description: 'File with infrastructure code to scan'
      required: false
    directory:
      description: 'Directory with infrastructure code to scan'
      required: false
      default: '.'
  ```
  And map the input to the args to be consumed by the docker images entrypoint.sh
  > Where: https://github.com/bridgecrewio/checkov-action/blob/4b6b3857279f6b82beb58b4151dc9f7a0f9302c8/action.yml#L74-L76
  ```yaml
    args:
      - ${{ inputs.file }}
      - ${{ inputs.directory }}
      - ${{ inputs.check }}
      - ${{ inputs.skip_check }}
  ``` 

Testing
I've tested this myself in a private repo where:
- I created a new docker image with the changes (entrypoint.sh)
- Updated action.yaml and executed a github action to ensure changes worked

Here are the two resources I updated:
- https://gist.github.com/roymartinezblanco/e30c688b91156582576e2d53267d1d86
- https://gist.github.com/roymartinezblanco/d61e38e7c710577cbd7384cc444a2f32

and consumed with:
```yaml
      - name: Static Code Analysis
        uses: ./checkov-action/
        with:
            file: infra/plans/tfplan.json
            quiet: true # optional: display only failed checks
            soft_fail: true # optional: do not return an error code if there are failed checks
            framework: terraform_plan # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
            container_user: 1000 #
            compact: true
#            log_level: DEBUG
            external_checks_dirs: policy_as_code/policies
        continue-on-error: true
```
