### ISSUE TITLE
Graph Rules to Validate Attributes for Transitive Resources

### ISSUE THREAD

**Issue by michaelstanfa** [bridgecrewio/checkov#3094]
**Describe the issue**
We want to leverage checkov graph to perform dynamic validations against CloudFormation. We are unable to perform transitive attribute validation, i.e., we can only perform consistently accurate attribute validations against the resource(s) actively filtered on at the root of the graph rule definition. We want to validate that an attribute of a connected resource contains a specific value, but only require that the connected resource attribute contains said value when it's connected to the specific resource we are filtering on.

**Examples**
Simple architecture diagram for resources we want to test:
![graph_issue_diagram](https://user-images.githubusercontent.com/17631787/174168478-5614d6cf-722f-4180-a2f9-17963ad9bac6.png)

In the above example, `AWS::CloudTrail::Trail` is the primary resource and the source of the rule. However, other resources have requirements when they are connected to CloudTrail, too. If the CloudTrail resource sends notifications via SNS, then we want to validate that the `AWS::SNS::TopicPolicy` has a specific condition: the existence of 
 a `PolicyDocument.Statement.*.Condition.ArnEquals.aws:SourceArn` attribute within the `AWS::SNS::TopicPolicy` `PolicyDocument`.

A simple testing CloudFormation json structure looks like the following:

```json
{
  "Resources": {
    "MyCloudTrail": {
      "Type": "AWS::CloudTrail::Trail",
      "Properties": {
        "SnsTopicName": { "Ref": "MySNSTopic" },
        "KMSKeyId": "placeholder"
      }
    },
    "MySNSTopic": {
      "Type": "AWS::SNS::Topic",
      "Properties": {
        "TopicName": "my_sns_topic"
      }
    },
    "MyTopicPolicy": {
      "Type": "AWS::SNS::TopicPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Allow",
              "Action": "sns:Publish:*",
              "Condition": {
                "ArnEquals": { "aws:SourceArn": { "Ref": "MyCloudTrail" } }
              }
            }
          ]
        },
        "Topics": [{ "Ref": "MySNSTopic" }]
      }
    }
  }
}
```
The current graph .yaml configuration to test this configuration is below:
```yaml
metadata:
  name: "CloudTrail can only send notifications to SNS topics that employ 'aws:SourceArn'"
  id: "CUSTOM_CHECKOV_RULE_ID_123"
  category: "GENERAL_SECURITY"
definition:
  and:
    # Working with cloudtrail
    - cond_type: filter
      attribute: resource_type
      value:
        - AWS::CloudTrail::Trail
      operator: within
    - or:
        # no connection to SNS
        - cond_type: connection
          operator: not_exists
          resource_types:
            - AWS::CloudTrail::Trail
          connected_resource_types:
            - AWS::SNS::Topic
        # proper connection to SNS
        - and:
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::CloudTrail::Trail
              connection_resource_types:
                - AWS::SNS::Topic
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::SNS::Topic
              connected_resource_types:
                - AWS::SNS::TopicPolicy
            - cond_type: attribute
              operator: exists
              resource_types:
                - AWS::SNS::TopicPolicy
              attribute: PolicyDocument.Statement.*.Condition.ArnEquals.aws:SourceArn
```
This graph rule _should_ do a few things:
- passes if there is no connection to SNS from CloudTrail
- passes if:
-- There is a valid connection between `CloudTrail::Trail` & `AWS::SNS::Topic`
-- There is a valid connection between `AWS::SNS::Topic` & `AWS::SNS::TopicPolicy`
-- `AWS::SNS::TopicPolicy` contains a specific attribute (noted above)

However, because we are not filtering on resources other than `AWS::CloudTrail::Trail`, attribute validation for `AWS::SNS::TopicPolicy` & connection validation between `CloudTrail::Trail` & `AWS::SNS::Topic`.

### Invalid fix:

We attempted to add additional fields to the root-level filter, The resulting .yaml looked like this:

```yaml
etc...
    # Working with cloudtrail
    - cond_type: filter
      attribute: resource_type
      value:
        - AWS::CloudTrail::Trail
        - AWS::SNS::Topic
        - AWS::SNS::TopicPolicy
      operator: within
...etc
```
This solution works in the example above, but when any other `AWS::SNS::Topic` is introduced in any CloudFormation template, this rule checks that unrelated resource and we receive a false failure: that unrelated topic policy does not, and should not, contain the `PolicyDocument.Statement.*.Condition.ArnEquals.aws:SourceArn` attribute noted above.

**Desktop (please complete the following information):**
 - OS: [WSL running Ubuntu 20.04]
 - Checkov Version [2.0.1129]

**Additional context**
- Is this the right approach to transitively test resources? If so, and it's not implemented, we will look into contributing back.
- If this is not the right approach, how should we proceed?
- How can we conditionally validate transitive resources?

**Comment by gruebel** [comment]
hey @michaelstanfa thanks for reaching out! I tested your policy and it works as it should. the `filter` block only indicates which resource type to mark, when the check fails/passes.

I extended your example to also do the reference back to the trail
```yaml
metadata:
  name: "CloudTrail can only send notifications to SNS topics that employ 'aws:SourceArn'"
  id: "CUSTOM_CHECKOV_RULE_ID_123"
  category: "GENERAL_SECURITY"
definition:
  and:
    # Working with cloudtrail
    - cond_type: filter
      attribute: resource_type
      value:
        - AWS::CloudTrail::Trail
      operator: within
    - or:
        # no connection to SNS
        - cond_type: connection
          operator: not_exists
          resource_types:
            - AWS::CloudTrail::Trail
          connected_resource_types:
            - AWS::SNS::Topic
        # proper connection to SNS
        - and:
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::CloudTrail::Trail
              connection_resource_types:
                - AWS::SNS::Topic
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::SNS::Topic
              connected_resource_types:
                - AWS::SNS::TopicPolicy
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::SNS::TopicPolicy
              connected_resource_types:
                - AWS::CloudTrail::Trail
            - cond_type: attribute
              operator: exists
              resource_types:
                - AWS::SNS::TopicPolicy
              attribute: PolicyDocument.Statement.*.Condition.ArnEquals.aws:SourceArn
```

If you have some examples, where your check is failing, but should actually pass and vice versa, then I can try to dig in deeper on what the issue could be 🙂

**Comment by michaelstanfa** [comment]
Adding in that additional check did appear to give us more consistent results with our tests. Thanks for taking a look and providing that feedback.
```yaml
- cond_type: connection
  operator: exists
  resource_types:
    - AWS::SNS::TopicPolicy
  connected_resource_types:
    - AWS::CloudTrail::Trail
```

After getting this to work, we tried expanding the tests to allow for another acceptable control:
```yaml
- cond_type: attribute
  operator: exists
  resource_types:
    - AWS::SNS::TopicPolicy
  attribute: PolicyDocument.Statement.*.Condition.StringEquals.aws:SourceAccount
```
Our rules state that a topic policy must have one of two valid controls: 
- ` StringEquals.aws:SourceAccount`
- `ArnEquals.aws:SourceArn`

A CFN example to work against:
```json
{
  "Resources": {
    "MyCloudTrail": {
      "Type": "AWS::CloudTrail::Trail",
      "Properties": {
        "SnsTopicName": { "Ref": "MySNSTopic" },
        "KMSKeyId": "placeholder"
      }
    },
    "MySNSTopic": {
      "Type": "AWS::SNS::Topic",
      "Properties": {
        "TopicName": "my_sns_topic"
      }
    },
    "MyTopicPolicy": {
      "Type": "AWS::SNS::TopicPolicy",
      "Properties": {
        "PolicyDocument": {
          "Statement": [
            {
              "Effect": "Allow",
              "Action": "sns:Publish:*",
              "Condition": {
                "StringEquals": { "aws:SourceAccount": "123456789012" }
              }
            }
          ]
        },
        "Topics": [{ "Ref": "MySNSTopic" }]
      }
    }
  }
}
```
and the .yaml file we've constructed:
```yaml
metadata:
  name: "CloudTrail can only send notifications to SNS topics that employ 'aws:SourceArn'"
  id: "CUSTOM_CHECKOV_RULE_ID_123"
  category: "GENERAL_SECURITY"
definition:
  and:
    # Working with cloudtrail
    - cond_type: filter
      attribute: resource_type
      value:
        - AWS::CloudTrail::Trail
      operator: within
    - or:
        # no connection to SNS
        - cond_type: connection
          operator: not_exists
          resource_types:
            - AWS::CloudTrail::Trail
          connected_resource_types:
            - AWS::SNS::Topic
        # proper connection to SNS
        - and:
            # CloudTrail to SNS
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::CloudTrail::Trail
              connection_resource_types:
                - AWS::SNS::Topic
            # Topic to TopicPolicy
            - cond_type: connection
              operator: exists
              resource_types:
                - AWS::SNS::Topic
              connected_resource_types:
                - AWS::SNS::TopicPolicy
            - or:
                # Source Account - no identifiable connection between TopicPolicy & CloudTrail with the StringEquals referencing a string, not an actual resource reference
                - cond_type: attribute
                  operator: exists
                  resource_types:
                    - AWS::SNS::TopicPolicy
                  attribute: PolicyDocument.Statement.*.Condition.StringEquals.aws:SourceAccount
                # Source Arn - SourceArn exists & TopicPolicy connected to CloudTrail
                - and:
                    - cond_type: attribute
                      operator: exists
                      resource_types:
                        - AWS::SNS::TopicPolicy
                      attribute: PolicyDocument.Statement.*.Condition.ArnEquals.aws:SourceArn
                    - cond_type: connection
                      operator: exists
                      resource_types:
                        - AWS::SNS::TopicPolicy
                      connected_resource_types:
                        - AWS::CloudTrail::Trail
```
We have not been able to successfully pass any `StringEquals` checks with the `aws:SourceAccount` check ([docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourceaccount)). Even when we simplify the .yaml file so the deepest `and` looks like the following, the StringEquals check does not work as expected:
```yaml
...
 - and:
    # CloudTrail to SNS
    - cond_type: connection
      operator: exists
      resource_types:
        - AWS::CloudTrail::Trail
      connection_resource_types:
        - AWS::SNS::Topic
    # Topic to TopicPolicy
    - cond_type: connection
      operator: exists
      resource_types:
        - AWS::SNS::Topic
      connected_resource_types:
        - AWS::SNS::TopicPolicy
    # Source Account - no identifiable connection between TopicPolicy & CloudTrail with the StringEquals referencing a string, not an actual resource reference
    - cond_type: attribute
      operator: exists
      resource_types:
        - AWS::SNS::TopicPolicy
      attribute: PolicyDocument.Statement.*.Condition.StringEquals.aws:SourceAccount
```
Any insight you can provide to get the `StringEquals` check against an `{aws:SourceAccount: "123456789012"}` object would help us achieve a valid test against our cloudformation.
