### ISSUE TITLE
Add ability to limit module source as a custom policy

### ISSUE THREAD

**Issue by tsmithv11** [bridgecrewio/checkov#3233]
**Describe the issue**
Users would like the ability to check that Terraform code only uses modules from trusted sources. We would need to add the ability to check the module source against a regex policy. Here is an example policy that could be written:

```yaml
metadata:
  name: "Trusted source check"
  guidelines: "Use a trusted source"
  category: "general"
  severity: "medium"
#scope: #not relevant
#  provider: "" #not required
definition:
  cond_type: "attribute"
  resource_types:
  - "module"
  attribute: "source"
  operator: "subset"
  value:
  - "hashicorp/cloudposse/*"
  - "./" #local source allowed or not depending on the operator
  - "github.com/hashicorp/example"
```
