### ISSUE TITLE
PodSecurityContext ignored for related checks

### ISSUE THREAD

**Issue by sgspinola** [bridgecrewio/checkov#3300]
**Describe the issue**
For checks like CKS_K8S_28 or CKS_K8S_31, checkov fails to recognise the presence of a `securityContext` addressing the specific configuration at `Pod` level. As per the documentation at [Set the securityContext for a Pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod):

> The security settings that you specify for a Pod apply to all Containers in the Pod.

So I expect Checkov to be aware of this field when it comes to related checks. Is there any logic I might be missing for this behaviour?

**Examples**
The following sample `Deployment` fails when checked against CKS_K8S_28:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysample-deployment
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        capabilities:
          drop:
          - all
      initContainers:
        - name: init
          image: myimage
          imagePullPolicy: IfNotPresent
          # securityContext:
          #   capabilities:
          #     drop:
          #     - all
      terminationGracePeriodSeconds: 60
      containers:
        - name: main
          image: myimage
          imagePullPolicy: IfNotPresent
          # securityContext:
          #   capabilities:
          #     drop:
          #     - all
```
Output:
```zsh
Check: CKV_K8S_28: "Minimize the admission of containers with the NET_RAW capability"
        FAILED for resource: Deployment.default.mysample-deployment
        File: /sample.yaml:1-25
        Guide: https://docs.bridgecrew.io/docs/bc_k8s_27

                1  | apiVersion: apps/v1
                2  | kind: Deployment
                3  | metadata:
                4  |   name: mysample-deployment
                5  | spec:
                6  |   replicas: 1
                7  |   template:
                 ...
```
But when applied on `initContainers` and `containers`, it passes the check:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysample-deployment
spec:
  replicas: 1
  template:
    spec:
      # securityContext:
      #   capabilities:
      #     drop:
      #     - all
      initContainers:
        - name: init
          image: myimage
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
              - all
      terminationGracePeriodSeconds: 60
      containers:
        - name: main
          image: myimage
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
              - all
```
Output:
```zsh
$ checkov --directory . --quiet --framework kubernetes --check CKV_K8S_28
kubernetes scan results:

Passed checks: 1, Failed checks: 0, Skipped checks: 0
```

**Version (please complete the following information):**
 - Checkov Version: 2.1.90

**Additional context**
Installed through `pip3`
