### ISSUE TITLE
Azure DevOps Test Results - Bridgecrew docs links not working

### ISSUE THREAD

**Issue by thepaulmacca** [bridgecrewio/checkov#3326]
I have the scan test results publishing fine - but in the test failures, the links to the bridgecrew docs pages don't look to be working 

They just redirect back to my git repo for some reason. Same for the `yaml` file the rule is referring to:

![image](https://user-images.githubusercontent.com/41340540/183459555-5e97a9a4-e73c-4394-90f0-99cd393187f7.png)

Here is my pipeline config:

```yaml
- bash: |
    checkov \
      --directory $(Build.SourcesDirectory)/tests/pmc-library-testing \
      --framework helm \
      --var-file $(Build.SourcesDirectory)/tests/pmc-library-testing/environments/dev/values.yaml \
      --skip-check CKV_K8S_21 \
      --output junitxml \
      --soft-fail \
      > $(System.DefaultWorkingDirectory)/checkov-report.xml
  displayName: Run checkov scan

- task: PublishTestResults@2
  inputs:
    testRunTitle: 'Checkov Scan Results'
    failTaskOnFailedTests: true
    testResultsFormat: 'JUnit'
    testResultsFiles: 'checkov-report.xml'
    searchFolder: $(System.DefaultWorkingDirectory)
  displayName: Publish checkov scan results
```

Are these links working for anyone else?

Thanks
