### ISSUE TITLE
Checkov filter with tags_all is not working

### ISSUE THREAD

**Issue by AndreKapraty** [bridgecrewio/checkov#3348]
**Describe the issue**
I am trying to filter resources by environment using tags. But It's failing and not returns proper output. For instance, we have the following tags_all input (from terraform plan file):

```
"tags_all": {
                4511 |                   "Name": "some-test",
                4512 |                   "application_name": "test",
                4513 |                   "backups_account_enabled": "false",
                4514 |                   "country": "ukraine",
                4515 |                   "db_name": "test",
                4516 |                   "environment": "production",
                4517 |                   "group": "test",
                4518 |                   "product_name": "test",
                4519 |                   "service_name": "test",
                4520 |                   "team_name": "test"
```

And trying to filter resources by environment tag:

```
---
metadata:
  name: "RDS cluster not properly sized (for Aurora MySQL - db.t3.small, for Aurora PostgreSQL - db.tg4.medium)"
  id: "RDS_INSTANCE_SIZE"
  category: "CONVENTION"
definition:
   and:
    - cond_type: "filter"
      attribute: "resource_type"
      value:
        - "aws_rds_cluster_instance"
      operator: "within"
    - cond_type: filter
      resource_types:
        - aws_rds_cluster_instance
      attribute: "tags_all.environment"
      operator: within
      value: "staging"
    - cond_type: "attribute"
      resource_types:
      - aws_rds_cluster_instance
      attribute: "instance_class"
      operator: "within"
      value: 
        - "db.tg4.medium"
        - "db.t3.small"
```

But It's failing. If I understood correctly, It should just end with a success exit code and be skipped as this group of resources are under the production environment

The main idea of this policy to allow creation of RDS instances with only specific instance types

**Additional context**
-

**Comment by gruebel** [comment]
hey @AndreKapraty thanks for reaching out. I think there is a misunderstanding on how the YAML based policies work.
You basically check here that all `aws_rds_cluster_instance` need to have an attribute `tags_all.environment` with a vlaue of `staging` and `instance_class` being either `db.tg4.medium` or `db.t3.small`. That's why your check fails against the production resource, because it has the wrong tag. What you probably tried to do is something like that
```yaml
definition:
  or:
    - cond_type: "attribute"
      resource_types:
        - aws_rds_cluster_instance
      attribute: "tags_all.environment"
      operator: within
      value: "production"
    - and:
      - cond_type: "attribute"
        resource_types:
          - aws_rds_cluster_instance
        attribute: "tags_all.environment"
        operator: "equals"
        value: "staging"
      - cond_type: "attribute"
        resource_types:
        - aws_rds_cluster_instance
        attribute: "instance_class"
        operator: "within"
        value:
          - "db.tg4.medium"
          - "db.t3.small"
```
