### ISSUE TITLE
【Terraform plan resource not deleted】is invalid

### ISSUE THREAD

**Issue by foreverwf** [bridgecrewio/checkov#3357]
**Describe the issue**
custom yaml policies
```
---
metadata:
  name: "Ensure Secret is not deleted"
  id: "CKV2_ALI_2"
  category: "GENERAL_SECURITY"
scope:
  provider: alicloud
definition:
  cond_type: attribute
  resource_types:
    - alicloud_vpc
  attribute: __change_actions__
  operator: not_contains
  value: delete
```
tf.json
![image](https://user-images.githubusercontent.com/38393219/184501202-0cad9f4b-5791-4f6d-ba8d-46f1b5753edd.png)
log
```
terraform_plan scan results:

Passed checks: 4, Failed checks: 0, Skipped checks: 0

Check: CKV2_ALI_1: "example"
        PASSED for resource: alicloud_vpc.vpc-boss-pre
        File: /tf.json:0-0
Check: CKV2_ALI_1: "example"
        PASSED for resource: alicloud_vpc.vpc-boss-prod
        File: /tf.json:0-0
Check: CKV2_ALI_2: "Ensure Secret is not deleted"
        PASSED for resource: alicloud_vpc.vpc-boss-pre
        File: /tf.json:0-0
Check: CKV2_ALI_2: "Ensure Secret is not deleted"
        PASSED for resource: alicloud_vpc.vpc-boss-prod
        File: /tf.json:0-0
```

**Version (please complete the following information):**
 - Checkov Version 2.1.121
