### ISSUE TITLE
Why checkov doesn't display `Severity` in the output when running via docker container with the default image?

### ISSUE THREAD

**Issue by KelvinVenancio** [bridgecrewio/checkov#3442]
**Describe the issue**
We are running checkov using the default `bridgecrew/checkov` image, and in the output, the Severity is not displayed. I did a local test, see the result:

```bash
$ docker run --tty --volume $PWD:/tf --workdir /tf bridgecrew/checkov -f tfplan.json
```

Output:
![Captura de tela de 2022-08-30 12-09-30](https://user-images.githubusercontent.com/5761755/187473601-ff0df452-87eb-43ae-9f57-6387f1081d01.png)

If I run outside Docker container, on my Local OS (Ubuntu 20.04), I see the output in the way I need:

```bash
$ checkov -f tfplan.json
```

Output:
![Captura de tela de 2022-08-30 12-12-56](https://user-images.githubusercontent.com/5761755/187474406-cac036e3-5d96-4dee-9710-227fe9688793.png)

I did comparisons with the `--show-config` flag in both environments (my local OS and in the docker container) and didn't notice any difference. This directly impacts my CI flow report, because without displaying this information, my output appears with [NONE], see:

![screenshot-gitlab com-2022 08 30-12_18_05](https://user-images.githubusercontent.com/5761755/187475831-7de2a32c-e01a-47e9-8c35-76288023caf2.png)

Finally, the only difference I could see is that when I run locally, this appears before the result:

```text
[ kubernetes framework ]: 100%|████████████████████|[1/1], Current File Scanned=tfplan.json
[ gitlab_configuration framework ]: 100%|████████████████████|[1/1], Current File Scanned=../tfplan.json
[ bitbucket_configuration framework ]: 100%|████████████████████|[1/1], Current File Scanned=../tfplan.json
[ github_configuration framework ]: 100%|████████████████████|[1/1], Current File Scanned=../tfplan.json
[ secrets framework ]: 100%|████████████████████|[1/1], Current File Scanned=tfplan.json
```

Honestly, I don't know what it is. I tried to find and use some parameter options as described [here](https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html), but with no success. I'm also not sure if this is the expected behavior when checkov is run inside a docker container with the default image etc. Can anyone help me here?

**Additional context**
I tested with two versions (local and docker image): 2.1.150 and 2.1.170. Same behavior in both versions.

**FYI:** Using tfsec I get the result I expect, but I would like to use checkov. :)
![Captura de tela de 2022-08-30 12-29-15](https://user-images.githubusercontent.com/5761755/187478591-82fae13c-7d43-4817-8691-41867461b5e7.png)

**Comment by gruebel** [comment]
hey @KelvinVenancio thanks for reaching out. Severities are only shown when you use an API key. My guess is, that you configured it and they are probably stored under your home folder `[home]/.bridgecrew/credentials`.

**Comment by KelvinVenancio** [comment]
hey @gruebel, you completely right, I did a test with the API key and it works like a charm. Thanks!

**Comment by AshishDadhich4h2** [comment]
Is any flag/input parameter to pass api key using docker image? @KelvinVenancio  @gruebel 
docker run --tty --volume $PWD:/tf --workdir /tf bridgecrew/checkov

**Comment by AshishDadhich4h2** [comment]
As I want to report severity in test results and it's only possible if we use api key so trying to find how do you pass that api token in docker cli. 
I got it that checkov cli supports --bc-api-key API_KEY but couldn't find same kind of flag for docker cli

**Comment by KelvinVenancio** [comment]
hey @AshishDadhich4h2, it's the same parameter, see:
```
$ export BC_API_KEY=your-key
$ docker run --tty --volume $PWD:/tf --workdir /tf --env BC_API_KEY=$BC_API_KEY bridgecrew/checkov --bc-api-key $BC_API_KEY -f tfplan.json
```
Something like that will work for you. The entry point of the image is the checkov command.

If you are using Github, there is an action that you can use on your CI: https://github.com/bridgecrewio/checkov-action
If you are using Gitlab, I have this step here (I use Gitlab too):
```
checkov:
  stage: security
  cache: []
  image:
    name: bridgecrew/checkov:2.1.150
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  rules:
    - if: $CHECKOV_DISABLED
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_REF_NAME == "main" || $CI_PIPELINE_SOURCE == "merge_request_event"'
  dependencies:
    - terraform build plan
  script:
    - >
      if [ "$CHECKOV_QUALITY_GATE" == "true" ]; then
        checkov -f checkov.json -o junitxml --bc-api-key $BC_API_KEY --repo-id $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME --branch $CI_COMMIT_REF_NAME | tee checkov.test.xml
      else
        checkov -s -f checkov.json -o junitxml --bc-api-key $BC_API_KEY --repo-id $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME --branch $CI_COMMIT_REF_NAME | tee checkov.test.xml
      fi
  artifacts:
    reports:
      junit: checkov.test.xml
    paths:
      - checkov.test.xml
```
Let me know if this helps you.
