### ISSUE TITLE
Usage of --external-checks-dir, custom checks do not get recognized

### ISSUE THREAD

**Issue by nijdarshan** [bridgecrewio/checkov#3470]
Hi,

I am facing the same problem with my custom checks while trying to run in a pipeline. But, it works absolutely well when works scanned locally.

### **My sample check in python looks like below:**

```
from typing import Dict, Any

from checkov.common.models.enums import CheckResult
from checkov.kubernetes.checks.resource.base_container_check import BaseK8sContainerCheck


class ApiServerAuditLog(BaseK8sContainerCheck):
    def __init__(self) -> None:
        id = "CKV_K8S_999"
        name = "Ensure that the --audit-log-path argument is set"
        super().__init__(name=name, id=id)

    def scan_container_conf(self, metadata: Dict[str, Any], conf: Dict[str, Any]) -> CheckResult:
        self.evaluated_container_keys = ["command"]
        if conf.get("command") is not None:
            if "kube-apiserver" in conf["command"]:
                hasAuditLog = False
                for command in conf["command"]:
                    if command.startswith("--audit-log-path"):
                        hasAuditLog = True
                return CheckResult.PASSED if hasAuditLog else CheckResult.FAILED

        return CheckResult.PASSED

check = ApiServerAuditLog()
```

### **.gitlab-ci.yml looks like below:**
```
stages:
    - test
    
checkov:
  stage: test
  allow_failure: true  # True for AutoDevOps compatibility
  image:
    name: bridgecrew/checkov
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - '**/*.yml'
        - '**/*.yaml'
        - '**/*.json'
        - '**/*.template'
        - '**/*.tf'      
        - '**/serverless.yml'
        - '**/serverless.yaml'
  script:
      - checkov -d ./ --external-checks-dir ./ --check CKV_K8S_999 
```

### **My GitLab repo structure:**
![image](https://user-images.githubusercontent.com/51939272/188483398-dec5c289-9c71-4bda-9ec7-45b25d68dc39.png)

Can someone please help? Thanks!
