### ISSUE TITLE
Incorrectly fails CKV_AWS_23 even with description set

### ISSUE THREAD

**Issue by bbriggs** [bridgecrewio/checkov#353]
**Describe the bug**
Checkov is incorrectly failing check CKV_AWS_23

**To Reproduce**
Apply checkov via GH Actions using a security group rule like the following
```
# GH Actions excerpt
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install deps
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install checkov
        run: pip install checkov

      - name: Check example directory
        run: checkov -d ./example_directory
```

```
resource "aws_security_group" "inbound_public_ssh" {
  name        = "inbound_public_ssh"
  description = "Allow SSH from limited public source IPs"
  vpc_id      = module.some_vpc.vpc_id
  // ingress and egress rules omitted
}
```

**Expected behavior**
Test passes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `ubuntu-latest` via Github Actions (18.04)
 - Checkov Version: latest from `pip install`

**Additional context**
Add any other context about the problem here (e.g. code snippets).
