### ISSUE TITLE
CKV2_AWS_38/39 produce empty `helpUri` in sarif output

### ISSUE THREAD

**Issue by ankon** [bridgecrewio/checkov#3540]
**Describe the issue**

We're producing sarif output from checkov in a github action. This started failing now because the sarif contains `helpUri: null` fields, which aren't valid (https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317848). 
![image](https://user-images.githubusercontent.com/1210641/191239371-e197a8b3-d00b-457c-98b7-849ffdfddd31.png)

I can reproduce this locally with checkov 2.1.216, and in my case it's the rules CKV2_AWS_38 and CKV2_AWS_39 with invalid content:
![image](https://user-images.githubusercontent.com/1210641/191239878-d463ea41-f9dc-4e74-ba47-f66cacf3cda0.png)

**Additional context**

Possibly caused by: #3492 adding `helpUri`
A similar issue existed in cfn-lint, where the fix was to ensure that `helpUri` is pointing to something sane in all cases: https://github.com/aws-cloudformation/cfn-lint/pull/2276

**Workaround**

We filter the content before uploading now:

```yaml
      - name: "Band-aid: Remove empty helpUri in sarif"
        run: jq 'del(.runs[].tool.driver.rules[].helpUri|select(.=="" or .==null))' <results.sarif >results-fixed.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-fixed.sarif
```
