### ISSUE TITLE
Not showing guideline from local custom policy

### ISSUE THREAD

**Issue by jota3c** [bridgecrewio/checkov#3594]
**Describe the issue**
No guidelines and priority on results of custom policies when loaded using using --external-checks-dir.
Using the same policy added on bridgecrew.cloud works showing the guideline/priority on cli output.

**Additional context**
To reproduce :

```
metadata:
  name: "Check that all resources are tagged"
  guidelines: "guide link here"
  category: "general"
  severity: "low"
scope:
  provider: azure
definition:
  cond_type: "attribute"
  resource_types:
    - "all"
  attribute: "tags"
  operator: "exists"

checkov --version
2.1.242

checkov -d . --external-checks-dir checkov-test-policies/  --bc-api-key "xxx" --output junitxml --soft-fail 
```
Results : 
```
                <testcase name="[NONE][] Check that all resources are tagged" classname="/main.tf.module.teste.azurerm_..." file="/main.tf">
                        <failure type="failure" message="Check that all resources are tagged">
Resource: module.teste.azurerm_...
File: /main.tf: 5-23
Guideline: None
```
Removing the local policy and adding on bridgecrew.cloud/policies :
```
                <testcase name="[LOW][removed-account-here] Check that all resources are tagged" classname="/main.tf.module.teste.azurerm_..." file="/main.tf">
                        <failure type="failure" message="Check that all resources are tagged">
Resource: module.teste.azurerm_...
File: /main.tf: 5-23
Guideline: guide link here

```
