### ISSUE TITLE
Support details field in custom YAML policies?

### ISSUE THREAD

**Issue by CTLaChance** [bridgecrewio/checkov#3623]
Apologies if this isn't the correct place to ask questions, but I didn't see a discussions tab.

I'm attempting to return a custom error message when my custom YAML policy fails for a resource. In a python policy this would be as simple as appending a string to the `details` for the check.

I've looked through the YAML policy docs and haven't seen a way to accomplish this. If this isn't possible, I'd like to request its addition as a feature.

Thanks!

**Comment by gruebel** [comment]
hey @CTLaChance thanks for reaching out. We usually suggest to ask question in our Slack channel, which you can join for free https://slack.bridgecrew.io/ no strings attached 🙂 
Yeah, the `details` attribute is currently only available for Python checks, but sounds like a good idea to also add it to the YAML based policies. You could leverage the `guideline` field under `metadata`, which would give you the possibility to put any kind of text in it
https://github.com/bridgecrewio/checkov/blob/2fce14ee65f4e6143c2a510e3219b9957ee5a50f/docs/3.Custom%20Policies/YAML%20Custom%20Policies.md?plain=1#L40-L46

How would you expect it to look like? Something like this
```yaml
metadata:
  id: "CKV2_CUSTOM_1"
  name: "Ensure bucket has versioning and owner tag"
  category: "BACKUP_AND_RECOVERY"
  guideline: "https://docs.bridgecrew.io/docs/ckv2_custom_1"
  details:
    - "some great details"
    - "more better details"
```
