### ISSUE TITLE
Binary Logical operators within JSONPaths are not working if the form is `&&` instead of `&` (same for "or")

### ISSUE THREAD

**Issue by kadoshms** [bridgecrewio/checkov#3642]
**Describe the issue**

Assuming we have this check:

```
metadata:
  id: "test"
scope:
  provider: "aws"
definition:
  cond_type: "attribute"
  resource_types:
    - "aws_security_group"
  attribute: "ingress[?(@.to_port==22 && @.from_port==22)].cidr_blocks[*]"
  operator: "jsonpath_contains"
  value: "0.0.0.0/0"
```

due to usage of `jsonpath-ng` under the hood, the abvoe check fails since `&&` is invalid token - expected to have `&` instead.
I guess that for many users this will be less predictable as `&&` is a valid form as well.
