### ISSUE TITLE
Custom Rule crashes Checkov in pipeline 

### ISSUE THREAD

**Issue by SiSiHenry** [bridgecrewio/checkov#3714]
**Describe the issue**
Currently using Checkov in pipeline for pre-commit checks. The rule below is validating if S3 bucket policy is configured with TLS. 

When run in my pipeline, it crashes when scanning EKS, ECS, etc resources.  

I would like to know if there is another way to call for conditions, to validate settings in aim permissions ? 

**Example Value**
```
from typing import Dict, List, Any
from checkov.common.util.type_forcers import force_list
from checkov.terraform.checks.data.base_check import BaseDataCheck
from checkov.common.models.enums import CheckResult, CheckCategories
 

class S3BucketAllowsSSLRequestsOnlyV1(BaseDataCheck):
 
    def __init__(self):
       
        name = "S3 bucket policy allows SSL requests only (only applies to S3 bucket policies)"
        id = "custom_AWS_TF_S3_7777"
        supported_data = ['aws_iam_policy_document']
        categories = [CheckCategories.IAM]
        super().__init__(name=name, id=id, categories=categories, supported_data=supported_data)
   
    def scan_data_conf(self, conf: Dict[str, List[Any]]) -> CheckResult:
       
        # booleans to determine pass/fail
        general_bool = False
        secure_transport_bool = False
        tls_version_bool = False
 
        for statements in conf.get("statement", []):
            statements = force_list(statements)
            for statement in statements:
                if (
                    isinstance(statement, dict)
                    and statement.get("effect") == ["Deny"]
                    and "s3:*" in statement["actions"][0]
                    and "*" in statement["principals"][0]["identifiers"][0]
                ):
                    general_bool = True
 
                for condition in statement["condition"]:
                    if (
                        "aws:SecureTransport" in condition["variable"]
                        and False in condition["values"][0]
                    ):
                        secure_transport_bool = True
                    if (
                        "s3:TlsVersion" in condition["variable"]
                        and all(value >= 1.2 for value in condition["values"][0])
                    ):
                        tls_version_bool = True
 
                if general_bool and secure_transport_bool and tls_version_bool:
                    return CheckResult.PASSED
 
        return CheckResult.FAILED
 
check = S3BucketAllowsSSLRequestsOnlyV1()
```

**Comment by gruebel** [comment]
hey @SiSiHenry thanks for reaching out. What do you mean with crash? Does it hang or you get an error?

**Comment by SiSiHenry** [comment]
When I say crash, it gives an error.

**Comment by gruebel** [comment]
can you share the error?

**Comment by SiSiHenry** [comment]
I am getting a KeyError: "condition" when I run this rule for policies that do not contain the condition key.

**Comment by SiSiHenry** [comment]
Am I scanning for the condition attribute correctly ? is there a way for me to place an else statement ?

**Comment by SiSiHenry** [comment]
in YAML I get an error generic traceback error

**Comment by gruebel** [comment]
when I use your custom check,I 2 different errors, one is related to you not tabbing the `and` operator and the other one is related to the `equal` operator, which need to be `equals`
so, at the end it needs to be like this to be valid
```yaml
metadata:

  name = "S3 bucket policy allows SSL requests only (only applies to S3 bucket policies)"

  id: "custom_AWS_TF_S3_1"

  category: "Security"

scope:

  provider: "aws"

definition:

  and:
  
     - cond_type: "attribute"
  
       resource_types:
  
       - "data.aws_iam_policy_document"
  
       attribute: "statement.actions"
  
       operator: "not_equals"
  
       value: "s3:*"
  
     - cond_type: "attribute"
  
       resource_types:
  
       - "data.aws_iam_policy_document"
  
       attribute: "statement.condition.variable"
  
       operator: "equals"
  
       value: "s3:TlsVersion"
  
     - cond_type: "attribute"
  
       resource_types:
  
       - "data.aws_iam_policy_document"
  
       attribute: "statement.condition.values"
  
       operator: "greater_than_or_equal"
  
       value: "1.2"
```
