### ISSUE TITLE
Enhance Library for JSONPath to add more Operators

### ISSUE THREAD

**Issue by jjchavanne** [bridgecrewio/checkov#3731]
**Describe the issue**
Require additional jsonpath operators then what is currently supported.

Example is request for use of a 'not_exist' operator.  The current library being used: https://github.com/h2non/jsonpath-ng does not appear to be being maintained.  Request if we can either find a better maintained library or fork and maintain our own so that additional features can be added.

**Examples**
I submitted a new request (sitting as a PR as of this writing: https://github.com/bridgecrewio/checkov/pull/3712).  I was unable to complete a test case for the following terraform example from the docs here: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document#effect

#Example Test Case - Fail for use of actions: "iam:*" and effect: "Allow" (Allow is the default for this data type so not required to be written, and therefore requires to code "effect" does not exist):
```
data "aws_iam_policy_document" "fail" {
#Default Allow
  statement {
    actions = [
      "iam:*",
    ]

    resources = [
      "*"
    ]
  }
}
```

# Expected result:
Find:
1) actions =/contains "item in a list OR <string>".  In example above that is "iam:*"
2) effect = "Allow" OR effect DOES_NOT_EXIST

**Version (please complete the following information):**
 - Checkov Version 2.1.270 (tested on)

**Additional context**
Currently there is no NOT_EXIST operator in the python library.
Additionally would be nice to have other common operators supported in other jsonpath libraries:  Here are some good examples:
https://support.smartbear.com/alertsite/docs/monitors/api/endpoint/jsonpath.html#filters

Using the example above, if an additional NOT "!" operator was added, the policy check might look like this:
```
  - cond_type: "attribute"
    resource_types:
    - "data.aws_iam_policy_document"
    attribute: "(statement[?(@.effect == 'Allow')] | statement[?(!@.effect)]).actions[*]"
    operator: "jsonpath_not_contains"
    value: "iam:*"
```
