### ISSUE TITLE
Obtain the condition block at the resource level.

### ISSUE THREAD

**Issue by Gaviria9601** [bridgecrewio/checkov#3840]
**Describe the issue**

It would be good in the query graph to get the condition block at the resource level, Why? Because at the rule logic level the condition value may be relevant.

Expected behavior for this use case:

**Examples**

> iac
```yaml


AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  pAcmcertificatearn:
    Description: ARN Digital Certificate
    Type: String
    
Conditions:
  envPdn: Equals [ !Ref environment, "pdn"]

Resources:

  MyCloudFront:
    Type: AWS::CloudFront::Distribution
    Condition: envPdn
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn:
            Ref: pAcmcertificatearn
  
  MyCloudFront2:
    Type: AWS::CloudFront::Distribution
    Condition: envPdn
    Properties:
      DistributionConfig:
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
```

> query

```py
from checkov.common.models.enums import CheckResult,CheckCategories
from checkov.cloudformation.checks.resource.base_resource_value_check import BaseResourceCheck

class CloudfrontCertificate(BaseResourceCheck):
    def __init__(self):
        name = "Ensure Cloudfront distribution has certificate"
        id = "CKV_AWS_XXX"
        supported_resources = ['AWS::CloudFront::Distribution']
        categories = [CheckCategories.GENERAL_SECURITY]
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf):

        if 'Properties' in conf.keys():
            if 'Condition' in conf['Properties'] and conf['Properties']['Condition'] == False:
                return CheckResult.SKIPPED
            elif 'DistributionConfig' in conf['Properties'].keys():
                if "ViewerCertificate" in conf['Properties']['DistributionConfig']:
                    if "AcmCertificateArn" in conf['Properties']['DistributionConfig']['ViewerCertificate']:
                        return CheckResult.PASSED
        return CheckResult.FAILED
```
