### ISSUE TITLE
Support forced colored output through environment variable

### ISSUE THREAD

**Issue by onezeroecho** [bridgecrewio/checkov#388]
Output from `checkov` does not display colors when running through GitLab CI or `gitlab-runner` locally. Supporting an environment variable like `CHECKOV_COLORS=1` to force colored output in CI runners would be a useful feature.

For example, other projects like [Molecule](https://molecule.readthedocs.io/en/latest/) and [Ansible](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-force-color) use `PY_COLORS` and `ANSIBLE_FORCE_COLOR`, respectively.

**Comment by schosterbarak** [comment]
Seems like a popular issue with gitlab-ci https://gitlab.com/gitlab-org/gitlab-runner/-/issues/332
any idea how to solve this? checkov is using python `colorama` package for colourful output

**Comment by onezeroecho** [comment]
Looks like I was able to get it working by utilizing the `script` command (borrowed from https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1021):

```yaml
checkov:
  stage: validate
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    # Need to use `script` which emulates `tty` for colored output.
    - script -q -c 'checkov --framework terraform -d terraform/'
```

Colors are being displayed properly now. @schosterbarak any chance we can get this added to the [Integrate Checkov with GitLab CI](https://github.com/bridgecrewio/checkov/blob/master/docs/4.Integrations/gitlab.md) documentation?
