### ISSUE TITLE
Data Object Custom Check Policy crashes

### ISSUE THREAD

**Issue by sun1l-aries** [bridgecrewio/checkov#3908]
**Describe the issue**
AM trying to create a Custom Policy Check for gcp_iam_Policy data object. The custom Policy crashes the checkov executable.

**Examples**
CustomPolicy.yml
```yaml
---
metadata:
   yamllint disable
  name: "GCP IAM Policy Data Source must not have not use Basic Primitive roles (Owner, Editor and Viewer)"
   yamllint enable
  id: "CKV2_GCP_1005"
  category: "IAM"
definition:
  - and:
      - cond_type: "attribute"
        resource_types:
          - "data.google_iam_policy"
        attribute: "binding.role"
        operator: "not_equals"
        value: "roles/editor"
      - cond_type: "attribute"
        resource_types:
          - "data.google_iam_policy"
        attribute: "binding.role"
        operator: "not_equals"
        value: "roles/viewer"
```

**Version (please complete the following information):**
 - Downloading the latest checkov version from dockerhub

**Additional context**
The IaC file used is

resource "google_folder_iam_policy" "folder" {
  folder      = "folders/1234567"
  policy_data = data.google_iam_policy.admin.policy_data
}

# Data Source Resource - IAM Policy
data "google_iam_policy" "admin" {
  binding {
    role = "roles/editor"

    members = [
      "user:jane@example.com",
    ]
  }
}

resource "google_folder_iam_binding" "folder" {
  folder  = "folders/1234567"
  role    = "roles/editor"

  members = [
    "user:jane@example.com",
  ]
}

resource "google_folder_iam_member" "folder" {
  folder  = "folders/1234567"
  role    = "roles/editor"
  member  = "user:jane@example.com"
}

The crash report in checkov logs is below:

Run docker run --tty --volume $(pwd):/tf --workdir /tf bridgecrew/checkov --config-file /tf/config/checkov_config.yaml
Error: -18 12:0[4](https://github.com/sun1l-aries/iac_checkov/actions/runs/3496726816/jobs/5854977838#step:5:5):04,562 [MainThread  ] [ERROR]  Failed to invoke function /usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry._parallel_run with <checkov.terraform.runner.Runner object at 0x7f1e866fd0d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/checkov/common/parallelizer/parallel_runner.py", line 39, in func_wrapper
    result = original_func(item)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 84, in _parallel_run
    report = runner.run(
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 104, in run
    self.load_external_checks(external_checks_dir)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 174, in load_external_checks
    self.graph_registry.load_external_checks(directory)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks_infra/registry.py", line 61, in load_external_checks
    self._load_checks_from_dir(dir, True)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks_infra/registry.py", line 51, in _load_checks_from_dir
    check = self.parser.parse_raw_check(
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks_infra/checks_parser.py", line 152, in parse_raw_check
    check = self._parse_raw_check(policy_definition, kwargs.get("resources_types"))
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks_infra/checks_parser.py", line 165, in _parse_raw_check
    complex_operator = get_complex_operator(raw_check)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks_infra/checks_parser.py", line 256, in get_complex_operator
    if raw_check.get(operator):
AttributeError: 'list' object has no attribute 'get'

**Comment by gruebel** [comment]
hey @sun1l-aries thanks for reaching out. Actually the check/policy definition is incorrect, the first operator can't be a list.
This should work
```yaml
metadata:
  name: "GCP IAM Policy Data Source must not have not use Basic Primitive roles (Owner, Editor and Viewer)"
  id: "CKV2_GCP_1005"
  category: "IAM"
definition:
  and:
    - cond_type: "attribute"
      resource_types:
        - "data.google_iam_policy"
      attribute: "binding.role"
      operator: "not_equals"
      value: "roles/editor"
    - cond_type: "attribute"
      resource_types:
        - "data.google_iam_policy"
      attribute: "binding.role"
      operator: "not_equals"
      value: "roles/viewer"
```
