### ISSUE TITLE
Checkov scan fail - CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"

### ISSUE THREAD

**Issue by Ramasubramoniam** [bridgecrewio/checkov#4127]
Since last two days, we are finding that - CKV2_GHA_1: "Ensure top-level permissions are not set to write-all" check is failing in our Github Action workflow files which was otherwise working properly. We have not modified our workflow files in these days. We couldn’t find any Checkov related document on how to remediate this fail. Could you help us with this issue in priority as we have production tasks in pipeline.

Attaching below the workflow file in our repo for which the scan is failing.

name: checkov-check
on:
  push:
    branches:
      - 'tech-dev-*'
jobs:
  checkov-check:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          pip install -q -U urllib3 requests
          pip install -q checkov
      - name: checkout code
        uses: actions/checkout@v3
      - name: scan
        run: |
          checkov --config-file $GITHUB_WORKSPACE/CodeValidation/checkov-check.yml --directory $GITHUB_WORKSPACE

Below is the failed check output 
Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
	FAILED for resource: permissions
	File: /.github/workflows/checkov-check.yml:0-1

**Comment by Riqardos** [comment]
I have the same problem, don't know how to skip it in code. For now I used `--skip-check CKV2_GHA_1 ` to skip it.

**Comment by shivvinaykanswal** [comment]
Encountered the same problem, even after changing permissions to read-all, checkov fails with the same error.

**Comment by marynaKK** [comment]
Hi! I've tried to run checkov on the example you gave with `permissions: read-all`, and `CKV2_GHA_1` is PASSED for me.
also giving specific permissions pass the test too. To sum up I couldn't reproduce The check failure as you described. 

Can you try adding this once again and see if this is working?

```
name: checkov-check

on:
  push:
    branches:
    - 'tech-dev-*'

permissions: read-all

jobs:
  checkov-check:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
            pip install -q -U urllib3 requests
            pip install -q checkov
      - name: checkout code
        uses: actions/checkout@v3
      - name: scan
        run: |
            checkov --config-file $GITHUB_WORKSPACE/CodeValidation/checkov-check.yml --directory $GITHUB_WORKSPACE
```

**Comment by gruebel** [comment]
thanks @marynaKK 
the default access is typically `write-all` with a few exceptions, https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token.
So, you should be more careful about which permissions are really needed for each job. And we are adding from time to time new checks, so if you are blocking your workflows you either need to only allow the checks you are interested in or pin the version of `checkov` and then test from time to time, what a new version will find in your templates.

**Comment by Riqardos** [comment]
@gruebel thanks, I temporary skip it with `--skip-check CKV2_GHA_1` as you said, maybe the question is how can I skip it in file, inline comment `#checkov:skip:CKV2_GHA_1:Comment` doesn't work. 
```
#checkov:skip:CKV2_GHA_1:Comment
name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
```

**Comment by gruebel** [comment]
hey @Riqardos 🙂 yeah I think that would be a great addition to `checkov` we will check, when we can tackle file based skips.

**Comment by snemetz** [comment]
I have this same issue when running pre-commit locally on mac. Checkov v2.2.330
I get the error for every github workflow file. All of the directories are 755 and the files are 644

**Comment by JamesWoolfenden** [comment]
@snemetz The default permission is write-all, so you need to set lower e.g.:
```
jobs:
   permissions: read-all
   terraform:
```

**Comment by Kurt-von-Laven** [comment]
The check does false-positive though. For instance, here is the output from running Checkov on [ScribeMD/docker-cache](https://github.com/ScribeMD/docker-cache):

```
Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
	FAILED for resource: on(Notify Assignee)
	File: /.github/workflows/notify-assignee.yaml:10-11

		10 |     permissions:
		11 |       contents: read

Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
	FAILED for resource: on(Notify Reviewers)
	File: /.github/workflows/notify-reviewers.yaml:10-11

		10 |     permissions:
		11 |       contents: read

Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
	FAILED for resource: on(Test)
	File: /.github/workflows/test.yaml:13-14

		13 |     permissions:
		14 |       checks: write # https://github.com/EnricoMi/publish-unit-test-result-action#permissions
```

Here are the pertinent source files:
- [ScribeMD/docker-cache/.github/workflows/notify-assignee.yaml#L10-L11](https://github.com/ScribeMD/docker-cache/blob/24b8a6fb1655d595d422b245041b0acad7df94b9/.github/workflows/notify-assignee.yaml#L10-L11)
- [ScribeMD/docker-cache/.github/workflows/notify-reviewers.yaml#L10-L11](https://github.com/ScribeMD/docker-cache/blob/24b8a6fb1655d595d422b245041b0acad7df94b9/.github/workflows/notify-reviewers.yaml#L10-L11)
- [ScribeMD/docker-cache/.github/workflows/test.yaml#L13-L15](https://github.com/ScribeMD/docker-cache/blob/24b8a6fb1655d595d422b245041b0acad7df94b9/.github/workflows/test.yaml#L13-L15)

**Comment by JamesWoolfenden** [comment]
You haven't set the top level permissions, otherwise the default permissions could be too permissive write-all, to pass it needs to be name: 
```yaml

Notify Assignee
on:
  pull_request:
    types:
      - assigned
permissions: read-all    
jobs:
  notify-assignee:
    name: Notify Assignee
    uses: ScribeMD/slack-templates/.github/workflows/notify-assignee.yaml@0.6.13
    permissions:
      contents: read
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_ASSIGN_CHANNEL_ID: ${{ secrets.SLACK_ASSIGN_CHANNEL_ID }}
```

**Comment by Kurt-von-Laven** [comment]
Thank you; that fixed our issues!

**Comment by jkatic85** [comment]
Reading this page: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs it says that: 
> If you specify the access for any of these scopes, all of those that are not specified are set to `none`.
So this check is basically a false positive.

**Comment by kpervin** [comment]
This is triggering a false positive for our actions pipeline:

```yaml
  terraform-apply:
    name: "Terraform Apply"
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
```
```
Check: CKV2_GHA_1: "Ensure top-level permissions are not set to write-all"
	FAILED for resource: on(Terraform Apply)
	File: /terraform-apply.yaml:52-53
```
