### ISSUE TITLE
Issue checking Serverless Framework projects with multiple config files

### ISSUE THREAD

**Issue by quickliketurtle** [bridgecrewio/checkov#4203]
**Describe the issue**
For Serverless Framework, when leveraging multiple config files: https://www.serverless.com/framework/docs/providers/aws/guide/variables#multiple-configuration-files Checkov is not checking resources in the nested file, or directly in the array provided. 

**Examples**
With a definition without multiple files running `heckov -d . --framework serverless --check CKV_AWS_28` returns the expected failed check. 
```
service: checkov-issue

provider:
  name: aws

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: checkov-issue
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

```

![CleanShot 2023-01-05 at 16 14 19](https://user-images.githubusercontent.com/1762128/210904060-0be62a30-39af-47dd-9945-4e40c3761add.png)

With the `resources` key as an array, checkov is not identifying the resources and performing checks on them. 

```
service: checkov-issue

provider:
  name: aws

resources:
  - Resources:
      UserTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: checkov-issue
          BillingMode: PAY_PER_REQUEST
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
```

![CleanShot 2023-01-05 at 16 14 52](https://user-images.githubusercontent.com/1762128/210904105-0ef300a5-3996-40b3-acc9-e5fa0894dba7.png)

**Version (please complete the following information):**
 - Checkov Version 2.1.270 and 2.2.225

**Additional context**
The same result happens if the resources key references a file include ` - ${file(resources/first-cf-resources.yml)` I just wanted to provide the simplest example. 
if you run `serverless package` you can verify that serverless does parse the file properly and generate the expected cloudformation: 
![CleanShot 2023-01-05 at 16 17 37](https://user-images.githubusercontent.com/1762128/210904444-4b943653-619f-49c2-9860-004cd3dbe80f.png)

Please let me know if there is additional info I can provide.
