### ISSUE TITLE
Using 'and' in custom .yml policy with two conditions on different resource_types fails

### ISSUE THREAD

**Issue by mhanysz** [bridgecrewio/checkov#4236]
I'm trying to write a custom policy using a yml file. It should check that two conditions are true at the same time using 'and'. The conditions work individually as expected (e.g. when commenting out the other one). Combining both of them with 'and' causes the policy to report a failure for that policy. Note that both conditions check different resource_types. Combining two conditions for the same resource_types works as expected.

## Expected behavior
The policy does not report a failure for main.tf when executing `checkov -f .\main.tf --external-checks-dir .\checkov-custom-policies\ --check SAMPLE*`.

## Observed behavior
The policy reports a failure for main.tf. The output is as follows:
```
Check: SAMPLE_TERRAFORM_1: "Illustrate broken/counterintuitive 'and' semantics"
        FAILED for resource: docker_container.nginx
        File: /main.tf:17-24

                17 | resource "docker_container" "nginx" {
                18 |   image = docker_image.nginx.latest
                19 |   name  = "tutorial"
                20 |   ports {
                21 |     internal = 80
                22 |     external = 8000
                23 |   }
                24 | }
```
## Steps to reproduce
Here's the minimal example.
checkov-custom-policies\custom-policy.yml:
```
---
metadata:
  name: "Illustrate broken/counterintuitive 'and' semantics"
  id: "SAMPLE_TERRAFORM_1"
  category: "CONVENTION"
definition:
  and:
    - cond_type: attribute
      resource_types:
        - docker_image
      attribute: name
      operator: equals
      value: "nginx:latest"
    - cond_type: attribute
      resource_types:
        - docker_container
      attribute: name
      operator: equals
      value: "tutorial"
```

main.tf (taken from docker tutorial):
```
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
      version = "~> 2.13.0"
    }
  }
}

provider "docker" {}

resource "docker_image" "nginx" {
  name         = "nginx:latest"
  keep_locally = false
}

resource "docker_container" "nginx" {
  image = docker_image.nginx.latest
  name  = "tutorial"
  ports {
    internal = 80
    external = 8000
  }
}
```

I'm using Windows 10, python 3.10.5 and checkov 2.2.257.
