### ISSUE TITLE
CKV_AWS_118 Fails With MonitoringInterval Integer Value

### ISSUE THREAD

**Issue by enzowritescode** [bridgecrewio/checkov#4242]
**Describe the issue**
CKV_AWS_118 fails if the `MonitoringInterval` value is not wrapped in double quotes despite the fact that the source code says it should allow ints and strings.

**Examples**
```
RDSinstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !Ref DbType
      DBInstanceIdentifier: !Sub ${AppName}-${EnvironmentName}
      DBParameterGroupName: !Ref DbParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: aurora-mysql
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RdsMonitoringRole.Arn
      PubliclyAccessible: 'false'
```

**Version (please complete the following information):**
 - Checkov Version 2.2.255 (CLI)

**Additional context**
The test failure happens with the CLI and also using a GItHub Action `bridgecrewio/checkov-action@master`

![Screenshot 2023-01-13 at 8 52 02 AM](https://user-images.githubusercontent.com/1328683/212362109-7c0d3751-08e4-4428-9120-37edf3e85f88.png)
