### ISSUE TITLE
Check: CKV_AZURE_190: Ensure that Storage blobs restrict public access, FAILED for resource: azurerm_storage_account.functions_app_storage_account

### ISSUE THREAD

**Issue by praveensuk** [bridgecrewio/checkov#4307]
**Describe the issue**
Check: CKV_AZURE_190: "Ensure that Storage blobs restrict public access" FAILED for resource: azurerm_storage_account.functions_app_storage_account
I am getting the above mentioned error after fixing the check. Here is my code

**Examples**
```
resource "azurerm_storage_account" "functions_app_storage_account" {
  count                     = var.environment == "dev" || var.environment == "prod" ? 1 : 0
  name                      = var.environment == "dev" ? join("", [var.project, "func", "nonprod"]) : join("", [var.project, "func", "prod"])
  resource_group_name       = azurerm_resource_group.resource_group.name
  location                  = azurerm_resource_group.resource_group.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "GRS"
  access_tier               = "Hot"
  enable_https_traffic_only = true
  is_hns_enabled            = false
  min_tls_version           = "TLS1_2"
  allow_blob_public_access  = false

  identity {
    type = "SystemAssigned"
  }

  network_rules {
    default_action             = "Deny"
    ip_rules                   = [] //To allow add ip's in var.default_ip_allow_list
    bypass                     = ["Logging", "Metrics", "AzureServices"]
    virtual_network_subnet_ids = var.environment == "dev" ? local.subnet_ids_nonprod : local.subnet_ids_prod
  }
  blob_properties {
    delete_retention_policy {
      days = 90
    }
  }
  lifecycle {
    ignore_changes = [
      network_rules[0].ip_rules
    ]
  }
}
```

**Version (please complete the following information):**
 - Checkov Version : bridgecrewio/checkov-action@v10 and tried in latest bridgecrewio/checkov-action@v12

**Additional context**

i was trying this in github actions.
  ```
  - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v10
      with:
        # directory with infrastructure code to scan
        directory: ./terraform
        # Run scan only on a specific check identifier (comma separated)
        # check: # optional
        # Run scan on all checks but a specific check identifier (comma separated)
        skip_check: CKV_AZURE_33,CKV_AZURE_140,CKV_AZURE_132,CKV_AZURE_112
        # display only failed checks
        # quiet: # optional
        # do not return an error code if there are failed checks
        # soft_fail: # optional
        # run only on a specific infrastructure
        # framework: # optional
        # comma separated list of external (custom) checks directories
        # external_checks_dirs: # optional
        # comma separated list of external (custom) checks repositories
        # external_checks_repos: # optional
        # The format of the output. cli, json, junitxml, github_failed_only
        # output_format: json
        # download external terraform modules from public git repositories and terraform registry:true, false
        # download_external_modules: # optional
        # log level
        # log_level: # optional, default is WARNING
```
