### ISSUE TITLE
CKV2_K8S_6: Cannot skip test

### ISSUE THREAD

**Issue by ScottKinder** [bridgecrewio/checkov#4332]
I am receiving a failure on `CKV2_K8S_6`, and I am unable to skip the test when running Checkov scans.

Here's my `Deployment` manifest where I'm seeing the issue. Checkov is successfully skipping `CKV_K8S_38`.

```
annotations:
    "checkov.io/skip1": "CKV_K8S_38=service account is necessary for S3 export bucket upload permissions"
    "checkov.io/skip2": "CKV2_K8S_6=on roadmap"
```

Results when running a Checkov scan. Output has been omitted or obfuscated.

```
checkov -f deployment.yaml --framework kubernetes

...

Check: CKV2_K8S_6: "Minimize the admission of pods which lack an associated NetworkPolicy"
	FAILED for resource: Pod.default...........

...
```

**Comment by ScottKinder** [comment]
I can skip the test if I pass it as a command-line argument.

```
checkov -f deployment.yaml --framework kubernetes --skip-check CKV2_K8S_6
```

**Comment by ScottKinder** [comment]
This is occurring on Checkov version `2.2.302`.

```
checkov --version
2.2.302
```

**Comment by ScottKinder** [comment]
Here is a sanitized version of the `Deployment` on which this test cannot be skipped:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-microservice
  namespace: test
  annotations:
    "checkov.io/skip1": "CKV_K8S_14=ignored as digests are used"
    "checkov.io/skip2": "CKV_K8S_43=ignored as digests are used"
    "checkov.io/skip3": "CKV2_K8S_6=on roadmap"
  labels:
    helm.sh/chart: microservice-1.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: microservice
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservice
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-microservice
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: microservice-tmp-dir
          emptyDir: {}
      containers:
        - name: release-name
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - NET_RAW
              - ALL
            readOnlyRootFilesystem: true
            runAsUser: 12000
          image: "RECACTED"
          imagePullPolicy: Always
          volumeMounts:
            - name: microservice-tmp-dir
              mountPath: /tmp
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```
