### ISSUE TITLE
Ability to write custom checks on provider block in Yaml

### ISSUE THREAD

**Issue by rannaladasu** [bridgecrewio/checkov#4341]
While checkov allows us to write custom checks involving various resource types in terraform, am not sure if there is a way to add custom checks for the provider block in terraform. The default check that runs for the provider block does scan for secrets, however, am looking to check if the provider block has a default_tags definition. The reason I need to check this is that while we can write custom checks to check tags for all supported resource types, we would need to avoid having to repeat the tags for individual resources and use the default_tags feature in terraform to apply the same set of tags to all resources, then there should be a way to check this and If defined then not check the individual resource types for the tags.

```hcl
provider "aws" {
  profile = "default"
  region = var.aws_region
  default_tags {
    tags = {
      Environment = "Test"
      Name        = "Provider Tag"
    }
  }
}
```

```yaml
scope:
  provider: aws
definition:
  and:
   - cond_type: "attribute"
     resource_types:
       - "provider.aws"
     attribute: "default_tags"
     operator: exists
```
