### ISSUE TITLE
Add a check for AWS::Lambda::Permission

### ISSUE THREAD

**Issue by andyloughran** [bridgecrewio/checkov#4346]
**Describe the issue**

When adding a permission to a lambda in CFN, it's possible to set up the permission by service, (e.g. API Gateway) https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html

For AWS services, the principal is a domain-style identifier defined by the service, like s3.amazonaws.com or sns.amazonaws.com. For AWS services, you can also specify the ARN of the associated resource as the SourceArn. If you grant permission to a service principal without specifying the source, other accounts could potentially configure resources in their account to invoke your Lambda function.

**Examples**

This is an example of an insecure permission:

```
ExampleFunctionPermission:
  Type: AWS::Lambda::Permission
  Properties:
    Action: lambda:InvokeFunction
    FunctionName: !GetAtt ExampleFunction.Arn
    Principal: apigateway.amazonaws.com
```

Checkov could ensure if the Principal includes 'amazonaws.com', that it also defines either a SourceAccount or a SourceArn property.

**Version (please complete the following information):**
 - Checkov Version 2.2.300

**Additional context**

There are other permissions within this CFN resource that could also probably be checked with checkov, however this was just the first that I've identified as being low-hanging fruit, and codifying the advice on the documentation.
