### ISSUE TITLE
eksctl configuration file support

### ISSUE THREAD

**Issue by nicholasmhughes** [bridgecrewio/checkov#4461]
**Describe the issue**
It would be great if there was support for eksctl configuration files to ensure that EKS clusters are being created per security best practices. Any item flagged in Terraform AWS EKS resources would be in-scope for eksctl. I haven't looked into the complexity of contributing a language to support eksctl, but I'd be happy to entertain it if someone could point me at a good example or chat with me for a bit about minimum requirements for a PR.

**Example Value**

Lack of the `secretsEncryption` key indicates an insecure configuration.

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# secretsEncryption:
#   keyARN: "arn:aws:kms:<region>:<account>:key/<key>"
```
