### ISSUE TITLE
Some ansible playbooks cause checkov crash

### ISSUE THREAD

**Issue by Igorgro** [bridgecrewio/checkov#4503]
Continuation of #4471 

The following playbook (probably because of missing tasks) still causes checkov to crash:

```yaml
- name: Sample play
  hosts:
    - test
  roles:
    - role: somerole
```

cc @gruebel
