### ISSUE TITLE
[HELM] allow checkov skip for a custom part of a resource without annotations

### ISSUE THREAD

**Issue by lerminou** [bridgecrewio/checkov#4541]
**Describe the issue**
Based on https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html#kubernetes-example
We can skip a single policy for a specific file.

On the Helm format, we can only disable the policy for the whole file in a annotation
https://github.com/bridgecrewio/checkov/blob/main/checkov/helm/runner.py#L363

It may be usefull to use the comment format like in other langages to allow a more specific skip

For example, a initcontainer may run as root, but not the application container
Actually, we can only disable the check globally for the deployment

**Example Value**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}-daphne
  annotations:
    checkov.io/skip1: CKV_K8S_37=Init Container must run as root <<<<<=======
    checkov.io/skip2: CKV_K8S_28=Init Container must run as root <<<<<=======
spec:
  template:
    spec:
      initContainers:
        ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
        - name: ulimit
          image: bitnami/bitnami-shell:11-debian-11-r76
          command:
            - /bin/bash
            - -ec
            - |
              {{- include "app.ulimitIfLess" (dict "key" "H" "value" "500000") | nindent 14 }}
              {{- include "app.ulimitIfLess" (dict "key" "S" "value" "100000") | nindent 14 }}
          securityContext:
            #checkov:skip=CKV_K8S_37 Init Container must run as root    <<<<<<======== need this
            privileged: true
            runAsUser: 0
      containers:
        - name: app-static
          image: 'app:1.0.0'
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - NET_RAW
                - ALL

```
