### ISSUE TITLE
custom checkov policy is not working

### ISSUE THREAD

**Issue by bharathr0209** [bridgecrewio/checkov#4544]
**Describe the issue**

I have using the first custom policy example provided here https://www.checkov.io/3.Custom%20Policies/Examples.html to test executing checkov run the custom policy
```yaml
---
metadata:
  name: "Check that all resources are tagged with the key - env"
  id: "CKV2_AWS_1"
  category: "GENERAL_SECURITY"
scope:
  provider: aws
definition:
  cond_type: "attribute"
  resource_types: "all"
  attribute: "tags.env"
  operator: "exists"
```

**Examples**
Running the following command 
checkov -d . --framework terraform --check CKV2_AWS_1 --external-checks-dir buildspec/customcheck --skip-check $CHECK

CHECK in the above command is CHECK=`paste -d, -s buildspec/checks.config`
and checks.config contains a list of items (like CKV_AWS_73, CKV_AWS_53 etc) to be skipped
I am mentioning here just to give the complete context

**Version (please complete the following information):**

2.3.34

**Additional context**
Is there something wrong with the command? or what I am missing here?

**Comment by gruebel** [comment]
hey @bharathr0209 thanks for reaching out.

You can't use the same check IDs we use, ours will override yours. It is recommended to use your own prefix or suffix, something which is unique for you.

```yaml
metadata:
  name: "Check that all resources are tagged with the key - env"
  id: "EXAMPLE_AWS_1"
  category: "GENERAL_SECURITY"
```
