### ISSUE TITLE
Several Kubernetes Checks crash when command attribute is omitted

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [bridgecrewio/checkov#4619]
**Describe the issue**
Several (dozens) of Kubernetes checks will crash with a Python dict `KeyError` in (valid) scenarios where `command` attribute is present, but `null` (in JSON), i.e. `None` in Python.

For example:
- https://github.com/bridgecrewio/checkov/blob/main/checkov/kubernetes/checks/resource/k8s/ApiServerSecurityContextDenyPlugin.py#L16
- https://github.com/bridgecrewio/checkov/blob/main/checkov/kubernetes/checks/resource/k8s/ApiServerAnonymousAuth.py#L16
- ..... many more

**Potential fix**

```
if conf.get("command") is not None:
```
instead of
```
if "command" in conf:
```

**Examples**

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
#### command exists in `dict`, but with value `None`
  - command:    # This is the culprit
    image: gcr.io/google_containers/kube-apiserver-amd64:v1.6.0
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 6443
        scheme: HTTPS
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /etc/kubernetes/
      name: k8s
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: certs
    - mountPath: /etc/pki
      name: pki
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: k8s
  - hostPath:
      path: /etc/ssl/certs
    name: certs
  - hostPath:
      path: /etc/pki
    name: pki
```

**Version (please complete the following information):**
 - All version, including latest (`2.3.59`)
