### ISSUE TITLE
Support for helm charts

### ISSUE THREAD

**Issue by josesimon** [bridgecrewio/checkov#465]
Hello,

I do not receive any output while scanning kubernetes manifests in helm format.

Is it supported?

Thank you

**Comment by jonjozwiak** [comment]
Today we don't render helm charts, but it is a feature we want to add.  Today you can use 'helm template' to render a template and then run checkov against the output.  

To help us develop the helm scanning feature I have a few questions: 
* Are you using your own authored charts or one of the public chart repositories? 
* Where do you place your values that you pass into a template?  Are these just local or in a repo?  And are they stored with a chart or separate?  
* Are you using a CI/CD tool for deployment of charts to kubernetes?  Or just local helm commands?  

Thanks!

**Comment by maheshkalagotla254** [comment]
Any update on this,we are also looking for checkov scan for helm charts.

**Comment by nicolasbelanger** [comment]
Hey @jonjozwiak.  We're also following this issue and be interested in a more native support of helm charts (than let's say helm template).

> * Are you using your own authored charts or one of the public chart repositories?

  I suppose it should support both.  We have a mixture of public and private charts.

> * Where do you place your values that you pass into a template?  Are these just local or in a repo?  And are they stored with a chart or separate?

  There usually is a default values.yaml file within the chart, but what matters most is the rendered templates with possibly a custom values.yaml (or even a bunch of --set).  Generally speaking, there should be a way to provide an alternate value file/path at the very least.

> * Are you using a CI/CD tool for deployment of charts to kubernetes?  Or just local helm commands?

  There should be no difference IMHO.  Integration with a local pre-commit is great, but the ability to run those tests on the CI is as important if not more.

My 2 cents here... ready for feed-back!

**Comment by mteodori** [comment]
I am using the following local pre-commit hook with the assumption that in my repo I have a directory called helm and each subdir is an helm chart:
```yaml
- id: checkov-helm
  name: Checkov - Helm check
  entry: bash -c 'find helm -mindepth 1 -maxdepth 1 -type d | xargs -t -n1 -I% bash -c "helm template % > %.yaml && checkov -f %.yaml" || true' --
  language: system
  pass_filenames: false

```
