### ISSUE TITLE
YAML connection not working on terraform plan

### ISSUE THREAD

**Issue by arkaprava-jana** [bridgecrewio/checkov#4695]
[plan2.json.zip](https://github.com/bridgecrewio/checkov/files/11002241/plan2.json.zip)

Connection check between aws_s3_bucket and aws_s3_bucket_policy does not work.

Plan. attached.

TF Code:

resource "aws_s3_bucket" "example" {
  bucket = "my-tf-test-bucket"
}

resource "aws_s3_bucket_policy" "allow_access_from_another_account" {
  bucket = aws_s3_bucket.example.id
  policy = data.aws_iam_policy_document.allow_access_from_another_account.json
}

**Comment by rotemavni** [comment]
Thank you @arkaprava-jana for reporting this issue. We will take a look and will update once we have a fix in place.

**Comment by gruebel** [comment]
hey @arkaprava-jana,
I tested with following custom policy and it passed
```yaml
metadata:
  name: "Ensure S3 bucket has a bucket policy defined"
  id: CUSTOM_3
  category: "GENERAL_SECURITY"
definition:
  and:
    - cond_type: filter
      attribute: resource_type
      operator: within
      value:
        - aws_s3_bucket
    - cond_type: connection
      resource_types:
        - aws_s3_bucket
      connected_resource_types:
        - aws_s3_bucket_policy
      operator: exists
```
