### ISSUE TITLE
`length_*` YAML Operators

### ISSUE THREAD

**Issue by bschwab003** [bridgecrewio/checkov#4751]
I believe I have found a potential "gap" in the "Length" YAML operators/Attribute Resolvers. I am not calling it a bug, because I believe it could be considered working correctly or not depending on the intent of the user.

In the example below, I am trying to ensure the user is specifying 2 origins with an `aws_cloudfront_distribution`.

I started with my positive test which worked as I expected. But when I did my negative test (specifying only 1 origin), the test still passed which was confusing.

So I dove in further and here is what I found...

# Example 1: Working as intended?

Policy YAML:

```yaml
metadata:
  id: "CF_YAML_001"
  name: "Test"
  category: "NETWORKING"
definition:
  and:
    - cond_type: attribute
      attribute: origin
      operator: length_equals
      value: 2
      resource_types:
        - aws_cloudfront_distribution
```

Terraform:

```
resource "aws_cloudfront_distribution" "s3_distribution" {

    origin {
        domain_name = aws_s3_bucket.b.bucket_regional_domain_name
        origin_id = "123"
    }
    origin {
        domain_name = aws_s3_bucket.b.bucket_regional_domain_name
        origin_id = "123"
    }

    ....
}            
```

The `LengthEqualsAttributeSolver` evaluates the following for length:

```
[
    {'domain_name': 'aws_s3_bucket.b.bucket_regional_domain_name', 'origin_id': '123'}, 
    {'domain_name': 'aws_s3_bucket.b.bucket_regional_domain_name', 'origin_id': '123'}
]
```

It is a `list` and has a length of 2. Validation passes.

# Example 2: Not working as intended?

Policy YAML (remains the same):

```yaml
metadata:
  id: "CF_YAML_001"
  name: "Test"
  category: "NETWORKING"
definition:
  and:
    - cond_type: attribute
      attribute: origin
      operator: length_equals
      value: 2
      resource_types:
        - aws_cloudfront_distribution
```

Terraform (only one origin):

```
resource "aws_cloudfront_distribution" "s3_distribution" {

    origin {
        domain_name = aws_s3_bucket.b.bucket_regional_domain_name
        origin_id = "123"
    }
```

The `LengthEqualsAttributeSolver` evaluates the following for length:

```
{
    'domain_name': 'aws_s3_bucket.b.bucket_regional_domain_name', 
    'origin_id': '123'
}
```

It is a `dict` and has a length of 2. Validation passes.

# Conclusion

I am probably "misusing" the `length_equals` operator beacuse I feel like the intent of these "Length" Attribute Resolvers are for something like the following scenario:

Policy YAML:

````yaml
```yaml
metadata:
  id: "S3_YAML_001"
  name: "Test"
  category: "NETWORKING"
definition:
  and:
    - cond_type: attribute
      attribute: allowed_methods
      operator: length_equals
      value: 2
      resource_types:
        - aws_s3_bucket
```
````

Terraform:

```
resource "aws_s3_bucket" "b" {
  bucket = "s3-website-test.hashicorp.com"
  acl    = "public-read"

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "POST"]
    allowed_origins = ["https://s3-website-test.hashicorp.com"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3000
  }
}
```

My suggestion would be to submit a pull request for new operators for my use case ? But interested to hearing some feedback/guidance.

**Comment by gruebel** [comment]
hey @bschwab003 thanks for reaching out.

You are right it was intended for determine the length of a string or an array, not for Terraform blocks. What kind of operator do you want to contribute exactly?

**Comment by bschwab003** [comment]
Thanks for timely response!  

I have not dove too much further into a potential PR, just yet.  I wanted to see the response first, but here are my initial thoughts...  

**At a Minimum..**
If the intended target for the existing "length" operators (`length_equals`, `length_less_than`, etc.) is truly just `strings` and `arrays` then they should return `UNKNOWN` instead of `PASSED` if they evaluate an iterable that is of type `dict` to avoid confusion or potential "misuse."  Update documentation accordingly to make it clearer for the next person.

As for a potential "fix"...

**Option 1**
Update the existing "length" operators (`length_equals`, `length_less_than`, etc.) to evaluate `dict` objects as a length of 1 and continue to evaluate `str` and `list`objects as usual.  For `dict` objects, users are typically more concerned about the existence/nonexistence of keys and their values, not necessarily the "length" (i.e. number of keys) in the `dict` object.  Don't love this because it still leaves room for interpretation and makes some assumptions. 

**Option 2**
Keep the existing operators and add a new `cond_type` called `block` that could be used to perform slightly different evaluation logic akin to what is proposed in Option 1.   I am sure there could be other use cases for evaluating `blocks` as a whole versus just `attributes.`.  

I am open to other options/suggestions from someone who is closer to the codebase :).  But maybe these would provoke some discussion/consideration of potential options and I am happy to help pursue a PR that is aligned with the primary maintainer's vision/strategy.

**Comment by gruebel** [comment]
Personally I think Option 1 sounds actually good, as said a user doesn't need a length of `dict`, typically it is for a `str` or `list`.
I'm curious about Option 2, what exactly do you have in mind?
I also found a possible workaround solution for your case, but I'm interested in having a more straight forward one 🙂 

```yaml
metadata:
  id: "S3_YAML_001"
  name: "Test"
  category: "NETWORKING"
definition:
  and:
    - cond_type: "attribute"
      resource_types:
        - "aws_cloudfront_distribution"
      attribute: "origin.0"
      operator: "exists"
    - cond_type: "attribute"
      resource_types:
        - "aws_cloudfront_distribution"
      attribute: "origin"
      operator: "length_equals"
      value: 2
```
The `origin.0` attribute reference guarantees it is a `list` and not a `dict`
