### ISSUE TITLE
Handling multiple instances of the same resource.  

### ISSUE THREAD

**Issue by bschwab003** [bridgecrewio/checkov#4818]
I idenfied a scenario that I am afraid checkov cannot address. I am hoping I am missing something or at least get acknowledgment and identify an area where checkov could improve in the future.

### Desired Policy:

Ensure a DynamoDB Table has an autoscaling policy for both read and write capacity units.

### The Terraform:

To accomplish this in Terraform, we would need two `aws_appautoscaling_target` resources - one for read and another for write, along with two `aws_appautoscaling_policy` resources, but that is less relevant to the problem at hand.

The Terraform would look something like this...

```
resource "aws_dynamodb_table" "basic-dynamodb-table" {
  name           = "GameScores"
  billing_mode   = "PROVISIONED"
  read_capacity  = 20
  write_capacity = 20
  hash_key       = "UserId"
  range_key      = "GameTitle"

...
}

resource "aws_appautoscaling_target" "dynamodb_table_read_target" {
  max_capacity       = 100
  min_capacity       = 5
  resource_id        = aws_dynamodb_table.basic-dynamodb-table.id
  scalable_dimension = "dynamodb:table:ReadCapacityUnits"
  service_namespace  = "dynamodb"
}

resource "aws_appautoscaling_target" "dynamodb_table_write_target" {
  max_capacity       = 100
  min_capacity       = 5
  resource_id        = aws_dynamodb_table.basic-dynamodb-table.id
  scalable_dimension = "dynamodb:table:WriteCapacityUnits"
  service_namespace  = "dynamodb"
}

resource "aws_appautoscaling_policy" "dynamodb_table_read_policy" {
  name               = "DynamoDBReadCapacityUtilization:${aws_appautoscaling_target.dynamodb_table_read_target.resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.dynamodb_table_read_target.resource_id
  scalable_dimension = aws_appautoscaling_target.dynamodb_table_read_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.dynamodb_table_read_target.service_namespace
}

resource "aws_appautoscaling_policy" "dynamodb_table_write_policy" {
  name               = "DynamoDBReadCapacityUtilization:${aws_appautoscaling_target.dynamodb_table_write_target.resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.dynamodb_table_write_target.resource_id
  scalable_dimension = aws_appautoscaling_target.dynamodb_table_write_target.scalable_dimension
  service_namespace  = aws_appautoscaling_target.dynamodb_table_write_target.service_namespace
}
```

### The Problem

This is my YAML policy thus far.

```yaml
definition:
  or:
    - and:
      - cond_type: "attribute"
        resource_types: "aws_dynamodb_table"
        attribute: "billing_mode"
        operator: "equals"
        value: "PROVISIONED"
      - cond_type: "connection"
        resource_types:
          - "aws_dynamodb_table"
        connected_resource_types:
          - "aws_appautoscaling_target"
        operator: "exists"
      - cond_type: "connection"
        resource_types:
          - "aws_appautoscaling_target"
        connected_resource_types:
          - "aws_appautoscaling_policy"
        operator: "exists"
    - cond_type: "attribute"
      resource_types: "aws_dynamodb_table"
      attribute: "billing_mode"
      operator: "equals"
      value: "PAY_PER_REQUEST"
metadata:
  category: GENERAL_SECURITY
  id: TEST_YAML_POLICY
  name: 'Test YAML Policy'
```

It is successful so far in ensuring that a DynamoDB table has an attached auto scaling policy (the connection is there).  Plus, ignoring the check when `billing_mode` is `PAY_PER_REQUEST`.  

However, this is where my problem begins.

From what I have gathered, checkov more or less looks at each **_instance_** of a resource in isolation and applies the policy check to that instance even if the Terraform includes multiple instances of the same resource. Therefore, it is impossible (at least at this point) to actually perform my check because one of the two resources will fail.

The `aws_appautoscaling_target.dynamodb_table_write_target` resource will not pass validation when the `scalable_dimension = "dynamodb:table:ReadCapacityUnits"` condition is run and the `aws_appautoscaling_target.dynamodb_table_read_target` resource will not pass validation when the `scalable_dimension = "dynamodb:table:WriteCapacityUnits"` condition is run.

**Comment by gruebel** [comment]
hey @bschwab003 

There is actually a way to achieve it, but it seems like it is a hidden gem 😄 we have an operator named `one_exists`, which can be used for connection checks. You also need to use the filter block to only flag the resource you are actually interested in, in this example `aws_dynamodb_table`, otherwise all other resources will fail the check.

Long story short, here is the policy you are looking for

```yaml
  or:
    - and:
      - cond_type: filter
        attribute: resource_type
        value:
          - aws_dynamodb_table
        operator: within
      - and:
        - cond_type: "attribute"
          resource_types: "aws_dynamodb_table"
          attribute: "billing_mode"
          operator: "equals"
          value: "PROVISIONED"
        - cond_type: "connection"
          resource_types:
            - "aws_dynamodb_table"
          connected_resource_types:
            - "aws_appautoscaling_target"
          operator: "one_exists"
        - cond_type: "connection"
          resource_types:
            - "aws_appautoscaling_target"
          connected_resource_types:
            - "aws_appautoscaling_policy"
          operator: "exists"
        - cond_type: "attribute"
          resource_types: "aws_appautoscaling_target"
          attribute: "scalable_dimension"
          operator: "equals"
          value: "dynamodb:table:ReadCapacityUnits"
      - and:
        - cond_type: "attribute"
          resource_types: "aws_dynamodb_table"
          attribute: "billing_mode"
          operator: "equals"
          value: "PROVISIONED"
        - cond_type: "connection"
          resource_types:
            - "aws_dynamodb_table"
          connected_resource_types:
            - "aws_appautoscaling_target"
          operator: "one_exists"
        - cond_type: "connection"
          resource_types:
            - "aws_appautoscaling_target"
          connected_resource_types:
            - "aws_appautoscaling_policy"
          operator: "exists"
        - cond_type: "attribute"
          resource_types: "aws_appautoscaling_target"
          attribute: "scalable_dimension"
          operator: "equals"
          value: "dynamodb:table:WriteCapacityUnits"
    - cond_type: "attribute"
      resource_types: "aws_dynamodb_table"
      attribute: "billing_mode"
      operator: "equals"
```
