### ISSUE TITLE
Potential bug in `BaseAttributeSolver`

### ISSUE THREAD

**Issue by bschwab003** [bridgecrewio/checkov#4833]
## Desired Policy:

I am trying to write a YAML policy to ensure that every volume of an AWS Launch Template is encrypted.

## Observation/Finding:

I had no issues implementing this as a YAML policy when there was only a single volume. Terraform would look something like the following.

```
resource "aws_launch_template" "foo" {

  name = "foo"

  block_device_mappings {
    device_name = "/dev/sdf"

    ebs {
      volume_size = 20
      encrypted = true
    }
  }
  ...
}
```

However, I have had difficulty implementing a YAML policy when there was more than one volume. Terraform would look something like the following. Note, this would be a negative test because only 1 of the 2 blocks are encrypted.  The resource should fail since the second volume is not encrypted.

```
resource "aws_launch_template" "foo" {

  name = "foo"

  block_device_mappings {
    device_name = "/dev/sdf"

    ebs {
      volume_size = 20
      encrypted = true
    }
  }

  block_device_mappings {
    device_name = "/dev/sdf2"

    ebs {
      volume_size = 20
      encrypted = false
    }
  }
}
```

I have been unable to get checkov to fail with the above configuration using the following YAML policy:

```yaml
definition:
  and:
    - attribute: resource_type
      cond_type: filter
      operator: within
      value:
        - aws_launch_template
    - attribute: block_device_mappings
      cond_type: attribute
      operator: exists
      resource_types:
        - aws_launch_template
    - attribute: 'block_device_mappings.*.ebs.encrypted'
      cond_type: attribute
      operator: is_true
      resource_types:
       - aws_launch_template
metadata:
  category: GENERAL_SECURITY
  id: SP-AWS-EC2001-EBS-VOLUME-ENCRYPTION-AT-REST
  name: EBS default encryption should be enabled
```

I believe I have identified why. It sits within `BaseAttributeSolver` class, specifically the `get_operation` method, where checkov is using the `any()` function to evaluate the results of the `_get_operation` method of each of the `filtered_attribute_matches`.

Should checkov be using the `all()` function here instead? I would expect all flavors of `block_device_mappings.*.ebs.encrypted` to be `True`, not just one.

In fact, checkov is using the `all()` function in the same situation a few lines up when the `self.is_jsonpath_check` condition is met.

```python
if attribute_matches:
	if self.is_jsonpath_check:
	    if self.resource_type_pred(vertex, self.resource_types) and all(
	            self._get_operation(vertex=vertex, attribute=attr) for attr in filtered_attribute_matches):
	        return True if len(attribute_matches) == len(filtered_attribute_matches) else None
	    return False

	if self.resource_type_pred(vertex, self.resource_types) and any(
	        self._get_operation(vertex=vertex, attribute=attr) for attr in filtered_attribute_matches):
	    return True
	return False if len(attribute_matches) == len(filtered_attribute_matches) else None
```

[Link to specific line](https://github.com/bridgecrewio/checkov/blob/d3301ae913cb68aa3dbb4535cc576ff8b41d5e5a/checkov/common/checks_infra/solvers/attribute_solvers/base_attribute_solver.py#L114)

**Comment by gruebel** [comment]
hey @bschwab003 
I think this a bit historical and hard to change, because current policies leverage this behaviour, so it would a breaking change to fix it. The logic itself is as you found to look for one valid block inside the list.
For your use-case we have a different operator `not` and it would look like this
```yaml
definition:
  not:
    - cond_type: "attribute"
      resource_types:
        - "aws_launch_template"
      attribute: "block_device_mappings.*.ebs.encrypted"
      operator: "equals"
      value: "false"
```

**Comment by bschwab003** [comment]
@gruebel Thank you for the suggestion.  Tested your YAML and it works for me use case.

**Comment by bschwab003** [comment]
@gruebel I have reopened this to ask a follow up.  So your suggestion did fix that particular check/condition.  However, I am still struggling to catch the scenario where the `encrypted` attribute of the `block_device_mappings` is missing all together.  This is more or less the same as the attribute existing with a value of `false`).

See the following Terraform.  I would expect this to fail because the second volume does not even have the `encrypted` attribute defined at all.

```
resource "aws_launch_template" "z" {

  name = "foo"

  block_device_mappings {
    device_name = "/dev/xda"

    ebs {
      volume_size = 20
      encrypted = true
    }
  }

  block_device_mappings {
    device_name = "/dev/sdf"

    ebs {
      volume_size = 20
    }
  }
}
```

My policy is as follows:
```
definition:
  and:
    - attribute: resource_type
      cond_type: filter
      operator: within
      value:
        - aws_launch_template
    - attribute: block_device_mappings.*.ebs.encrypted
      cond_type: attribute
      operator: exists
      resource_types:
        - aws_launch_template
metadata:
  category: GENERAL_SECURITY
  id: PWC_AWS-EC2-001-EBS-VOLUME-ENCRYPTION-AT-REST-LAUNCH-TEMP
  name: aws-ec2-001-ebs-volume-encryption-at-rest-launch-temp

```
This is not working (the resources passes validation).  I have tracked down why.  Since `encrypted` is not defined, the `get_attribute_matches` method of the `BaseAttributeSolver` only passes `block_device_mappings.0.ebs.encrypted` to the `ExistsAttributeSolver` because `block_device_mappings.1.ebs`does not match the regex `'^(block_device_mappings)[.][\\d]+[.](ebs)[.](encrypted)$'`.

Again, I am likely misusing the `exists` operator and there is hopefully another way of doing this that I am not privy to. 

Sorry for peppering with so many questions, but it can be a challenge writing these policies :-(

**Comment by gruebel** [comment]
I had an example in the past to make it work, but after a bit of tinkering I was able to further simplify it, at least I hope it is simpler than before 😄 

```yaml
definition:
  cond_type: "attribute"
  resource_types:
    - "aws_launch_template"
  attribute: "block_device_mappings[?(@.ebs.encrypted == 'false' || !@.ebs.encrypted)]"
  operator: "jsonpath_not_exists"
```

it is also possible to mix it with the example I gave you before, but most crucial part is the negated existence check `!@.ebs.encrypted`. One thing, which is also important, but I think it is a bug of the negation `!` it needs to be on the right side of the `||` statement.

The left side of the `||` statement is identical to the previous one I posted, so you can choose, which you prefer.
