### ISSUE TITLE
ansible checks not able to read ansible interpolations

### ISSUE THREAD

**Issue by camaeel** [bridgecrewio/checkov#4836]
**Describe the issue**
I have ansible step like this:
```
- name: get gpg key
  ansible.builtin.get_url:
    url: "{{ jenkins_key_location }}"
    dest: "/etc/apt/trusted.gpg.d/{{ jenkins_key_id }}.asc"
    mode: 0644
```
and jenkins_key_location is defined as `https://breaking.checkov.validation/ansible`

It raises Check: CKV2_ANSIBLE_2: "Ensure that HTTPS url is used with get_url"

Looks like the CKV2_ANSIBLE_* checks were introduced too early, as they are not able to understand neither ansible's variable interpolations nor skip functionality. 

**Examples**
Look into Description above

**Version (please complete the following information):**
Docker image: checkov:2

**Additional context**
This might break a lot of correctly implemented projects and should be enabled with some feature flag like --use-alpha-ansible-support.
