### ISSUE TITLE
For output gitlab_sast the severity is not correctly reporting

### ISSUE THREAD

**Issue by rezen** [bridgecrewio/checkov#4888]
Using `bridgecrew/checkov:2.3.160` and report output is `-o gitlab_sast` it looks like the issue severity is not getting parsed correctly. I'd expect the severity to be **Low** in the sample below but instead it is **Unknown**

**Sample**  
```json
 {
 	"id": "ad5108bf-c7d4-4a1a-87cf-0b6d3711b542",
 	"identifiers": [{
 		"name": "CKV_AWS_115",
 		"type": "checkov",
 		"value": "CKV_AWS_115",
 		"url": "https://docs.bridgecrew.io/docs/ensure-that-aws-lambda-function-is-configured-for-function-level-concurrent-execution-limit"
 	}],
 	"location": {
 		"file": "terraform/modules/******/lambda.tf",
 		"start_line": 8,
 		"end_line": 27
 	},
 	"name": "Ensure that AWS Lambda function is configured for function-level concurrent execution limit",
 	"description": "Further info can be found https://docs.bridgecrew.io/docs/ensure-that-aws-lambda-function-is-configured-for-function-level-concurrent-execution-limit",
 	"severity": "Unknown",
 	"solution": "Further info can be found https://docs.bridgecrew.io/docs/ensure-that-aws-lambda-function-is-configured-for-function-level-concurrent-execution-limit",
 	"links": [{
 		"url": "https://docs.bridgecrew.io/docs/ensure-that-aws-lambda-function-is-configured-for-function-level-concurrent-execution-limit"
 	}]
 }
```

**Comment by gruebel** [comment]
hey @rezen thanks for reaching out.

Are you using `checkov` with an API key or not?

**Comment by rezen** [comment]
I am not, is that the important detail I'm missing? (Below is the gitlab-ci job for reference)

```yaml
gitlab:checkov:
  stage: test
  allow_failure: true
  image:
    name: bridgecrew/checkov:2.3.160
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - checkov --quiet -d ./terraform -o gitlab_sast | tee gitlab_sast.json
  artifacts:
    reports:
      sast: "gitlab_sast.json"
    paths:
      - "gitlab_sast.json"
```
