### ISSUE TITLE
Missing edges when using external modules

### ISSUE THREAD

**Issue by leobadia** [bridgecrewio/checkov#4940]
**Describe the issue**
Please explain what is missing or malfunctioning in the graph (creation or querying).
Also detail what is the expected behavior for this use case.

I created a policy for checking every aws_s3_bucket has a aws_s3_bucket_lifecycle_configuration related. It works well when defining resources at root module or using local modules, but when it comes to an external module the policy is failing although 
terraform plan shows a connection between resources.
I've tried to debug the problem and it seems like the graph is not generating the edges between resources which are of an external module. Edges property of TerraformLocalGraph always turn out to be in an empty array.
I expect edges properties to have these connections between resources of an external module.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

I leave there the module and policy code I'm using:

```
module "s3_bucket_gitlab" {
  source                  = "terraform-aws-modules/s3-bucket/aws"
  version                 = "v3.3.0"
  acl                     = "private"
  lifecycle_rule = [{
    id                                      = "Incomplete multi-part uploads"
    status                                  = "Enabled"
    abort_incomplete_multipart_upload_days  = 8
  }]
}
```
```
metadata:
  name: "Ensure S3 bucket has LyfeCycle Configuration"
  category: "Security"
  id: "AWS_S3_LCC"

definition:
 and:
      - cond_type: "filter"
        attribute: "resource_type"
        value:
           - "aws_s3_bucket"
        operator: "within"
      - cond_type: "connection"
        resource_types:
           - "aws_s3_bucket"
        connected_resource_types:
           - "aws_s3_bucket_lifecycle_configuration"
        operator: "exists"
```
Actual behaviour:
![image](https://user-images.githubusercontent.com/75026603/233187648-7a5d18cc-2385-4796-8a6a-6835bc2c73b7.png)

Expected behaviour: Policy passed

**Desktop (please complete the following information):**
 - OS: MacOs and Linux
 - Checkov Version 2.3.165 and newer

**Additional context**
Add any other context about the problem here (e.g. code snippets).
