### ISSUE TITLE
Custom checks not used

### ISSUE THREAD

**Issue by AlexBng** [bridgecrewio/checkov#5026]
**Describe the issue**
I'm trying to create a custom check but when I run the following command it seems like my check isn't used (the check should fail)

**Command**
`checkov --external-checks-dir ./checkov_custom_checks -f test.tf`

**The custom check file**
```
metadata:
  name: "test"
  id: "CKV2_CUSTOM"
  category: "NETWORKING"
definition:
  cond_type: "attribute"
  resource_types: "test"
  attribute: "action"
  operator: "equals"
  value: "reset-both"
```

**The terraform file to check**
```
resource "test" {
    action = "default"
}
```

**The output**
`[ secrets framework ]: 100%|████████████████████|[1/1], Current File Scanned=test.tf`

**Version (please complete the following information):**
 - Checkov Version : 2.3.218
