### ISSUE TITLE
Custom policy for Kustomize

### ISSUE THREAD

**Issue by paulozava** [bridgecrewio/checkov#5094]
**Describe the issue**
I recently was testing the tool to use here at the company and brought my attention that checkov supports kustomize. The feature works well with policies I get from Brigdecrewio but when I tried to create a custom policy, I could not find a way to make it work. It there something I miss?

**Example Value**
```yaml
metadata:
  name: "Dummy Check Kubernetes"
  id: "DUMMY_K8S_001"
  category: "CONVENTION"
  guideline: "No simpsons in here"
scope:
  provider: "kubernetes"
definition:
  cond_type: "attribute"
  resource_types: "all"
  attribute: "metadata.labels.nelson"
  operator: "not_exists
```

I ran against the files:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-kustomized
  labels:
    io: there
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        io: there
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

and

```yaml
resources:
  - deploy.yaml

commonLabels:
  service_name: poc
  nelson: haha
```

Thanks for your time
