### ISSUE TITLE
Check AWS::Lambda::Function has any AWS::CloudWatch::Alarm set

### ISSUE THREAD

**Issue by pixelizedPeanut** [bridgecrewio/checkov#5100]
**Describe the issue**

I want to have a check where on every Lambda Function there is at least an alarm set for any metric. I have posted what I'm trying but I don't know what I'm doing wrong. There is no outcome and no error, even if there is no alarm set.

**Examples**

Here is what I have tried
```
---
metadata:
    name: "Check lambdas alarm"
    id: "CKV2_AWS_2"
    category: "GENERAL_SECURITY"
scope:
    provider: aws
definition:
    cond_type: "connection"
    resource_types: "AWS::Lambda::Function"
    connected_resource_types: "AWS::CloudWatch::Alarm"
    operator: "exists"
```

**Version (please complete the following information):**
 - Checkov Version : 2.3.245

**Additional context**
I am using cdk & cloudformation
