### ISSUE TITLE
Custom rule skipped issue with !Sub intrinsic function

### ISSUE THREAD

**Issue by sarbole** [bridgecrewio/checkov#5102]
**Describe the issue**
I have a rule that when there is a "*" in the resource it fails.
The rule it's being skipped when I use the sub function.  Is there a way to evaluate this wildcard? 

**Examples**
When I have in cloudformation this:

```yml
Parameters:
  Wildcard:
    Type: String
    Default: "*"
    Description: test
```

```yml
      - PolicyName: Sts_AssumeRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sts:AssumeRole
            Resource:
            - !Sub 'arn:aws:iam::${Wildcard}:role/AWSControlTowerExecution'
```

**Version (please complete the following information):**
 - Checkov Version 2.2.29
