### ISSUE TITLE
Why is not scanning the PSP Yaml file?

### ISSUE THREAD

**Issue by imvieira** [bridgecrewio/checkov#519]
Below is the entries of my PSP Yaml file. Why checkov is not returning results?

command: checkov -f psp.yaml
```

- apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
  metadata:
    annotations:
```
