### ISSUE TITLE
How can I check the configuration for terraform backend block

### ISSUE THREAD

**Issue by devopsevd** [bridgecrewio/checkov#5198]
I want to enforce a check on the backend configuration, that the value for credentials attribute should start with "#{"
Is it even possible? 
I was able to create a custom check for provider block, and that works as expected.

```hcl
terraform {
  backend "gcs" {
    bucket = "odeploy"
    prefix = "dev"
    credentials = "#{gcpcred.JsonKey | FromBase64 | JsonEscape}"
  }
}
```

The following custom check does not work
```yaml
---
metadata:
 name: "Check that the credentials in backend block starts with #{"
  id: "CKV2_GOOGLE_3"
  category: "GENERAL_SECURITY"
definition:
   cond_type: "attribute"
   resource_types: 
     - terraform.backend # other variation i have tried are "terraform", "backend.gcs"
   attribute: "backend.*.credentials" # other variations I have tried are "backend.gcs.credentials" only "credentials"
   operator: starting_with
   value: "#{"
```
