### ISSUE TITLE
Checkov docker image vulnerability scanner doesn't respect `<Dockerfile>.dockerignore` suffix

### ISSUE THREAD

**Issue by WP-LKL** [bridgecrewio/checkov#5218]
## Setup

We have multiple Dockerfiles:
```
.
├── Dockerfile
├── Dockerfile.deploy
├── Dockerfile.deploy.dockerignore
```

For workflows:
```yaml
     ...
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deploy/Dockerfile.deploy
```

### Ignore
```
# file: Dockerfile.deploy.dockerignore
#checkov:skip=CKV_DOCKER_2
#checkov:skip=CKV_DOCKER_3
### REMOVED FROM Dockerfile.deploy
*/tests/*
conftest.py
```

Another way is to complicate the Dockerfile to accomodate both, which can also help with caching the image.

## Solution

I could easily open a PR at https://github.com/bridgecrewio/checkov/blob/440ecaeb8b654b0bdd4faf9b34b4b5ada7e4660d/checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py#LL102C9-L102C13 that:
* checks the `dockerfile_path` suffix for `.dockerignore` 
* and logs `logging.info(f'Image scan ignored detected as .dockerignore file')`

_But you probably want that it is not even parsed till this point._
