### ISSUE TITLE
tags with values "true" and "false" can only be evaluated as boolean.

### ISSUE THREAD

**Issue by fcastagninizoom** [bridgecrewio/checkov#5249]
**Describe the issue**
It is not possible to test if a tag is exactly equal to the string lowercase "true" or lowercase "false".

At some point checkov assumes that the tag="true" is a boolean, and "TRUE", "tRUe", etc all mean the same.

I need to enforce that a tag has a value of a string exactly equal to lowercase "true" or "false".

I love checkov, is a fantastic tool!
This is my first time filling a ticket in this project, please forgive me if I made a mistake.

**Examples**
1 - This is my custom yaml policy
```yaml
❯ cat policies/TAG_AWS_1/policy.yaml
---
metadata:
  name: "Ensure that the resource is tagged with the key Terraform and it is the lowercase string true or false."
  id: "TAG_AWS_1"
  category: "CONVENTION"
scope:
  provider: aws
definition:
  or:
    # Test if this resource has an Terraform tag that is the lowercase string true or false
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags_all.Terraform"
      operator: within
      value:
        - "true"
        - "false"

    # Test if this resource has an Terraform tag that is the lowercase string false
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags_all.Terraform"
      operator: "equals"
      value: "false"

    # Test if this resource has an Terraform tag that is the lowercase string true
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags_all.Terraform"
      operator: "equals"
      value: "true"
```

2 - Test case mocking a terraform plan that should PASS:
```json
❯ cat tests/TAG_AWS_1/pass.json
{
    "format_version": "1.2",
    "terraform_version": "1.5.0",
    "planned_values": {
        "root_module": {
            "resources": [],
            "child_modules": [
                {
                    "resources": [
                        {
                            "address": "module.example1.aws_iam_policy.example",
                            "mode": "managed",
                            "type": "aws_iam_policy",
                            "name": "example1",
                            "values": {
                                "tags_all": {
                                    "Description": "This test case should PASS.",
                                    "Terraform": "true"
                                }
                            }
                        },
                        {
                            "address": "module.example3.aws_iam_policy.example",
                            "mode": "managed",
                            "type": "aws_iam_policy",
                            "name": "example3",
                            "values": {
                                "tags_all": {
                                    "Description": "This test case should PASS.",
                                    "Terraform": "false"
                                }
                            }
                        }
                    ],
                    "address": "module.example"
                }
            ]
        }
    }
}%
```

3 - Testing the custom policy with `pass.json`, that should **PASS** (this is working correctly)
```shell
❯ checkov --check TAG_AWS_1 --file tests/TAG_AWS_1/pass.json --external-checks-dir policies/TAG_AWS_1

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.3.301 

terraform_plan scan results:

Passed checks: 2, Failed checks: 0, Skipped checks: 0

Check: TAG_AWS_1: "Ensure that the resource is tagged with the key Terraform and it is the lowercase string true or false."
	PASSED for resource: module.example1.aws_iam_policy.example
	File: /pass.json:14-19
Check: TAG_AWS_1: "Ensure that the resource is tagged with the key Terraform and it is the lowercase string true or false."
	PASSED for resource: module.example3.aws_iam_policy.example
	File: /pass.json:26-31
```

4 - Test case mocking a terraform plan that should FAIL:
```json
❯ cat tests/TAG_AWS_1/fail.json
{
    "format_version": "1.2",
    "terraform_version": "1.5.0",
    "planned_values": {
        "root_module": {
            "resources": [],
            "child_modules": [
                {
                    "resources": [
                        {
                            "address": "module.example2.aws_iam_policy.example",
                            "mode": "managed",
                            "type": "aws_iam_policy",
                            "name": "example2",
                            "values": {
                                "tags_all": {
                                    "Description": "This test case should FAIL.",
                                    "Terraform": "True"
                                }
                            }
                        },
                        {
                            "address": "module.example4.aws_iam_policy.example",
                            "mode": "managed",
                            "type": "aws_iam_policy",
                            "name": "example4",
                            "values": {
                                "tags_all": {
                                    "Description": "This test case should FAIL.",
                                    "Terraform": "FALSE"
                                }
                            }
                        }
                    ],
                    "address": "module.example"
                }
            ]
        }
    }
}%
```

5 - Testing the custom policy with `fail.json` should **FAIL**, but it is **PASSING** the test:
```shell
❯ checkov --check TAG_AWS_1 --file tests/TAG_AWS_1/fail.json --external-checks-dir policies/TAG_AWS_1

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.3.301 

terraform_plan scan results:

Passed checks: 2, Failed checks: 0, Skipped checks: 0

Check: TAG_AWS_1: "Ensure that the resource is tagged with the key Terraform and it is the lowercase string true or false."
	PASSED for resource: module.example2.aws_iam_policy.example
	File: /fail.json:14-19
Check: TAG_AWS_1: "Ensure that the resource is tagged with the key Terraform and it is the lowercase string true or false."
	PASSED for resource: module.example4.aws_iam_policy.example
	File: /fail.json:26-31
```

**Version (please complete the following information):**
 - Checkov Version **2.3.301**
