### ISSUE TITLE
Custom Policies in Python

### ISSUE THREAD

**Issue by rusherr02** [bridgecrewio/checkov#5274]
**I have created a custom policy in Python and I need to run it against a CFT.yaml which I am unable, please help how can I run it**

**Example Value**
Policy I have created:
```python
from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck


class DemoCheck(BaseResourceCheck):

    def __init__(self, file):
        name = "Ensure any resource should not have abc"
        id = "CLUMIO_CFT_01"
        supported_resources = ['*']
        categories = [CheckCategories.GENERAL_SECURITY]
        self.file = file
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf, file):
        if 'abc' not in conf.get[file]:
            return CheckResult.PASSED

        return CheckResult.FAILED

        # if conf.get("tags",[]):
        #     env = conf["tags"][0].get("Environment",{})
        #     if env in ["Developemnt","Staging","Production"]:
        #         return CheckResult.PASSED
        # return CheckResult.FAILED


scanner = DemoCheck()
```
yaml file
```
    somePolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Sid: DescribeDynamoResources
                      Effect: Allow
                      Action:
                        - dynamodb:DescribeBackup
                        - dynamodb:DescribeContinuousBackups
                        - dynamodb:DescribeGlobalTable
                        - dynamodb:DescribeGlobalTableSettings
                        - dynamodb:DescribeTable
                        - dynamodb:DescribeTableReplicaAutoScaling
                        - dynamodb:ListBackups
                        - dynamodb:ListGlobalTables
                        - dynamodb:ListTables
                        - dynamodb:ListTagsOfResource
                      Resource: "abc"
```
basically, it's a very big yaml file I just want to create a custom policy if the resource contains 'abc' it should throw an error.
I need help with how to create and run against the same.
thanks
