### ISSUE TITLE
Improve Terraform variable rendering for map usage

### ISSUE THREAD

**Issue by Greven145** [bridgecrewio/checkov#5292]
**Describe the issue**
I have written a custom policy to check the format of names of resources. When the name of the resources is a complex local value, this policy is just ignored during code scanning. Terraform plan scanning works fine, I assume because there is string that has now been processed. In my sample below changing the attribute to location instead it evaluates as expected.

**Examples**
```yaml
---
metadata:
  name: Resource group name must follow naming convention
  id: CUSTOM_AZURE_NAMING_1
  category: CONVENTION
scope:
  provider: azure
definition:
  cond_type: attribute
  resource_types:
    - azurerm_resource_group
  attribute: name
  operator: regex_match
  value: "^[a-zA-Z]+-rg-[a-zA-Z]+-(dev|test|prod)\\d\\d$"
```

```hcl
locals {
    division = "business_division"
    product = "product"
    env_map = { development = "dev"}
    rg_name = "${local.division}-rg-${local.product}-${local.env_map[var.environment]}01"
    location = "canadacentral"
}
resource "azurerm_resource_group" "rg" {
  name     = local.rg_name
  location = local.location
}
```

Expected value:

```text
Check: CUSTOM_AZURE_NAMING_1: "Resource group name must follow naming convention"
        PASSED for resource: azurerm_resource_group.rg
        File: /main.tf:1-40
```

Actual value:

Nothing, the policy is just ignored.

**Version (please complete the following information):**
 - 2.3.312
