### ISSUE TITLE
Passing config to Checkov container in Kubernetes

### ISSUE THREAD

**Issue by alexdyas** [bridgecrewio/checkov#5323]
I am having trouble passing configuration directives to Checkov running in a container in Kubernetes. For instance I want to pass `--skip-check` directives to the container on startup, specifically to skip various Kubernetes namespaces.

I've tried adding annotations to the job, eg:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: checkov
  namespace: checkov
  annotations:
    checkov.io/skip1: default=Namespace to ignore
    checkov.io/skip2: namespace01=Namespace to ignore
    checkov.io/skip3: namespace02=Namespace to ignore
    checkov.io/skip4: namespace03=Namespace to ignore
spec:
  template:
    metadata:
      annotations:
        checkov.io/skip1: default=Namespace to ignore
        checkov.io/skip2: namespace01=Namespace to ignore
        checkov.io/skip3: namespace02=Namespace to ignore
        checkov.io/skip4: namespace03=Namespace to ignore
```
But this doesn't seem to have an effect.

Are there other ways to pass config to the container? For instance through environment variables, or a config file?

I'm using the Bridgecrew container images hosted on hub.docker.com - `bridgecrew/checkov-k8s:latest`

I've looked through the documentation but I can't see any reference to what I'm trying to do.

Thanks.

**Comment by gruebel** [comment]
hey @alexdyas thanks for reaching out.

Not every flag in `checkov` can be used via env var, but `--skip-check` can 😄 

```yaml
    env:
    - name: CKV_SKIP_CHECK
      value: "xyz"
```
