### ISSUE TITLE
Checkov unable to resolve CFN Parameters and Conditions

### ISSUE THREAD

**Issue by cbhat-ie** [bridgecrewio/checkov#5325]
**Describe the issue**
Framework: Cloudformation
Checkov is unable to resolve the CFN parameters and conditions properly like in the example shown below. Although 'public-access-block' evaluates to true, the scan still complains about "Ensure S3 bucket has block public ACLS enabled". Any idea why?

**Example Template**
```yaml
  BlockPublicAccess:
    Description: Set to true to block all public access with a public access block configuration
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"

  public-access-block: !Equals
    - !Ref BlockPublicAccess
    - "true"

  S3Bucket:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::S3::Bucket
      PublicAccessBlockConfiguration: !If
        - public-access-block
        - BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        - !Ref "AWS::NoValue"
```
