### ISSUE TITLE
Custom YAML based policies for dockerfile

### ISSUE THREAD

**Issue by sandeepsharmadevops** [bridgecrewio/checkov#5390]
**Describe the issue**

checkov is bundled with dockerfile specific rules/policies, can we build YAML based policies to be used for the dockerfile? if yes please share some references.

**Example Value**
Please share an example check / use case that this issue will allow checkov to support.

**Comment by sandeepsharmadevops** [comment]
I am referring checkov custom policies [page](https://www.checkov.io/3.Custom%20Policies/YAML%20Custom%20Policies.html), dockerfile is supported at framework with the following details.

![Screenshot 2023-07-31 at 1 54 32 PM](https://github.com/bridgecrewio/checkov/assets/12079189/bef68627-1f53-4570-9c68-d181ab966f55)

So, written custom YAML policy
```yaml
---
metadata:
  name: "myfirst docker policy"
  id: "CKV_DOCKERFILE_1222"
  category: "dockerfile"
definition:
  cond_type: "attribute"
  resource_types:
  - "FROM"
  attribute: "content"
  operator: "contains"
  value: "alpine"
```

Dockerfile
```
FROM alpine
```

Checkov command execution
checkov --framework dockerfile -f Dockerfile --check CKV_DOCKERFILE_1222 -d .

No result - neither policy/rule passed nor failed.
