### ISSUE TITLE
terraform/hcl merge used within for_each is not properly evaluated

### ISSUE THREAD

**Issue by nwsparks** [bridgecrewio/checkov#5447]
**Describe the issue**

Attempting to evaluate tags that are inside of a `merge()` function within a `for_each` loop does not work.

In the example below the `working` bucket passes this custom check, the `failing` bucket does not even though they both have the `replica=true` tag present.

**Examples**

```yaml
metadata:
 name: ensure replica tag is true
 id: s3_test_1
 category: "s3"
definition:
    cond_type: attribute
    resource_types:
      - aws_s3_bucket
    attribute: tags.replica
    operator: equals
    value: true
```

```hcl
locals {
  buckets = {
    "bucket1" = {
      name = "bucket1"
      tags = {
        name = "bucket1"
      }
    }
  }
}

# failing bucket
resource "aws_s3_bucket" "failing" {
  for_each = local.buckets

  bucket = each.value.name

  tags = merge(
    {replica = true},
    each.value.tags
  )
}

# working bucket
resource "aws_s3_bucket" "working" {
  bucket = "working"

  tags = merge(
    {replica = true},
    {name = "working"}
  )
}

```

**Version (please complete the following information):**
 - 2.3.366
