### ISSUE TITLE
Checkov HELM with values files for different ENVs

### ISSUE THREAD

**Issue by zeenmc** [bridgecrewio/checkov#5710]
Hello Team,

I hope you are doing well.
I am asking for assistance with Checkov and HELM.

`Checkov version: 3.0.16`
**command which is used**
`
checkov -d ./charts/ --framework helm -c CKV_K8S_12
`
**output**
```
helm scan results:

Passed checks: 0, Failed checks: 1, Skipped checks: 0

Check: CKV_K8S_12: "Memory requests should be set"
        FAILED for resource: Deployment.craftsphere.employees
        File: /employees/templates/deployment.yaml:3-243
        Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/bc-k8s-11
```

In our project we have folder with chart files, and one folder up we can find our values.yaml, values-dev.yaml, values-qa.yaml etc...

```
├── charts
│   ├── Chart.yaml
│   ├── templates
│   │   ├── deployment.yaml
│   │   ├── ingress.yaml
│   │   └── service.yaml
│   ├── values-dev.yaml
│   ├── values-prod.yaml
│   ├── values-qa.yaml
│   ├── values-sandbox.yaml
│   └── values.yaml
```
**Affected code* in deployment.yaml*
```
          resources:
            requests:
              memory: {{ .Values.podMemoryRequest }}
              cpu: {{ .Values.podCpuRequest }}
            limits:
              memory: {{ .Values.podMemoryLimit }}
```
**Affected values-dev.yaml file**
```
podMemoryRequest: 768Mi
podCpuRequest: 50m
podMemoryLimit podMemoryLimit: 768Mi
```

Question will be how to validate HELM files with values.yaml plus values files for respected ENV, eg: values-dev.yaml, values-qa.yaml etc....

I get error from output from below, but if I change two requests memory and limits memory with numbers, our test is passing fine.

```
          resources:
            requests:
              memory: {{ .Values.podMemoryRequest }}
              cpu: {{ .Values.podCpuRequest }}
            limits:
              memory: {{ .Values.podMemoryLimit }}
```
with

```
          resources:
            requests:
              memory: 768Mi
              cpu: {{ .Values.podCpuRequest }}
            limits:
              memory: 768Mi
```

Thank you in advance for your kind assistance.
