### ISSUE TITLE
GitLab SAST Reports JSON format

### ISSUE THREAD

**Issue by brenwhyte** [bridgecrewio/checkov#573]
**Describe the solution you'd like**
Add an output that's compatible to GitLab's [Reports JSON format ](https://docs.gitlab.com/ee/user/application_security/sast/#reports-json-format)that's compatible with the GitLab Security dashboard

**Additional context**
I've tried the below and despite the json file being created and uploaded as an artifact ok, nothing is showed in the SAST dashboard.

```
checkov_sast:
  image:
    name: bridgecrew/checkov
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: validate
  script:
    - checkov -o json -d . | tee gl-sast-checkov.json
  allow_failure: true
  artifacts:
    name: gl-sast-checkov.json
    paths:
      - gl-sast-checkov.json
    reports:
        sast: gl-sast-checkov.json
    expire_in: 1 week
  only:
    - branches
```
