### ISSUE TITLE
Chekov GitHub Actions Workflow Schema Outdated & not Scanning

### ISSUE THREAD

**Issue by bakosa** [bridgecrewio/checkov#5742]
**Describe the issue**
When running checkov, various GH workflow files are being ignored. After doing some digging, it looks like the [actions workflow schema](https://github.com/bridgecrewio/checkov/blob/4875adc472f409bc7039a879347b404468e88215/checkov/github_actions/schemas.py#L657) is outdated. Any workflow that contains the [run-name](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#run-name) property is not scanned. Adding this property to the schema on my local install fixes this. 

I also did some more digging to see if there are other outdated properties in this schema since it looks like it has not been updated in about a year, and I found a few probably worth mentioning. 

- The `check_suit` event trigger should only have `completed` as an activity type, not [these](https://github.com/bridgecrewio/checkov/blob/4875adc472f409bc7039a879347b404468e88215/checkov/github_actions/schemas.py#L1648) 3. Here are the [GitHub docs](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/events-that-trigger-workflows#check_suite).
-  I don’t think [member events](https://github.com/bridgecrewio/checkov/blob/4875adc472f409bc7039a879347b404468e88215/checkov/github_actions/schemas.py#L1821) can trigger workflows anymore.
- I don't think `project` events can trigger a workflow on `update` events. Here are the [GitHub docs](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/events-that-trigger-workflows#project)

**Examples**
Example workflow not being picked up
```yaml
name: Test Checkov Issue
run-name: "Setting run name ${{ github.ref_name }}"
on: 
  pull_request:
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              shell: bash
              run: echo "Hello World" 
```

**Version (please complete the following information):**
 - Checkov Version all
