### ISSUE TITLE
Checkov command not running checks from external policies directory

### ISSUE THREAD

**Issue by beairwalk** [bridgecrewio/checkov#5819]
Description: I’m having trouble getting the checkov command to run checks from my external policies directory. I’m using the --external-checks-dir parameter, that seems to parse the policies and throws an error if they are wrong. I’m also using policy IDs from the custom policys using the --checks parameter with the checkov command, but it’s not running the checks associated with those IDs. I would appreciate any help in resolving this issue.

Steps to Reproduce:

Run the checkov command with the --external-checks-dir parameter.

Use policy IDs with the --checks parameter with the checkov command.

Expected Behavior: The checkov command should run the checks from the external policies directory and the checks associated with the policy IDs.

Actual Behavior: The checkov command is not running the checks from the external policies directory or the checks associated with the policy IDs.

example custom policy:

```
---
metadata:
  name: "Ensure S3 Block Public Access setting is enabled"
  id: "AR_S3_01"
  category: "FSPB-S3"
definition:
  cond_type: "attribute"
  resource_types: "AWS::S3::Bucket"
  attribute: "BlockPublicAcls"
  operator: "equals"
  value: true
```

**Comment by JamesWoolfenden** [comment]
@beairwalk  Works for me!  

is your Yaml valid?

<img width="505" alt="image" src="https://github.com/bridgecrewio/checkov/assets/1456880/a54f6801-e4bd-4179-88ec-ba5e800838c5">

`checkov -d . --external-checks-dir external`

with custom.yaml is your file with this sample code:
```yaml
AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3BucketNoProps:
    Type: AWS::S3::Bucket
  S3BucketPublicRead:
    Type: AWS::S3::Bucket
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3045
    Properties:
      AccessControl: PublicRead
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  S3Bucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3045
    Properties:
      AccessControl: PublicRead
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: String
              SSEAlgorithm: aws:kms
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  S3Bucket2:
    Type: AWS::S3::Bucket
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3045
    Properties:
      AccessControl: PublicReadWrite
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: String
        LogFilePrefix: String
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  S3Bucket3:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
      LoggingConfiguration:
        DestinationBucketName: "String"
        LogFilePrefix: "String"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  S3Bucket4:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'example'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: Name of S3 bucket to hold website content
```
