### ISSUE TITLE
aws_cloudwatch_log_group - aws_cloudwatch_log_subscription_filter connection?

### ISSUE THREAD

**Issue by deese** [bridgecrewio/checkov#5852]
Good day :D

I would like to raise a question to the people involved on the project.  I wanted to create a custom check for ensuring that a aws_cloudwatch_log_group has a connected aws_cloudwatch_log_subscription_filter. 

Sample TF code

```
resource "aws_cloudwatch_log_group" "sample_group1" {
  name              = "/custom/loggroup"
  retention_in_days = 30
}
resource "aws_cloudwatch_log_subscription_filter" "sample_group1_filter" {
  name            = "sample subscripton filter"
  log_group_name  = "/custom/loggroup"
  filter_pattern  = ""
  destination_arn = "arn:aws:logs:eu-central-1:account:destination:kinesis-destination"
  distribution    = "ByLogStream"
}
```

A simple YAML check like that one, doesn't work and after some checks, I think that it is not detecting the connection between the resources, as it is not really a connection and the only relation is based on the name of the log group ( aws_cloudwatch_log_group.name <-> aws_cloudwatch_log_subscription_filter.log_group_name). 

```
definition:
  and:
    - cond_type:  connection
      resource_types:
        - aws_cloudwatch_log_group
      connected_resource_types:
        - aws_cloudwatch_log_subscription_filter
      operator: exists
    - cond_type: filter
      attribute: resource_type
      value:
        - aws_cloudwatch_log_group
      operator: within
```

Is this something I'm just not doing it properly or is this like that by design? If it's by design it would be great if something for checking cases like that is added to the YAML checks. 

I did a work around using the self.graph object but I would like to now if there is a proper way to do it in Python (some documentation to check?)

```
class DBSLMSCheck(BaseResourceCheck):
    LOG_GROUP = "/custom/loggroup"
    ARN_MATCH = re.compile(r'arn:aws:logs:eu-central-1:(account1|account2):destination:.*')

    def __init__(self) -> None:
        supported_resources = ("aws_cloudwatch_log_group",)
        name = "Ensure log group has configured log subscription to specific account"
        id = "CKV2_CUSTOM_3"
        categories = (CheckCategories.LOGGING,)
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)


    def scan_resource_conf(self, conf: dict[str, list[Any]]) -> CheckResult:

        log_group_name = conf.get("name", [])[0]

        if not log_group_name.startswith(self.LOG_GROUP):
            return CheckResult.UNKNOWN

        for i in list(itertools.chain(*self.graph.to_dict_list())):
            if i.get("block_type_", "") == "resource" and i.get("resource_type", "") == "aws_cloudwatch_log_subscription_filter":
                if i["attr"].get("log_group_name", "") == log_group_name:
                    if self.ARN_MATCH.search(i["attr"].get("destination_arn", "")):
                        return CheckResult.PASSED

        return CheckResult.FAILED
```

Thanks! :)
