### ISSUE TITLE
CloudFormation CKV_AWS_27 does not support SqsManagedSseEnabled property for encryption

### ISSUE THREAD

**Issue by bakosa** [bridgecrewio/checkov#5869]
**Describe the issue**
CKV_AWS_27 should handle the `SqsManagedSseEnabled` not just `KmsMasterKeyId`

*Note* CKV_AWS_27 on the Terraform side of the house already does this https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/resource/aws/SQSQueueEncryption.py

**Examples**
This should also pass CKV_AWS_27
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MySourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: "example_arn"
        maxReceiveCount: 5
      SqsManagedSseEnabled: true
```

**Version (please complete the following information):**
 - Checkov Version: latest

**Additional context**
Another thing to note is AWS by default will now do SSE on all newly created SQS queues
https://aws.amazon.com/blogs/compute/announcing-server-side-encryption-with-amazon-simple-queue-service-managed-encryption-keys-sse-sqs-by-default/
