### ISSUE TITLE
Gitlab-CI Job passes with failures present when emulating TTY for color output.

### ISSUE THREAD

**Issue by rosswickman** [bridgecrewio/checkov#590]
**Describe the bug**

Issue [#388] enabled the ability to use `script -q -c 'checkov -d .'` for colored output in gitlab-ci.yml.
This update prevents any status output from being presented to the runner causing the job to succeed even with a failure.

**To Reproduce**

use `script -q -c 'checkov -d .'` instead of `checkov -d .` in gitlab-ci job script section

```yaml
validate:checkov:
  stage: validate
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    #- script -q -c 'checkov -d ${CFT_DIR} --skip-check ${CHECKOV_SKIPS}'
    #- script -q -c 'checkov -d ${CFT_DIR}'
    #- checkov -d ${CFT_DIR} --skip-check ${CHECKOV_SKIPS}
    # - checkov -d ${CFT_DIR} --skip-check ${CHECKOV_SKIPS}
    - checkov -d ${CFT_DIR}
  when: always
```

**Expected behavior**
Error exit status causes job to fail instead of succeeding.

**Screenshots**

Screenshot of a successful job with failed checks using script -q -c 'checkov -d .':
![image](https://user-images.githubusercontent.com/1621528/94725681-c5aa2b80-0321-11eb-8238-7aabf3117473.png)

Screenshot of same code and checks resulting in failed job with no colored output using just checkov -d .:
![image](https://user-images.githubusercontent.com/1621528/94725786-ed998f00-0321-11eb-8f80-8b0ae1684d86.png)

**Desktop (please complete the following information):**
 - Checkov Version :latest

**Additional context**
Not afraid to admit I'm pretty ignorant with regards to emulating `tty` and could be missing a simple step to capture error.
Any nudge in the right direction would be great. Thanks

**Comment by metahertz** [comment]
Interesting! Thanks for reporting this! Taking a look!

**Comment by metahertz** [comment]
Theres been a lot of discussion about gitlab script runners not failing a job on a bad return code:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/25394
https://gitlab.com/gitlab-org/gitlab/-/issues/241714

However, I think in our case, we're getting a zero return code from the `script` command, rather than passing back the non-zero return from checkov. 

With the following:

```yaml
validate:checkov:
  stage: test
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - script -q -c 'checkov -d . ; echo $?'
    - echo $?
```

We see a 1 returned from checkov, then a zero from the outer command, and a "succeeded" run.

<img width="972" alt="Screenshot 2020-09-30 at 23 11 42" src="https://user-images.githubusercontent.com/4842186/94745412-91ab2680-0372-11eb-8a72-161b797379ff.png">

**Comment by metahertz** [comment]
After some head scratching, this works:

```yaml
validate:checkov:
  stage: test
  image:
    name: bridgecrew/checkov:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - script -q -c 'checkov -d . ; echo $? > CKVEXIT'
    - exit $(cat CKVEXIT)
  when: always
```
Writing our return code to a file within the `script` binary execution, then causing an exit using that code outside afterwards. 

Policy violations:
<img width="970" alt="Screenshot 2020-09-30 at 23 54 59" src="https://user-images.githubusercontent.com/4842186/94748192-aab6d600-0378-11eb-8144-1aa8ee133c80.png">

No Violations:
<img width="381" alt="Screenshot 2020-09-30 at 23 54 32" src="https://user-images.githubusercontent.com/4842186/94748220-ba361f00-0378-11eb-8033-9b01a8910a56.png">

<img width="1041" alt="Screenshot 2020-09-30 at 23 54 10" src="https://user-images.githubusercontent.com/4842186/94748250-c7530e00-0378-11eb-87a9-07c0a0820275.png">

I tried a load of cleaner ways first, like bash shell opts, `bash -c` (same issue, no colours) and then getting the checkov return code using environment variables (which dont seem to persist between steps at all), so while hacky, the file was the only option of persistence  that seems to work, and exporting as artifacts etc seems a little overkill!
