### ISSUE TITLE
How to block Action dynamodb:* or any other service followed by *

### ISSUE THREAD

**Issue by yehudimikhael** [bridgecrewio/checkov#5926]
How do I make it Fail when presenting an Action with dynamodb:* or s3:* or apigateway:*?

I'm using CloudFormation

```yaml
Resources:
  APIGatewayRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: APIGatewayDynamoDBPolicyBoundsDelete
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:*'
                Resource:
                  - 'arn:aws:dynamodb:us-east-1:1111111111111:table/dynamodb-bound/*'
       ```

**Comment by gruebel** [comment]
Hey @yehudimikhael thanks for reaching out.

Are you writing a Python or YAML based check?

**Comment by yehudimikhael** [comment]
@gruebel 
I'm writing in YAML

**Comment by gruebel** [comment]
That's not so easy, but you can find here an example for Terraform https://github.com/bridgecrewio/checkov/blob/main/checkov/terraform/checks/graph_checks/aws/IAMPolicyNotAllowFullIAMAccess.yaml it will be similar for CloudFormation.

**Comment by yehudimikhael** [comment]
iIn the run command do i pass the parameter referencing this yaml ?

**Comment by gruebel** [comment]
You mean the CLI command? If yes, then you have to use the external check flag and reference the folder, which stores the YAML file. And use a different ID, otherwise it won't work, because internal IDs are preferably considered.

**Comment by yehudimikhael** [comment]
I'll test it here and let you know

**Comment by yehudimikhael** [comment]
would the CLI call look like this?

`$ checkov -d . --external-checks-dir s3PolicyCheck.yaml`

**Comment by yehudimikhael** [comment]
I managed to solve it here and my .yaml file is :

```yaml
---
metadata:
 name: "Ensure no actions policies that allow full 'RESOURCE:*' administrative privileges are not created"
 id: "CUSTOM_AWS_0126"
 category: "GENERAL_SECURITY"
scope:
 provider: aws
definition:
  and:
    - cond_type: "attribute"
      resource_types: "AWS::IAM::Role"
      attribute: Policies.PolicyDocument.Statement[*].Action[*]
      operator: "jsonpath_not_equals"
      value: "s3:*"
    - cond_type: "attribute"
      resource_types: "AWS::IAM::Role"
      attribute: Policies.PolicyDocument.Statement[*].Action[*]
      operator: "jsonpath_not_equals"
      value: "dynamodb:*"
    - cond_type: "attribute"
      resource_types: "AWS::IAM::Role"
      attribute: Policies.PolicyDocument.Statement[*].Action[*]
      operator: "jsonpath_not_equals"
      value: "states:*"
      
```
