### ISSUE TITLE
(Question) Is it possible to block an entire resource?

### ISSUE THREAD

**Issue by bschaatsbergen** [bridgecrewio/checkov#5975]
I'm wondering if it's possible to flat-out reject the creation of a particular resource type, such as the `google_service_account_key`. I want to implement a custom Checkov policy to prevent the creation of the `google_service_account_key` resource. Although I couldn't find any relevant details in the documentation, I would expect this to be possible.

**Comment by JamesWoolfenden** [comment]
You could write a rule to fail if you find any google_service_account_key resources, like: 

```
from __future__ import annotations

from typing import Any

from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck


class ServiceAccountKey(BaseResourceCheck):
    def __init__(self):
        name = "Ensure that service account key creation is denied"
        id = "CKV_GCP_124"
        supported_resources = ("google_service_account_key")
        categories = (CheckCategories.IAM,)
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf: dict[str, list[Any]]) -> CheckResult:
        return CheckResult.PASSED


check = ServiceAccountKey()
```

**Comment by bschaatsbergen** [comment]
Thanks a lot for the swift response, @JamesWoolfenden! I attempted to use the YAML custom policies but struggled how to make it work there. If you happen to know by any chance, I'd appreciate it! Otherwise, thanks for providing this example :)!

**Comment by bschaatsbergen** [comment]
I've found a working solution to check whether any attribute is present.

```
---
metadata:
  name: "Service account keys are not allowed to be created"
  id: "EXAMPLE_GCP_2"
  category: "GENERAL"
  guideline: "If you need to create a service account key, please contact Example."
scope:
  provider: gcp
definition:
  cond_type: "attribute"
  resource_types:
    - "google_service_account_key"
  attribute: "*"
  operator: "exists"

```
