### ISSUE TITLE
CKV_GCP_110 test still fails after recommended change for PostrgeSQL's database_flag for pgAudit (GCP and Terrafrom)

### ISSUE THREAD

**Issue by marcin-kulik** [bridgecrewio/checkov#6058]
**Test still fails after recommended change**

My terraform code fails on the above 2 tests:

```
        Code lines for this resource are too many. Please use IDE of your choice to review the file.
Check: CKV_GCP_110: "Ensure pgAudit is enabled for your GCP PostgreSQL database"
    FAILED for resource: google_sql_database_instance. cloud_sql
    File: /cloud_sql.tf:1-74
    Guide: https:/
```

**My code was changed accordingly with the advice**

```
resource "google_sql_database_instance" "cloud_sql" {
  name             = "cloud-sql"
  database_version = "POSTGRES_15"
  region           = var.region
  project          = var.project_id

  settings {
    tier = "db-f1-micro"

    backup_configuration {
      enabled = true
    }
    ip_configuration {
      ipv4_enabled = false
      require_ssl     = false
      private_network = "projects/${var.project_id}/global/networks/${var.network}"
    }
    database_flags {
      name  = "log_statement"
      value = "all"
    }
    database_flags {
      name  = "log_lock_waits"
      value = "on"
    }
    database_flags {
      name  = "log_connections"
      value = "on"
    }
    database_flags {
      name  = "log_checkpoints"
      value = "on"
    }
    database_flags {
      name  = "log_disconnections"
      value = "on"
    }
    database_flags {
      name  = "log_hostname"
      value = "on"
    }
    database_flags {
      name  = "log_min_error_statement"
      value = "ERROR"
    }
    database_flags {
      name  = "log_min_messages"
      value = "ERROR"
    }
#    database_flags {
#      name  = "log_min_messages"
#      value = "DEBUG5"
#    }
#    database_flags {
#      name  = "enable_pgaudit"
#      value = "on"
#    }
    database_flags {
      name  = "pgaudit.log"
      value = "'all'"
    }
    database_flags {
      name  = "log_duration"
      value = "on"
    }
  }
  deletion_protection = false
  depends_on          = [google_service_networking_connection.private_vpc_connection]
}
```
**Version:**
Checkov 3.2.25

**Additional context**
I am running checkov from the Azure DevOps pipeline on Ubuntu 20.04.
Most of the checks behave normally.

Here are Azure DevOps tasks:

```
          - task: Bash@3
            displayName: 'Install checkov 3.2.25'
            inputs:
              targetType: 'inline'
              script: |
                pip3 install checkov==3.2.25

          - task: Bash@3
            displayName: 'Run checkov'
            inputs:
              targetType: 'filePath'
              filePath: ${{ parameters.rootDirectory }}/pipeline-templates/gcp/scripts/run_checkov.sh
              arguments: >
                ${{ parameters.rootDirectory }}/${{ parameters.repositoryName }}/${{ parameters.terraformFolder }}
                ${{ parameters.checkovSkipCheck }}
```

Here is my bash script to run checkov:

```
#!/bin/bash

terraform_working_directory="$1"
skip_check="$2"

echo "Terraform Working Directory: $1"
echo "Skip Check: $2"

python3 -m venv .venv
source .venv/bin/activate
pip3 install --upgrade pip
pip3 install --upgrade checkov

echo "Executing Checkov with skip checks"
echo "checkov -d \"$terraform_working_directory\" --download-external-modules true --skip-check \"$skip_check\" --output cli"
echo "Skip checks to be passed to Checkov: \"$skip_check\""

checkov -d "$terraform_working_directory" --download-external-modules true --skip-check $skip_check --output cli
checkov_exit_code=$?

if [ $checkov_exit_code -ne 0 ]; then
  echo "Checkov identified issues."
  exit $checkov_exit_code
else
  echo "Checkov completed successfully with no issues."
fi
```
