### ISSUE TITLE
[ask] Can we extend checkov secret policy?

### ISSUE THREAD

**Issue by kecebon9** [bridgecrewio/checkov#6089]
**Describe the issue**
1. Currently the list of regular expressions defined [here](https://github.com/bridgecrewio/checkov/blob/main/checkov/common/util/secrets.py), is there anyway we can extend it using custom secret policy?

or can Checkov do scanning credentials and secret for plain text file (.txt, etc) (other than .yaml .tf, etc).

2. Our use case is let say for helm, the checkov unable to scan secret inside `test.yaml` because the `configmap.enabled` set to `false` on the `values.yaml` file. is there any way we can still do a check to all yaml content.
```
# values.yaml
configmap:
  enabled: false
```

```
# templates/test.yaml
{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  database.properties: |
    username: myuser
{{- end }}
```

thanks
