### ISSUE TITLE
CloudFormation: All protocols and ports open in Security Group Ingress not recognized

### ISSUE THREAD

**Issue by mil-dot** [bridgecrewio/checkov#6108]
**Describe the issue**
Some IpProtocol values in security group ingress disregard port ranges and leave all ports open, which is not recognized by existing test cases like CKV_AWS_24.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-securitygroupingress.html#cfn-ec2-securitygroupingress-ipprotocol
TCP, UDP, ICMP protocols must have port range specified, IPv6-ICMP can have it optionally.
All other protocols disregard port ranges, allowing traffic on all ports.

Checks should recognize IpProtocol -1 as the least restrictive syntax; Checks should handle situations where FromPort and ToPort do not apply because of IpProtocol value.

**Examples**
CloudFormation:

```
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !FindInMap [ LandingZoneMap, Sandbox, VpcId ]
      SecurityGroupEgress:
        - Description: Allow outbound connections
          IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - Description: Allow inbound connections
          IpProtocol: -1
          CidrIp: 0.0.0.0/0

```
In this example Ingress allows inbound connections to all ports (including 22, 80 etc) over all protocols, while rules like CKV_AWS_24 do not recognize it.

**Version (please complete the following information):**
 - 3.2.38

**Additional context**
I have added a separate rule to handle this situation: https://github.com/bridgecrewio/checkov/pull/6088
