### ISSUE TITLE
No colors using Azure DevOps pipelines

### ISSUE THREAD

**Issue by msl0** [bridgecrewio/checkov#6110]
I'm using Azure Devops pipelines to run Checkov, but output is monochromatic. 
```
steps:
  - pwsh: |
      checkov -d .
    displayName: Checkov
```

Output from Azure DevOps pipeline:
![image](https://github.com/bridgecrewio/checkov/assets/59068696/5a6dee3e-4e09-4d57-8221-15b03b5d0d9a)

Output on my local machine:
![image](https://github.com/bridgecrewio/checkov/assets/59068696/aaa627ed-7cda-495a-82d6-b46d8ad1f126)

Is there any way to enforce colors?
