### ISSUE TITLE
Custom yml policy is not matching the contents of Terraform

### ISSUE THREAD

**Issue by rajagopalan-trimble** [bridgecrewio/checkov#6137]
**Describe the issue**
I wrote a custom check policy in YML to find if service bus primay key is used in an azurerm_api_management_api_operation_policy. I used the "contains" logical operator with a regex pattern that has to look into the contents of the attribute xml_content, but the checks fail even if the matching contents are not there.
Expected behavior is to fail checks if the xml_content contains azurerm_servicebus_queue_authorization_rule.queue_auth_rule[each.key].primary_key but it fails even if azurerm_servicebus_queue_authorization_rule.queue_auth_rule[each.key].primary_key is not in the content.

**Examples**
```
resource "azurerm_api_management_api_operation_policy" "enqueue_operation_policy" {
  for_each            = var.servicebus
  api_name            = each.value.system_api.name
  api_management_name = each.value.system_api.api_management_name
  resource_group_name = var.resource_group.name
  operation_id        = azurerm_api_management_api_operation.enqueue_operation[each.key].operation_id

  xml_content = <<XML
<policies>
    <inbound>
        <base />
        <cache-lookup-value key="${local.queue_name}_sas" variable-name="cachedSasToken" />
        <choose>
            <when condition="@(context.Variables.GetValueOrDefault&lt;string&gt;("cachedSasToken") == null)">
                <set-variable name="cachedSasToken" value="@{
                    string resourceUri = "https://${local.namespace_name}.servicebus.windows.net/${local.queue_name}";
                    string keyName = "${azurerm_servicebus_queue_authorization_rule.queue_auth_rule[each.key].name}";
                    string key = "${azurerm_servicebus_queue_authorization_rule.queue_auth_rule[each.key].primary_key}";
                    TimeSpan sinceEpoch = DateTime.UtcNow - new DateTime(1970, 1, 1);
                    var expiry = Convert.ToString((int)sinceEpoch.TotalSeconds + 120);
                    string stringToSign = System.Uri.EscapeDataString(resourceUri) + "\n" + expiry;
                    HMACSHA256 hmac = new HMACSHA256(Encoding.UTF8.GetBytes(key));
                    var signature = Convert.ToBase64String(hmac.ComputeHash(Encoding.UTF8.GetBytes(stringToSign)));
                    var sasToken = String.Format("SharedAccessSignature sr={0}&amp;sig={1}&amp;se={2}&amp;skn={3}",
                                    System.Uri.EscapeDataString(resourceUri),
                                    System.Uri.EscapeDataString(signature), expiry, keyName);
                    return sasToken;
                }"/>
                <cache-store-value key="${local.queue_name}_sas" value="@(context.Variables.GetValueOrDefault&lt;string&gt;("cachedSasToken"))" duration="10" />                
            </when>
        </choose>
        <set-header name="Authorization" exists-action="override">
            <value>@(context.Variables.GetValueOrDefault<string>("cachedSasToken"))</value>
        </set-header>
        <set-header name="Content-type" exists-action="override">
            <value>application/json</value>
        </set-header>
        <set-backend-service base-url="https://${local.namespace_name}.servicebus.windows.net" />
        <rewrite-uri template="${local.queue_name}/messages" />
    </inbound>
</policies>
XML

}

```
```
metadata:
  name: "Ensure Azure services are integrated using Managed Identity rather than access key"
  category: "GENERAL_SECURITY"
  id: "TCP_AZURE_APIM_POLICY_SECRET"
scope:
  provider: "AZURE"
definition:
  or:
    - cond_type: attribute
      attribute: xml_content
      operator: contains
      value: '[a-z_.\[\]]*primary_[a-z]*_key'
      resource_types:
        - azurerm_api_management_api_operation_policy
    - cond_type: attribute
      attribute: xml_content
      operator: contains
      value: '[a-z_.\[\]]*primary_key'
      resource_types:
        - azurerm_api_management_api_operation_policy
```
**Version (please complete the following information):**
 - Checkov Version [e.g. 22]
3.2.39
**Additional context**
