### ISSUE TITLE
does not work to specify multiple external-checks-git and external-checks-dir

### ISSUE THREAD

**Issue by krizi** [bridgecrewio/checkov#6159]
**Describe the issue**
i have issues running checkov with multiple external checks. right now only the first reference is picked up and used. the others are ignored.  
all sources which are used works if they're the only source, but if all are referenced at the same time only the first is working the other are ignored.

**Examples**
```yaml

framework:
- kubernetes
external-checks-git:
  - ssh://git@my.git.com/common-checks.git//base
  - ssh://git@my.git.com/common-checks.git//specific
external-checks-dir:
  - checks
quiet: true
compact: true
```

**Version (please complete the following information):**
 - Checkov Version: 3.2.50

**Additional context**
this is one of these checks i used to verify if all sources are used.
```python
from __future__ import annotations

from typing import Any

from checkov.common.models.enums import CheckCategories, CheckResult
from checkov.kubernetes.checks.resource.base_spec_check import BaseK8Check


class VerifyNamespace(BaseK8Check):
    def __init__(self) -> None:
        name = "Namespace must start with 'my-'"
        id = "MY_ID_1"
        supported_kind = ("Namespace",)
        categories = (CheckCategories.KUBERNETES,)
        super().__init__(name=name, id=id, categories=categories, supported_entities=supported_kind)

    def scan_spec_conf(self, conf: dict[str, Any]) -> CheckResult:
        metadata = conf.get("metadata")
        if metadata:
            name = metadata["name"]
            if name.lower().startswith("my-"):
                return CheckResult.PASSED
            else:
                return CheckResult.FAILED
        return CheckResult.UNKNOWN


check = VerifyNamespace()
```
command used to execute: 
```bash
CHECKOV_OPTS="\
--soft-fail
--skip-download
--directory $configroot/rendered
--output junitxml
--config-file checkov.yaml"

checkov $CHECKOV_OPTS --baseline $configroot/.checkov.baseline --output-baseline-as-skipped --create-baseline | tee checkov-$testname.xml
```
