### ISSUE TITLE
Skiping CKV2_GHA_1 is not honoured 

### ISSUE THREAD

**Issue by AttilaT** [bridgecrewio/checkov#6216]
**Describe the issue**
The inline skip `CKV2_GHA_1` is not honoured.

**Examples**
When scanning the below yaml file

```yaml
name: Default
#checkov:skip=CKV2_GHA_1:Please ignore
permissions: write-all
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  short-run:
    name: short-run
    runs-on: ${{ vars.LINUX_RUNNER }}
    steps:
      - name: Validate repo
        shell: bash
        run: echo "Hello!"
```

**Version (please complete the following information):**
 - Checkov is running of release `v3.2.74`
