### ISSUE TITLE
Error while installing checkov in Azure pipelines

### ISSUE THREAD

**Issue by VimukthiPerera** [bridgecrewio/checkov#629]
**Describe the bug**
I'm trying to integrate checkov with Azure pipelines. Encountered the following error while trying to install checkov.

```
Collecting checkov
  Downloading https://files.pythonhosted.org/packages/a4/84/158ce0a10321dccc4e842974df78c8c5818a7194061d0a9d4c256be88ae3/checkov-1.0.594.tar.gz (130kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-As8PIb/checkov/setup.py", line 4, in <module>
        from importlib import util
    ImportError: cannot import name util
```

**To Reproduce**
1. Configure Azure pipeline to run checkov against helm charts.
```
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
    echo Running Checkov Scan!
    sudo apt-get install python3.7
    pip install checkov
    checkov -d . --framework kubernetes
  displayName: 'Run Checkov Scan script'
```
2. Commit code to trigger the pipeline.

**Expected behavior**
Install checkov.

**Screenshots**
![image](https://user-images.githubusercontent.com/15902071/96969266-d79d7980-152f-11eb-8ff1-145be6c0ec60.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu latest
 - Checkov Version: 1.0.594

**Additional context**
Same works with GitHub actions(Which also runs on Azure I presume).
```
---
name: Checkov
on:
  push:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test with Checkov
        run: |
          pip install checkov
          checkov -d . --framework kubernetes
```
![image](https://user-images.githubusercontent.com/15902071/96969736-627e7400-1530-11eb-8823-aa203d3afa86.png)
