### ISSUE TITLE
[Helm] Issue when pulling chart dependency from OCI registry

### ISSUE THREAD

**Issue by Farfaday** [bridgecrewio/checkov#6350]
**Describe the issue**
When running checkov on a chart, pulling dependencies out of a public OCI repository like
```
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
```
then checkov fails with 

```sh
LOG_LEVEL=DEBUG checkov -d .
[...]
2024-05-14 16:10:56,667 [MainThread  ] [WARNI]  Failed processing helm chart mychart at dir: .. Working dir: /tmp/tmpr6umnbn6. Failure details: Pulled: registry-1.docker.io/bitnamicharts/common:2.19.2
```

The dependency chart is correctly pulled (files are there) but checkov fails and does not check the chart.
Running checkov again is then successful. 

When changing the repository to https, it works without issue.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Checkov Version: 3.2.106
 - Same behavior with latest docker container.
