### ISSUE TITLE
Custom Check for CloudFormation DeletionPolicy

### ISSUE THREAD

**Issue by dmeiser** [bridgecrewio/checkov#6440]
I have a use case where I want to check specific resources for a DeletionPolicy. I created the YML configuration below, but the check fails every time. It appears that checks for DeletionPolicy are not currently supported:
```
definition:
  cond_type: attribute
  resource_types:
  - AWS::S3::Bucket
  attribute: DeletionPolicy
  operator: equals
  value: Retain
```
