### ISSUE TITLE
CKV2_ANSIBLE_2 false positive when variable is used

### ISSUE THREAD

**Issue by amedee** [bridgecrewio/checkov#6556]
**Describe the issue**
`CKV2_ANSIBLE_2` gives a false positive when an https url is inside a variable.

**Examples**
Task:
```
- name: Check if WP-CLI is already installed
  ansible.builtin.stat:
    path: "{{ blog_wpcli_path }}"
  register: wpcli

- name: Download WP-CLI
  when: not wpcli.stat.exists
  become: true
  ansible.builtin.get_url:
    url: "{{ blog_wpcli_url }}"
    dest: "{{ blog_wpcli_path }}"
    owner: root
    mode: u=rwx,go=rx
```

In `vars/main.yml`:
```
---
blog_wpcli_path: /usr/local/bin/wp
blog_wpcli_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
```
Expected outcome:
* `CKV2_ANSIBLE_2` passes because `blog_wpcli_url` starts with https.

Actual outcome:
* `CKV2_ANSIBLE_2` fails.

**Version (please complete the following information):**
 - Checkov Version: 3.2.79 (the version reported by Codacy)
