### ISSUE TITLE
CKV_AZURE_43 Naming and Description Mismatch

### ISSUE THREAD

**Issue by iheanacho-chukwu** [bridgecrewio/checkov#6559]
**Issue Description**
The check CKV_AZURE_43: "Ensure Storage Accounts adhere to the naming rules" has conflicting information between its title, address, and description. The description talks about encryption using Customer Managed Keys (CMKs) for Azure Cognitive Services accounts, which does not match the title and address.

**Examples**
## Bicep Code Sample + the expected outcomes.

```yaml
resource storageAccountResource 'Microsoft.Storage/storageAccounts@2023-01-01' = {
  name: storageAccount.name
  location: location
  kind: 'StorageV2'
  sku: {
    name: 'Standard_GRS'
  }
  properties: {
    allowBlobPublicAccess: false
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
  }
  tags: tags
}
```

## The Expected outcomes**
- Align the description with the title and address, providing clear guidance on naming rules for storage accounts. If the check is about encryption for Azure Cognitive Services accounts, update the title and address accordingly and vice versa.

**Version:**
 - Checkov Version 3.2.179

**Additional context**
- I am running checkov via Azure DevOps Pipeline
`checkov --directory ${{ variables.armBicepTemplatesSourceFolder }} --file ${{ variables.armBicepTemplatesSourceFolder }}/${{ variables.armBicepDeploymentFile }} --framework $(templateFramework) --soft-fail --quiet --compact --output sarif --output-file-path $(System.DefaultWorkingDirectory)/results/ --skip-check $(SKIP_CHECKS)`

Result Snippet

```yaml
Check: CKV_AZURE_43: "Ensure Storage Accounts adhere to the naming rules"
	FAILED for resource: Microsoft.Storage/storageAccounts.storageAccountResource
	File: /Modules/function-app.bicep:31-44
	Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/azure-policies/azure-general-policies/ensure-cognitive-services-account-encryption-cmks-are-enabled
```

- The description should provide accurate information related to storage account naming rules, or the title and address should be updated if it pertains to encryption for Azure Cognitive Services accounts.
