### ISSUE TITLE
AzApi support

### ISSUE THREAD

**Issue by deku1998** [bridgecrewio/checkov#6584]
Hi,

Is there support for azapi_resource with custom yaml policy. Since all resources in azure can be created with azapi_resource there is currently no way to distinguish between 2 resources.

**Comment by tsmithv11** [comment]
Hey @deku1998, yes it's supported today, but it can create some noisy "passed" resources. Here's an example, not a real check, for illustrative purposes:

```yaml
definition:
  or:
    - cond_type: attribute
      resource_types:
      - azapi_resource
      attribute: type
      operator: not_regex_match
      value: Microsoft\.ContainerRegistry/registries@[^/]+
    - cond_type: attribute
      resource_types:
      - azapi_resource
      attribute: identity.type
      operator: not_contains
      value: "UserAssigned"
```

This will pass all resources that aren't `Microsoft.ContainerRegistry/registries` resource type and fail `Microsoft.ContainerRegistry/registries` that have identity types that are UserAssigned. Alternatively, you can make it a little cleaner with a Python check:

```python
from __future__ import annotations

from typing import Any
import re

from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck

resource_regex = r'Microsoft\.ContainerRegistry/registries@[^/]+'

class EXAzApiCheck(BaseResourceCheck):
    def __init__(self) -> None:

        name = "Example"
        id = "CKV_AZURE_999"
        supported_resources = ("azapi_resource",)
        categories = (CheckCategories.GENERAL_SECURITY,)
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf: dict[str, list[Any]]) -> CheckResult:
        resource_type = conf.get("type")[0]
        if re.match(resource_regex, resource_type) is None:
            return

        if conf.get("identity") and conf.get("identity")[0].get("type") and \
                ("UserAssigned" in conf.get("identity")[0].get("type") or \
                "UserAssigned" in [s.replace(" ", "") for s in conf.get("identity")[0].get("type")[0].split(',')]):
            return CheckResult.FAILED

        return CheckResult.PASSED


check = EXAzApiCheck()
```

This will skip resources that aren't of the appropriate type.
