### ISSUE TITLE
False positive for provider check during terraform plan scans

### ISSUE THREAD

**Issue by kirrmann** [bridgecrewio/checkov#6709]
Hi,
I'm hitting an issue during **terraform plan** scans (`CKV_FRAMEWORK = terraform_plan`) and you can already see in the error output that the definition it's complaining about, does indeed exist
```
Check: CKV_TF_LMN_001: "Check that the provider has default_tags set"
	FAILED for resource: aws.default
	File: providers.tf:1-10
	Guide: ...
		1  | provider "aws" {
		2  |   region = var.region
		3  |   assume_role {
		4  |     role_arn     = "arn:aws:iam::${arn}"
		5  |     session_name = "TerraformSession"
		6  |   }
		7  |   default_tags {
		8  |     tags = var.base_tags
		9  |   }
		10 | }
```

the YAML policy is
```
---
metadata:
  name: Check that the provider has default_tags set
  id: CKV_TF_LMN_001
  category: CONVENTION
  guideline: ...
scope:
  provider: aws
definition:
  cond_type: attribute
  resource_types:
    - provider
  attribute: default_tags
  operator: exists

```

the error appears after version 3.2.243 so I assume it was introduced in 3.2.245 by https://github.com/bridgecrewio/checkov/pull/6690

During terraform scans the check does behave correctly.
