### ISSUE TITLE
CKV2_K8S_{1-5} do not check `apiGroups` of ClusterRoleBindings

### ISSUE THREAD

**Issue by m-wynn** [bridgecrewio/checkov#6765]
**Describe the issue**
CKV2_K8S_1-5 check if ClusterRoleBindings have access to read all secrets, impersonate permissions, set nodes/proxy or pods/exec by checking for wildcards, etc.  However, they don't check apiGroups.  If you want to give your ServiceAccount *.* within your API group, that should only trigger CKV_K8S_49 (minimize wildcard use in Roles and ClusterRoles), not these specific rules.

I believe this started on a fairly recent version of Checkov.  I saw it on 3.2.257, but I don't remember seeing it on 3.2.250.

**Examples**
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test
rules:
  - apiGroups:
      - my-custom.api.group
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test
subjects:
  - kind: ServiceAccount
    name: my-cool-service-account
    namespace: my-namespace
```

The [Prometheus-Adapter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-adapter/templates/custom-metrics-cluster-role.yaml) Helm Chart also runs into this issue.

**Version (please complete the following information):**
 - Checkov Version 3.2.257
