### ISSUE TITLE
Support attribute paths with dots in custom policies (YAML custom policies)

### ISSUE THREAD

**Issue by mbukh** [bridgecrewio/checkov#6804]
Currently, the attribute field in yaml custom policies does not support paths that include dots ("."). This makes it difficult to reference nested keys that have dots in their names, such as:
```yaml
valuesObject:
  ingress:
    annotations:
      external-dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
```

To reference this path I would do:
```yaml
definition:
  attribute: valuesObject.ingress.annotations.external-dns.alpha.kubernetes.io/ingress-hostname-source
```
Which will definitely fail. 

We should add support for either:
1. Escaping dots with a backslash like `attribute\.with\.dots`
2. Using square bracket notation like `['attribute.with.dots']`
3. Both 1) and 2)

For example:

```yaml
definition:
  # attribute: valuesObject.ingress.annotations.external-dns\\.alpha\\.kubernetes\\.io/ingress-hostname-source
  attribute: |-
    valuesObject.ingress.annotations.external-dns\.alpha\.kubernetes\.io/ingress-hostname-source
```

or

```yaml
definition:
  attribute: valuesObject.ingress.annotations.external-dns['alpha.kubernetes.io/ingress-hostname-source']
```

This will allow more flexibility in referencing nested keys in custom policies.
