### ISSUE TITLE
kustomize checks can only be skipped with invalid YAML

### ISSUE THREAD

**Issue by ChrisSamo632** [bridgecrewio/checkov#6900]
**Describe the issue**

Checkov fails to skip `kustomize` framework issues when annotations are added to the `kustomization.yaml` file **unless* those annotations are added using invalid YAML

- valid YAML, checkov skip ignored (i.e. checkov test fails):

```yaml
metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_14=using latest Image Tag for local development is easiest
```

- invalid YAML (annotation not indented so `annotations` is not a valid YAML Object), checkov skip accepted (i.e. checkov test passes):

```yaml
metadata:
  annotations:
  checkov.io/skip1: CKV_K8S_14=using latest Image Tag for local development is easiest
```

**Examples**

Given a `kustomization.yaml` like

```yaml
resources:
  - ../../base

images:
  - name: api
    newName: api
    newTag: latest

metadata:
  annotations:
    checkov.io/skip1: CKV_K8S_14=using latest Image Tag for local development is easiest
```

The `checko` test fails. Breaking the YAML and un-indenting the `checkov.io/skip1` annotation allows the `checkov` test to pass.

**Version (please complete the following information):**
 - Checkov Version: 3.2.330
