### ISSUE TITLE
Unable to skip Argo Workflow checks

### ISSUE THREAD

**Issue by michaelzulian** [bridgecrewio/checkov#6957]
**Describe the issue**
Unable to skip Argo Workflow checks

**Examples**
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  generateName: "script-"
  name: "script"
  annotations:
    checkov.io/skip: CKV_ARGO_1
....
```
**Version (please complete the following information):**
`version: 3.2.353 `

**Additional context**
Tried the various forms IE. `checkov.io/skip1: CKV_ARGO_1`

Checking the source code, doesn't appear to be anything regarding skip under the workflow runner
