### ISSUE TITLE
CloudFormation: Unable to Validate Secret Manager Resource Policies Using forEach

### ISSUE THREAD

**Issue by sarbole** [bridgecrewio/checkov#6995]
**Describe the issue**
Cloudformation / I am trying to identify that all secret manager resources have an associated resource policy, but when using the forEach of cloudformation, although each resource has its policy associated with the check it is not possible to identify it, is there any support for foreach? , Thanks

**Custom Rule**:
```yaml
metadata:
    name: "Check that Secret has configured Resource Based policy"
    id: "CKV2_777"
    category: "GENERAL_SECURITY"
definition:
    and:
        - cond_type: "filter"
          attribute: "resource_type"
          value:
            - AWS::SecretsManager::Secret
          operator: within
        - cond_type: connection
          operator: exists
          resource_types:
              - AWS::SecretsManager::Secret
          connected_resource_types:
              - AWS::SecretsManager::ResourcePolicy
```

**Example Value**
```yaml
Resources:
  Secret1:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "Secret1"
      Description: "first secret"

  Secret2:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "Secret2"
      Description: "second secret"

  Fn::ForEach::secretsResourcePolicy:
    - SecretIdentifier
    - - Secret1
      - Secret2
    - ${SecretIdentifier}RoleBasedPolicy:
        Type: AWS::SecretsManager::ResourcePolicy
        Properties:
          ResourcePolicy:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Principal:
                  AWS:
                    - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/cloudformation-service-deployment
                Resource: '*'
              - Effect: Deny
                Action: secretsmanager:GetSecretValue
                Condition:
                  Fn::If:
                    - DeployVSTSRole
                    - StringNotLike:
                        aws:PrincipalArn:
                          - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/asdasd
                          - Ref: DbaAdminRole
                Principal:
                  AWS: '*'
                Resource: '*'
          SecretId:
            Ref: SecretIdentifier
```
