### ISSUE TITLE
CKV_K8S_31 failure with RuntimeDefault configured

### ISSUE THREAD

**Issue by VimukthiPerera** [bridgecrewio/checkov#710]
**Describe the bug**
CKV_K8S_31 failure when the `seccompProfile` type is configured as `RuntimeDefault` which is the new syntax.

**To Reproduce**
1. Define security context as below.
```yaml
...
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
...
```
2. Run checkov for kubernetes.

**Expected behavior**
CKV_K8S_31 to pass with the following configuration.
```yaml
...
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
...
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Kubernetes 1.19.0
-  OS: Ubuntu 18.04
 - Checkov Version: 1.0.657

**Additional context**
https://kubernetes.io/docs/tutorials/clusters/seccomp/#create-pod-that-uses-the-container-runtime-default-seccomp-profile

**Comment by nimrodkor** [comment]
Good catch! 
We'd appreciate a contribution!
Check out https://github.com/bridgecrewio/checkov/blob/e6ba23cbd7b570111bd8ca485371dceeba90d318/checkov/kubernetes/checks/Seccomp.py#L28 for implementation and https://github.com/bridgecrewio/checkov/blob/master/tests/kubernetes/checks/test_Seccomp.py for tests :)

**Comment by VimukthiPerera** [comment]
@nimrodkor This needs to be fixed in https://github.com/bridgecrewio/checkov/blob/master/checkov/kubernetes/checks/Seccomp.py#L44:L48 as well for workloads.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
....
spec:
...
...
  template:
  ...
  ...
    spec:
    ....
    ....
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
```
