### ISSUE TITLE
CKV2_K8S_5 fails when `resources: ["secrets"]` even if `resourceNames` are specified

### ISSUE THREAD

**Issue by simplyaduck** [bridgecrewio/checkov#7110]
**Describe the issue**
To allow an RBAC role to access specific secrets, according to the K8S [docs](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#referring-to-resources), is to specify the resource type (`secrets`, in this example), then the `resourceNames` of resources it has access to. This will allow it to only have access to the specified resource names. 

[CKV2_K8S_5](https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/no-serviceaccountnode-should-be-able-to-read-all-secrets) Fails even when  `resourceNames` is specified, (meaning the Service Account does not actually have permission to read all secrets) 

**Examples**
K8S yaml config 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "my-role"
  namespace: my-namespace
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames:
    - "my-secret-resource"
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "my-role-binding"
  namespace: my-namespace
subjects:
- kind: ServiceAccount
  name: "my-service-account"
roleRef:
  kind: Role
  name: "my-role"
  apiGroup: rbac.authorization.k8s.io
```

Result: 
```
Check: CKV2_K8S_5: "No ServiceAccount/Node should be able to read all secrets"
	FAILED for resource: RoleBinding.my-namespace.my-role-binding
	File: /test.yaml:14-25
	Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/kubernetes-policies/kubernetes-policy-index/no-serviceaccountnode-should-be-able-to-read-all-secrets

		14 | apiVersion: rbac.authorization.k8s.io/v1
		15 | kind: RoleBinding
		16 | metadata:
		17 |   name: "my-role-binding"
		18 |   namespace: my-namespace
		19 | subjects:
		20 | - kind: ServiceAccount
		21 |   name: "my-service-account"
		22 | roleRef:
		23 |   kind: Role
		24 |   name: "my-role"
		25 |   apiGroup: rbac.authorization.k8s.io
```

Expected Result: 
Check should pass 

**Version (please complete the following information):**
 - Checkov Version: 3.2.405
