### ISSUE TITLE
CKV_K8S_31 failure with RuntimeDefault configured for workloads

### ISSUE THREAD

**Issue by VimukthiPerera** [bridgecrewio/checkov#719]
**Describe the bug**
Please see #710

**To Reproduce**
Please see #710

**Expected behavior**
Please see #710

**Additional context**
The bug reported in #710 needs to be fixed for workloads in https://github.com/bridgecrewio/checkov/blob/master/checkov/kubernetes/checks/Seccomp.py#L44:L48 as well.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
....
spec:
...
...
  template:
  ...
  ...
    spec:
    ....
    ....
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
```

**Related PRs**
#711
