### ISSUE TITLE
Multiple skip checks in string now throws exception

### ISSUE THREAD

**Issue by Spencer0** [bridgecrewio/checkov#818]
This same command worked fine yesterday.
Today
![image](https://user-images.githubusercontent.com/38340800/105902929-1f6ee980-5fd4-11eb-8144-7cb1a608372b.png)

Yesterday
![image](https://user-images.githubusercontent.com/38340800/105903165-68bf3900-5fd4-11eb-9632-783409451dd9.png)

Docker image context (pipeline file)
```
    - step: &checkov
        name: Checkov
        image:
          name: bridgecrew/checkov:latest
          entrypoint:
            - '/usr/bin/env'
            - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
        script:
          - checkov -d . --skip-check "CKV_AWS_97,CKV_AWS_26"
```
         
I could of missed what the new syntax *should* be.  Any workarounds would be great.

**Comment by Spencer0** [comment]
https://github.com/bridgecrewio/checkov/commit/8bf93948e6a6f2b4b07473a30a11b039e8fa6752

Likely this commit but 🤷

**Comment by schosterbarak** [comment]
@mikeurbanski1 can you take a look?

**Comment by mikeurbanski1** [comment]
It's not multiple skip checks, it has to do with CFN tags - likely either a conditional tag block like this:

```
Tags:
        - !If
          - CreateVpc
          - Key: PublicRouteDependency
            Value: !Ref TerraformPublicGatewayRoute
            PropagateAtLaunch: false
          - !Ref AWS::NoValue
```

Or something like an EKS::Nodegroup with tags like this:

```
Tags:
  Name: ...
```

It's fixed here: https://github.com/bridgecrewio/checkov/pull/819

Thanks for reporting it.
