### ISSUE TITLE
checkov hanging. Running in docker in EC2 instance

### ISSUE THREAD

**Issue by lewissw** [bridgecrewio/checkov#985]
**Describe the bug**
Looks like the process is stuck and times out. 

**To Reproduce**
checkov -d . --external-checks-dir /checkov/custom_checks/ --no-guide --skip-check CKV_AWS_53,CKV_AWS_54,CKV_AWS_55,CKV_AWS_56,CUSTOM_AWS_001
/bin/bash: line 117:     9 Killed                  checkov -d . --external-checks-dir /checkov/custom_checks/ --no-guide --skip-check CKV_AWS_53,CKV_AWS_54,CKV_AWS_55,CKV_AWS_56,CUSTOM_AWS_001

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by schosterbarak** [comment]
@lewissw those it happens when you run the same version of checkov on files locally?

**Comment by lewissw** [comment]
Hi think I tracked the issue down:
in: checkov/blob/master/checkov/terraform/checks/utils/iam_cloudformation_document_to_policy_converter.py

This line expected a list:
```
            if "Resource" in statement:
                statement["Resource"] = str(statement.pop("Resource")[0])
```
              
but I had this in my CF:
```
DcpCloudWatchCsocPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DcpCloudWatchCsocPolicies
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: ['cloudwatch:DescribeAlarms']
          Resource:
            !Sub "arn:aws:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:Overall*"
      Groups: [!Ref 'DcpCloudWatchCsocUserGroup']
```

Which resulted in:
_File "C:\Users\802996686\AppData\Local\Programs\Python\Python38\lib\site-packages\checkov\terraform\checks\utils\iam_cloudformation_document_to_policy_converter.py", line 13, in convert_cloudformation_conf_to_iam_policy
    statement["Resource"] = str(statement.pop("Resource")[0])
KeyError: 0_

If I changed it to a list, i.e.
```
          Resource:
          - !Sub "arn:${AWS::Partition}:cloudwatch:${AWS::Region}:${AWS::AccountId}:alarm:Overall*"
```

  it works
