### ISSUE TITLE
CKV_AWS_111 - cloudformation  check cloudwatch:PutMetricData

### ISSUE THREAD

**Issue by cbuto** [bridgecrewio/checkov#990]
**Describe the bug**
When running checkov against a cloudformation template with an IAM policy including the action `cloudwatch:PutMetricData` and a condition limiting the action to a specific namepace, the `CKV_AWS_111` rule is triggered. Since [PutMetricData](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazoncloudwatch.html#amazoncloudwatch-PutMetricData) doesn't support limiting by a resource, the condition seems like it should be a sufficient control to limit write access. 

**To Reproduce**
1. Create a Cloudformation template containing a policy that looks like:
```
- Sid: AllowPutMetricData
  Effect: Allow
  Action:
    - cloudwatch:PutMetricData
  Resource: "*"
  Condition:
    StringEquals:
      cloudwatch:namespace: Namespace
```
2. Run `checkov -d </path/to/cloudformation> --quiet`
3. You should see checkov flag the policy as a violation of `CKV_AWS_111`

**Expected behavior**
I expect checkov to consider that policy valid for the `CKV_AWS_111` rule.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Checkov Version 1.0.844

Thanks ahead of time for reviewing this and thanks for the awesome tool!
